### ISSUE TITLE
Ignore some links

### ISSUE THREAD

**Issue by st3v3nmw** [st3v3nmw/obsidian-spaced-repetition#1]
Ignore links used for navigation, etc.

Much easier to ignore entire files, like those used for indexing.

**Comment by linfz94** [comment]
yes, provide an option to ignore some folders will be better.

**Comment by st3v3nmw** [comment]
@linfz94,

I've added a mechanism to review only notes with certain tags.
This is available in the settings of the latest release. Do check it out.
