### ISSUE TITLE
review under folders or tags

### ISSUE THREAD

**Issue by vipassanak** [st3v3nmw/obsidian-spaced-repetition#10]
It is inconvenient for me to set review: false on hundreds of notes since I have more than 2 thousands notes.

I only need to review certain notes under some folders or tags, especially tags.

Anyway ,it is a great plugin.

**Comment by st3v3nmw** [comment]
Hello, I'll work on fixing that in a few. I'll start with the tags.

**Comment by st3v3nmw** [comment]
I've added a mechanism to review only notes with certain tags.
This is available in the settings of the latest release. Do check it out.

**Comment by vipassanak** [comment]
This is a great update
