### ISSUE TITLE
Respect tags in YAML

### ISSUE THREAD

**Issue by Ampa** [st3v3nmw/obsidian-spaced-repetition#100]
I don't think the plugin reads tags in YAML.

Example...

---
tags: [review]
---

Could this please be added?

**Comment by st3v3nmw** [comment]
It does, I added support for this in #28.
I created a new note and added the `tags: [review]` YAML & it works just fine.
Do you have any error(s) on the developer console? (`ctrl` + `shift` + `i`)

**Comment by Ampa** [comment]
Thanks.
I confirm that it does work as you describe.
Not sure whether I was tired and missed it, or whether there was a glitch, but either way the YAML tag is working today!

**Comment by st3v3nmw** [comment]
Okay, thanks. I'll close this now.
