### ISSUE TITLE
[Bug]: sidebar content didn't have indent

### ISSUE THREAD

**Issue by Newdea** [st3v3nmw/obsidian-spaced-repetition#1000]
### Describe the bug

sidebar content didn't have indent
FYI, I have fixed this bug.

![Snipaste_2024-06-22_15-27-52](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/9208450/67bf4d98-bdd8-45fd-97f4-415c69908ec4)

### To Reproduce

open sidebar panel

### Expected behavior

sidebar content should have indent for better view

![Snipaste_2024-06-22_15-36-08](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/9208450/9ef5b906-9fbb-4e7e-83c8-c8f6c0cfb8de)

### OS of your device

win10

### Obsidian version

1.6.3

### Plugin version

1.12.4

### Installer version

1.4.13

**Comment by pfabri** [comment]
I was just about to report this myself. Amazing that you have not only reported but also fixed it too! Many thanks!
