### ISSUE TITLE
[FEAT]: Be able to group flashcards

### ISSUE THREAD

**Issue by Michael679089** [st3v3nmw/obsidian-spaced-repetition#1004]
### Is your feature request related to a problem? Please describe.

I don't like that my flashcards aren't organized.

### Describe the solution you'd like

Be able to categorize flashcards using tags #

**Comment by ronzulu** [comment]
Have you seen the existing support for hierarchies of decks, cards within multiple decks etc
https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#decks

If your use case doesn't match the existing functionality, you will need to explain in much greater detail what you are after, including the supply of examples.

**Comment by ronzulu** [comment]
Hi there, as we haven't heard back from you and there isn't enough information in your description, I'm closing this now. Feel free to reopen it if you can provide further detail.
