### ISSUE TITLE
[Bug]: please support the arabic question mark (؟)

### ISSUE THREAD

**Issue by xolvum** [st3v3nmw/obsidian-spaced-repetition#1009]
### Describe the bug

basically when trying to do the multi-line card

the plugin seems to only recognize it if i used the question mark that looks to the left (?)

so i have to switch the layout everytime. 

is there a way to also support the one that looks to the right (؟)

and thanks for the project.

### To Reproduce

1 - make an arabic multiline card
2 - type ؟ between the lines

the card is not picked up by the plugin 

### Expected behavior

it would be great if it was available to use the same arabic question mark

### OS of your device

android

### Obsidian version

v1.6.5

### Plugin version

v1.12.4

**Comment by ronzulu** [comment]
Hi @xolvum, I haven't tested this, but I hope this should work.

In settings, update the following:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/14e9f589-aeb6-47fb-99cc-082328a2b805)

to
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/b8d2592c-e3e2-409f-8b54-9492e24481a0)

Let me know it that works.

Cheers
Ronny

**Comment by azizabogoda** [comment]
I came across this same problem. I use Arabic and English in the same vault. Would a good solution be to allow multiple separators? Maybe separate by a comma or multiline: 
?
؟

**Comment by ronzulu** [comment]
Hi @azizabogoda sounds like a good solution, similar to 
[ enable two or more symbles for Multi-line style (Separated by ?) multilanguage users #471 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/471)

Regarding the separator between tokens, I'd suggest we recognize any whitespace (space, newline etc). This is what is currently used when interpreting multiple tags (e.g. the "flashcards tags" setting)

**Comment by xolvum** [comment]
thanks @ronzulu and sorry for the late reply

i followed your advice and it actually worked 

thank you for the help

**Comment by xolvum** [comment]
> I came across this same problem. I use Arabic and English in the same vault. Would a good solution be to allow multiple separators? Maybe separate by a comma or multiline: ? ؟

hey @azizabogoda another thing is to use a plus sign (+) as a seperator. i tested the equal sign and it made the previous line as a header


so you can use maybe ++ and +++ for bidirectional cards, you got the idea.



and sorry i will close this issue since my problem was not a bug after all?
idk how github works 😅
