### ISSUE TITLE
multiple cloze

### ISSUE THREAD

**Issue by s1avash26** [st3v3nmw/obsidian-spaced-repetition#1016]
### Is your feature request related to a problem? Please describe.

a simple request.

### Describe the solution you'd like

Hello,
I really liked this plugin and want to use it, sometimes I want to highlight more than one word in a sentence to use it "spaced repetition" but it's shown in 2 separate cards, if they appear in one card and I click on "show the answer" and show both of them at the same time in same page it would be great. could you please add this feature.
Thank you so much <3

**Comment by ronzulu** [comment]
Hi @s1avash26 

@MotaOcimar has contributed some code, currently in the process of being reviewed before being included in the mainstream release.

If you could look at https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/943 the section called "Classic Clozes", I believe that that will give you what you are after.


Cheers
Ronny

**Comment by st3v3nmw** [comment]
Hi.

With the new cloze patterns, I think this is currently supported:

> `==[123;;]answer[;;hint]==`

For instance, this pattern picks up `==highlights==` but you can add Anki-like sequencing. For instance `==1;;this== and ==1;;this== creates a single card` (similar to Anki's `{{c1:this}} and {{c1::this}} creates a single card`):

![image](https://github.com/user-attachments/assets/35ec8dba-8df3-40bf-9320-484b44a7beb9)

 You  can also add hints to your clozes, so for instance `==this;;hint== will be rendered as`:

![image](https://github.com/user-attachments/assets/4556ea0b-45f0-4e3b-91ed-f072909b796d)

**Comment by s1avash26** [comment]
Thank you so much, this works for me
{{1;;this}} and {{1;;this}} creates a single card.

**Comment by oumout** [comment]
you have no idea how this tip/feature helped me.. thanks a lot..
