### ISSUE TITLE
Tags does not create decks

### ISSUE THREAD

**Issue by semits20** [st3v3nmw/obsidian-spaced-repetition#102]
at the time of reviewing flashcard, the assigned tags are not being created as decks.
Is there something I am missing? because i think if i add tags then it would reflect as decks at the time of review. Or should i add tags in YAML

**Comment by st3v3nmw** [comment]
Have you added the tags you want to use in the settings? Because what you're currently doing sounds correct.
Maybe a couple illustrative screenshots might be helpful for me to get to the root of the problem.
Is this related to what you raised in #87?

**Comment by semits20** [comment]
Before raising this issue i didn't added tags in the settings, but i did after u mentioned here. Still, I can only see two tags as decks, the rest are not being shown. I am extremely sorry I misunderstood the way these tags works, I thought it is intuitive means after adding #flashcards I can add different tags like neuracache do with their software.

**Comment by semits20** [comment]
One more thing i would like to show, which i think if it can be implemented then life would be very easy, it would be a delight to create flashcards.
![2021-05-26 (2)](https://user-images.githubusercontent.com/79163835/119694958-5c0bfe00-be6b-11eb-9bc4-d896ccd24765.png)
see in this screenshot, i have tried to create a flashcard within this block means my outliner plugin was active, this does not reflect in my flashcard. If flashcard within sub child could have been created, then it would be awesome

**Comment by st3v3nmw** [comment]
You can change the settings to have the flashcards scheduling placed in the last line of the flashcard's text. That should solve this problem.

**Comment by st3v3nmw** [comment]
So, for the decks, the plugin picks only the first matching tag and uses that for the deck.

**Comment by semits20** [comment]
![2021-05-26 (1)](https://user-images.githubusercontent.com/79163835/119704414-3f74c380-be75-11eb-8987-b13525003b2f.png)
as you can see in this screenshot i have added different tags but only first two tags are shown. The rest of the tags are not shown as decks, so is it how it works? I am just asking, i am not aware about it.

And related to the settings to have the flashcards scheduling, it is already turned on. Still, it does not reflect in my workflow.

**Comment by Couriuss** [comment]
I had the same problem, make sure you haven't press enter accidentally. If you press enter the tags are not read correctly.

**Comment by st3v3nmw** [comment]
I've made a fix to allow splitting with arbitrary numbers of any whitespace character, newlines included. That should fix what @Couriuss raised.

**Comment by st3v3nmw** [comment]
Hey @semits20, could you give us an update on this?

**Comment by Masstronaut** [comment]
I just installed the plugin and was having a very similar issue. I ended up figuring out a workaround. To repro:

1. Install the plugin with default settings.
2. Add `#flashcards` in an existing.
3. Add Cloze deletions (the `disable cloze cards?` option is not enable). I put three on a single line.
4. Run the `Spaced Repetition: Review flashcards` command
5. Observe that there are no decks in the dialogue.
6. Add a single line flashcard using the default separator `::`
7. Repeat step 4
8. Observe that the Cloze deletions AND the single line flashcard have now appeared.

**Comment by st3v3nmw** [comment]
@Masstronaut, there's a bug with the cloze cards. It requires a blank line after the card text. I'll fix this.

**Comment by st3v3nmw** [comment]
Closing

**Comment by jamesstephenbrown** [comment]
I found that it was only preexisting tags that didn't show up. If I changed my #History to #HistoryCards (in both the settings and the note) and used that, it worked.
