### ISSUE TITLE
[Bug]: Embedded notes are displayed twice starting from version 1.12.5

### ISSUE THREAD

**Issue by ASEM000** [st3v3nmw/obsidian-spaced-repetition#1041]
### Describe the bug

Embedded notes are shown twice.

### To Reproduce

Minimal repro

Starting with a trivial embedded note like the following

```
#flashcard/test

Test multiline
?
![[Test Embed]]
```
![image](https://github.com/user-attachments/assets/c50e1ff8-8834-4ef1-a104-d636a302eb50)

Show answer button show the embedded note twice

![image](https://github.com/user-attachments/assets/59a70c91-e6a4-4eb0-ad69-f1b195e27c20)

P.S. This behavior is observed starting from 1.12.5

### Expected behavior

The embedded note should be shown once.

### OS of your device

Mac os 14.5

### Obsidian version

1.6.7

### Plugin version

1.12.5

### Installer version

1.5.12

**Comment by ronzulu** [comment]
Could you please send through the two markdown files (attach to your post, not copy/paste)

**Comment by ASEM000** [comment]
Sure, 

[Test Spaced Repetition.md](https://github.com/user-attachments/files/16509859/Test.Spaced.Repetition.md)
[Test Embed.md](https://github.com/user-attachments/files/16509862/Test.Embed.md)

**Comment by adakka** [comment]
I have the same problem

**Comment by ronzulu** [comment]
The fix is available as a beta release at:
https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/1011
