### ISSUE TITLE
能否将“下划线”增加为“环形填空”[FEAT]: 

### ISSUE THREAD

**Issue by JawnSong** [st3v3nmw/obsidian-spaced-repetition#1044]
### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/287647e2-108d-4d0e-abde-2bd7f2bab2be)

**Comment by ronzulu** [comment]
According to google translate

> Can "underline" be added to "fill in the blanks"?

I assume you want to be able to configure the plugin so that text within underline markup will be treated as a cloze.

There are existing issues that relate to this, such as #387 

If I have misunderstood, reopen and communicate in English.
