### ISSUE TITLE
[FEAT]: Hide note title when reviewing

### ISSUE THREAD

**Issue by ferrouswheel** [st3v3nmw/obsidian-spaced-repetition#1047]
### Is your feature request related to a problem? Please describe.

I often have small notes that contain the definition of a concept.

When I use the forward and reverse definition `name of concept:::definition`, the answer for the reverse direction is given away by showing the title of the note containing the card at the top of the review UI.

### Describe the solution you'd like

I would like the option to hide/suppress the note title while reviewing. I'm happy to have this as a global option because I never need the note title, it only serves to give away the answer meaning I don't actually need to use my memory so much.

**Comment by ferrouswheel** [comment]
real example from my notes, "reverberating activity" is the note title, but it is also the answer to this card.

<img width="520" alt="Untitled" src="https://github.com/user-attachments/assets/581def37-db9e-4a12-933f-197cea104eb8">

**Comment by ronzulu** [comment]
Hi there, fortunately there already is a global option, but is enabled by default.

![image](https://github.com/user-attachments/assets/890db8d2-938e-4595-b7aa-0ddc91c563b4)

**Comment by ferrouswheel** [comment]
Ah, thank you - apologies I missing that.

**Comment by ronzulu** [comment]
No problem, nice to get some easy questions sometimes!
