### ISSUE TITLE
[FEAT]: a button "again" for reviewing cards

### ISSUE THREAD

**Issue by adakka** [st3v3nmw/obsidian-spaced-repetition#1063]
### Describe the solution you'd like

 would appreciate it if you could add a button for reviewing cards on the same day. Currently, the minimal interval is at least one day, if I understand it correctly.

**Comment by ronzulu** [comment]
Hi there, thanks for the suggestion.

It does seem similar to other open suggestions, for example [ [FEAT] Support multiple card reviews in a single day #906 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/906).

It would be best if you close this issue, and add a comment on to 1 of the existing open issues.

Regards
Ronny

**Comment by adakka** [comment]
Thanks
