### ISSUE TITLE
[Bug]: Android: Folders to ignore stops decks from opening

### ISSUE THREAD

**Issue by IuriTPena** [st3v3nmw/obsidian-spaced-repetition#1064]
### Describe the bug

If we use the "Convert folders to decks and subdecks option" and add anything in the "Folders to ignore" list, whenever we try to review all the flashcards, nothing happens.

### To Reproduce

1. Activate "Convert FOlders to decks and subdecks"
2. Add some folders in "Folders to ignore"
3. Review flashcards
3a. From the bottom bar click "Review flashcards"
3b. From the command palette use "Spaced Repetition: Review flashcards from all notes"
4. Nothing appens

### Expected behavior

With step 3a or 3b the decks should appear, but nothing happens

### OS of your device

Android

### Obsidian version

v1.6.7

### Plugin version

v1.12.25

**Comment by ronzulu** [comment]
Hello, this Issue has been fixed and is available as a beta release at:
[Beta release of outstanding PRs #1011](https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/1011)

If you are able to try that, and let us know if that solves your issue that would be appreciated. 

Cheers
Ronny

**Comment by IuriTPena** [comment]
Can confirm, it has been fixed in the beta.

**Comment by ronzulu** [comment]
Thanks
