### ISSUE TITLE
[Bug]: Crash in Android after adding IGHORING FOLDER!

### ISSUE THREAD

**Issue by Ahatzoda-Tehronshoh** [st3v3nmw/obsidian-spaced-repetition#1065]
### Describe the bug

After adding "Folders to Ignore" in settings, command does not become active!
I change isEqualOrSubPath method and now it is working good in android and windows. I replace isEqualOrSubPath method to this:
```
function isEqualOrSubPath(toCheck, rootPath) {
 // Преобразуем пути в нижний регистр и заменяем обратные и прямые слэши на системный разделитель
  const normalizePath = (path) => {
    return path
      .toLowerCase()
      .replace(/\\/g, '/')
      .split('/')
      .filter((p) => p !== '');
  };

  const rootPathSections = normalizePath(rootPath);
  const pathSections = normalizePath(toCheck);

  if (pathSections.length < rootPathSections.length) {
    return false;
  }

  for (let i = 0; i < rootPathSections.length; i++) {
    if (rootPathSections[i] !== pathSections[i]) {
      return false;
    }
  }

  return true;
}
```

### To Reproduce

Android Version Obsidian -> Spaced Repitition Plugin -> Settings -> Folders to Ignore -> adding some folder path -> execute command

### Expected behavior

Can not execute Plugin's Command

### OS of your device

Android 13

### Obsidian version

1.6.7

### Plugin version

1.12.5

**Comment by ronzulu** [comment]
Please see #1064

**Comment by Ahatzoda-Tehronshoh** [comment]
> Please see #1064

Thank you for replying. I have read bug #1064, but I did not activate "Convert Folders to decks and subdecks".

My bug appears after adding a folder in "Folders to Ignore", and it does not disappear even after deleting all of them. 
I could fix it only after uninstalling and installing again. 
I debugged and handled the error in that method and rewrote the method myself. After rewriting, it is working well for the Android version and the Windows version also.

**Comment by ronzulu** [comment]
> I debugged and handled the error in that method and rewrote the method myself. After rewriting, it is working well for the Android version and the Windows version also.

That function was fixed in [[FIX] isEqualOrSubPath function](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/1048)

That fix is included in the beta release at:
[Beta release of outstanding PRs #1011](https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/1011)

If you are able to try that, and let us know if that solves your issue that would be appreciated. 

Cheers
Ronny

**Comment by Ahatzoda-Tehronshoh** [comment]
I am going to try it!
Thanks you!

**Comment by ronzulu** [comment]
Thanks  @Ahatzoda-Tehronshoh
