### ISSUE TITLE
[Bug]: plugin does not detect tags/cards after recent update

### ISSUE THREAD

**Issue by adakka** [st3v3nmw/obsidian-spaced-repetition#1077]
### Describe the bug

plugin does not detect tags/cards after recent update

### To Reproduce

1. Updated plugin
2. No cards can be displayed

### Expected behavior

cards displayed normally

### OS of your device

Windows 11 & iOS

### Obsidian version

1.7.1

### Plugin version

1.12.6

### Installer version

1.4.13

**Comment by yett1873** [comment]
I'm having a similar issue: the plugin stops recognizing new multiline cards but still recognizes cards with clozes. 
My Obsidian is on 1.7.1 and the issue resolves once I roll back to 1.12.5.

**Comment by ronzulu** [comment]
Hi there

I haven't been able to reproduce the problem, could you please send through (as an attachment, not copy/paste)

1. Your configuration file, for example on my machine this is located at:
`D:\Obsidian\.obsidian\plugins\obsidian-spaced-repetition\data.json`

2. A sample markdown file that includes cards that are no longer detected.

Also, with `1.12.6` running:
3. A screenshot of the deck selection dialog, e.g.:
![image](https://github.com/user-attachments/assets/9718a746-6deb-4baa-a2c7-a9b2361b1fea)

Cheers
Ronny

**Comment by adakka** [comment]
Thanks for your email.

There you go.
[cid:94583cb5-8873-432f-8b1e-68b073fa9704]
________________________________

**Comment by ronzulu** [comment]
Thanks for that, unfortunately GitHub only extracted the text from your email to include in the post. Any attachments that you had in it were ignored.

I think you'll need to use the GitHub website and create a post, and attach the files there manually.

**Comment by adakka** [comment]
![image](https://github.com/user-attachments/assets/666e5269-42ff-4507-bafa-2648b6b5313d)
[data.json](https://github.com/user-attachments/files/17071347/data.json)
[fc immuno.md](https://github.com/user-attachments/files/17071357/fc.immuno.md)

**Comment by adakka** [comment]
The previous version works without any problems

**Comment by Smitty010** [comment]
Here's an error I'm seeing a lot of
plugin:obsidian-spaced-repetition:9740 Unexpected error: SyntaxError: Expected ":", comment, end of line, or whitespace but "=" found. (at plugin:obsidian-spaced-repetition:5023:23)
    at new peg$SyntaxError (plugin:obsidian-spaced-repetition:5023:23)
    at eval (plugin:obsidian-spaced-repetition:5553:18)
    at Object.peg$parse [as parse] (plugin:obsidian-spaced-repetition:5554:10)
    at eval (plugin:obsidian-spaced-repetition:6259:27)
    at Array.map (<anonymous>)
    at generate (plugin:obsidian-spaced-repetition:6257:32)
    at generateParser (plugin:obsidian-spaced-repetition:9450:43)
    at parseEx (plugin:obsidian-spaced-repetition:9732:21)
    at NoteQuestionParser.parseQuestions (plugin:obsidian-spaced-repetition:11753:20)
    at NoteQuestionParser.doCreateQuestionList (plugin:obsidian-spaced-repetition:11719:41)
    at NoteQuestionParser.createQuestionList (plugin:obsidian-spaced-repetition:11695:32)
    at async NoteFileLoader.load (plugin:obsidian-spaced-repetition:11923:26)
    at async OsrAppCore.loadNote (plugin:obsidian-spaced-repetition:12900:18)
    at async OsrAppCore.processFile (plugin:obsidian-spaced-repetition:12825:14)
    at async OsrAppCore.loadVault (plugin:obsidian-spaced-repetition:12934:9)
    at async _SRPlugin.sync (plugin:obsidian-spaced-repetition:26251:5)
    at async eval (plugin:obsidian-spaced-repetition:26052:11)

Could it be that it isn't processing the spaced repetition if we aren't using the standard symbols for spaced repetition?

**Comment by st3v3nmw** [comment]
@Smitty010, I think that's the case.. The parser isn't handling the symbols correctly. What separators are you using?

**Comment by adakka** [comment]
I'm using "@@". This separator has worked perfectly in the previous versions.

**Comment by st3v3nmw** [comment]
I was able to reproduce @Smitty010's error based on what @adakka provided. The issue occurs when none of the "Convert X to clozes?" options are turned on which was messing up the parser. There's a fix in #1081. I'm waiting for a code review.. We'll release the fix ASAP.

**Comment by Smitty010** [comment]
Here's my data.json file if you want to test it:
```
{
  "settings": {
    "flashcardEasyText": "Easy",
    "flashcardGoodText": "Good",
    "flashcardHardText": "Hard",
    "flashcardTags": [
      "#flashcards",
      "#piano-flash",
      "#course-flash"
    ],
    "convertFoldersToDecks": false,
    "cardCommentOnSameLine": false,
    "burySiblingCards": false,
    "showContextInCards": true,
    "flashcardHeightPercentage": 80,
    "flashcardWidthPercentage": 40,
    "randomizeCardOrder": null,
    "flashcardCardOrder": "DueFirstRandom",
    "flashcardDeckOrder": "PrevDeckComplete_Sequential",
    "convertHighlightsToClozes": false,
    "convertBoldTextToClozes": false,
    "convertCurlyBracketsToClozes": false,
    "singleLineCardSeparator": ":>",
    "singleLineReversedCardSeparator": "<:>",
    "multilineCardSeparator": "?",
    "multilineReversedCardSeparator": "??",
    "editLaterTag": "#edit-later",
    "enableNoteReviewPaneOnStartup": true,
    "tagsToReview": [
      "#review"
    ],
    "noteFoldersToIgnore": [
      "SecondBrain/Templates",
      "SecondBrain/Attachments",
      "SecondBrain/AI Prompts",
      "SecondBrain/People"
    ],
    "openRandomNote": false,
    "autoNextNote": false,
    "disableFileMenuReviewOptions": false,
    "maxNDaysNotesReviewQueue": 365,
    "initiallyExpandAllSubdecksInTree": false,
    "baseEase": 250,
    "lapsesIntervalChange": 0.5,
    "easyBonus": 1.3,
    "maximumInterval": 36525,
    "maxLinkFactor": 1,
    "showDebugMessages": false,
    "showFileNameInFileLink": false,
    "singlelineCardSeparator": ":>",
    "singlelineReversedCardSeparator": "<:>"
  },
  "buryDate": "2024-09-15",
  "buryList": [],
  "historyDeck": "chatgpt-prompt"
}
```

**Comment by st3v3nmw** [comment]
@adakka @yett1873 @Smitty010, please try the new release (v1.12.7) and let us know if it fixes the issue for you.

**Comment by adakka** [comment]
Now I can see the notes. Thank you.
Furthermore, the problem of "double cards" has also been fixed.
I'll keep you updated.

________________________________

**Comment by Smitty010** [comment]
That solved my problem as well
