### ISSUE TITLE
Request to have link to file displaying the actual file name

### ISSUE THREAD

**Issue by Couriuss** [st3v3nmw/obsidian-spaced-repetition#108]
In the review panel, on the upper left corner, there is the link to file named: 'open link'.
I'd like to ask to change the generic 'open file' to the name of the file. So, in example, if the file is named: 'Microeconomics' it would show Microeconomics as a link to file.

The displaying of the file name in the context function will become redundant if applied.

The why of such request is: because the context function doesn't work in obsidian comments (%%) i'd like to have at least the file name displayed so it gives me a little of context.

**Comment by st3v3nmw** [comment]
Fix should be available in the next release.

**Comment by roamhacker** [comment]
It would be good if this is a switch in settings, since for me the file name might reveal the answer.

**Comment by st3v3nmw** [comment]
Dang, looks like I have to revert something LOL :).
