### ISSUE TITLE
[Bug]: Screen Freezes after update 1.12.6

### ISSUE THREAD

**Issue by TheBrightSoul** [st3v3nmw/obsidian-spaced-repetition#1110]
### Describe the bug

Hello,  
I've been encountering an issue for quite some time (since the release of version 1.12.6). Whenever I update this plugin, it freezes my screen, causing everything to stop, and Obsidian becomes unresponsive. I initially assumed it would be resolved in subsequent updates, but unfortunately, it hasn't been addressed yet. Given the delay, I decided to report the issue.

### To Reproduce

1. Update the plugin
2. Screen freezes

### Expected behavior

It should be responding properly but it doesn't it just freezes the Obsidian.

### Screenshots

Here is the video of the issue

https://drive.google.com/file/d/17bClCUU9XxD9AUTLXoV_RwErsbUq0vFu/view?usp=sharing

### OS of your device

Win11

### Obsidian version

Latest

### Plugin version

1.12.5

### Installer version

I don't know

### Config file

Main file [data.json](https://github.com/user-attachments/files/17273400/data.json)
I don't have violated file

**Comment by st3v3nmw** [comment]
Thanks for the bug report @TheBrightSoul . There was a parser change which has made the plugin much slower... I'm working on a fix.

Similar to #1111.

**Comment by st3v3nmw** [comment]
Hi,

I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that should remedy the performance problem. Please try it and let us know if the performance has improved.

I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.

Cheers.

**Comment by st3v3nmw** [comment]
Closing this now..
