### ISSUE TITLE
[Bug]: SR Plugin/Parser causes whole Obsidian Application to freeze (mobile & desktop)

### ISSUE THREAD

**Issue by cstelmach** [st3v3nmw/obsidian-spaced-repetition#1111]
### Describe the bug

Upon opening the application, the SR Plugin causes the whole Obsidian App to freeze as soon as the plugin loads, as in no action is possible.

This is quite concerning on mobile. If I didn't have a 1s delay due to `plugin groups` I would have had to completely reset my vault because of this spaced repetition plugin bug. 

This is may be somehow connected to the flashcards parser functionality changed in 1.12.6, since this is the last step shown if I turn on the debugger functionality on desktop obsidian (see screenshots). Also if I remove all tags (as in no flashcards notes), then the app starts normally. 

I've found this error only happens in the plugin versions 1.12.6+. (tested .5, .6, .7, .8, .9)
I'm now using the 1.12.5 version, as it at least allows opening the application. It still comes with bugs and errors, but ...

---

After trying out a few things, there is a markdown in the context which by itself causes 77s freezing.

### To Reproduce

1. Open the app with the markdown file as flashcard
2. wait 1 second
3. try to click navigation or anything else. Application frozen.
4. Wait for a few minutes for it to unfreeze, hoping it completes (if you have a single markdown file, else forget it).

### Expected behavior

The app is functional. 

### Screenshots

v1.12.5 (doesn't freeze)
<img width="357" alt="image" src="https://github.com/user-attachments/assets/437c6248-781d-43e0-8345-f0846bd05507">

v1.12.9 (freezes, as any above 1.12.6 does too)
<img width="357" alt="Screenshot 2024-10-06 at 23 08 19" src="https://github.com/user-attachments/assets/d7dd82ea-8a24-44fb-b669-aba4e6004f39">

### OS of your device

MacOS 14.4.1 (23E224)

### Obsidian version

v1.6.7

### Plugin version

v1.12.6/7/8/9

### Installer version

'5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36'

### Additional context

The console output of a single markdown file, which nevertheless causes the application to load for 77s on desktop obsidian:

````
plugin:obsidian-spaced-repetition:12980 Text to parse:
<<<




## Important Concepts

### Text Functions

- **`lower(string)`**: Converts the given string to lowercase.
  
  Example:
  ```sql
  SELECT lower('The') FROM textfun;
  -- Result: 'the'
  ```


- **`upper(string)`**: Converts the given string to uppercase.
  
  Example:
  ```sql
  SELECT upper('tom') FROM textfun;
  -- Result: 'TOM'
  ```

- **`substring(string from int for int)`**: Extracts a substring from the specified position and for the specified length.
  
  Example:
  ```sql
  SELECT substring('Thomas' from 2 for 3) FROM textfun;
  -- Result: 'hom'
  ```

- **`substring(string from pattern)`**: Extracts a substring that matches a POSIX regular expression.
  
  Example:
  ```sql
  SELECT substring('Thomas' from '...$') FROM textfun;
  -- Result: 'mas'
  ```

- **`position(substring in string)`**: Finds the position of a substring within a string.
  
  Example:
  ```sql
  SELECT position('om' in 'Thomas') FROM textfun;
  -- Result: 3
  ```

- **`overlay(string placing string from int for int)`**: Replaces a substring within a string starting from a specified position.
  
  Example:
  ```sql
  SELECT overlay('Txxxxas' placing 'hom' from 2 for 4) FROM textfun;
  -- Result: 'Thomas'
  ```

- **`trim([leading | trailing | both] [characters] from string)`**: Removes the longest string of characters (spaces by default) from the start, end, or both ends of a string.
  
  Example:
  ```sql
  SELECT trim(both 'x' from 'xTomxx') FROM textfun;
  -- Result: 'Tom'
  ```

- **`translate(string, from, to)`**: Translates characters in a string from one set to another, similar to the Unix `tr` command. The `from` and `to` strings must be of equal length.
  
  Example:
  ```sql
  SELECT translate('th.p/', 'tp.', 'TP_') FROM textfun;
  -- Result: 'Th_P/'
  ```

- **`bit_length(string)`**: Returns the number of bits in a string.
  
  Example:
  ```sql
  SELECT bit_length('Jose') FROM textfun;
  -- Result: 32
  ```

- **`char_length(string)` / `character_length(string)`**: Returns the number of characters in a string.
  
  Example:
  ```sql
  SELECT char_length('Jose') FROM textfun;
  -- Result: 4
  ```

- **`octet_length(string)`**: Returns the number of bytes in a string.
  
  Example:
  ```sql
  SELECT octet_length('Jose') FROM textfun;
  -- Result: 4
  ```

- **`split_part(string, delimiter, field)`**: Splits a string by a delimiter and returns the part specified by the field index.
  
  Example:
  ```sql
  SELECT split_part('https://www.pg4e.com/neon/150000', '/', 4) FROM textfun;
  -- Result: 'neon'
  ```




>>>
plugin:obsidian-spaced-repetition:12702 The parsers grammar is provided below. You can test it with https://peggyjs.org/online.html.
plugin:obsidian-spaced-repetition:12705 {info: 'Copy the grammar by right-clicking on the property…hen, paste it in https://peggyjs.org/online.html.', grammar: '{\n    // The fallback case is important if we want…000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000\\ufeff])\n'}
plugin:obsidian-spaced-repetition:12717 New parser generated in 28 milliseconds.
plugin:obsidian-spaced-repetition:12996 Parsed cards:
 []
plugin:obsidian-spaced-repetition:28196 SR: Decks _Deck {deckName: 'root', newFlashcards: Array(0), dueFlashcards: Array(0), subdecks: Array(0), parent: null}
plugin:obsidian-spaced-repetition:28197 SR: Sync took 77842ms
````

The markdown file:
[uC13-35 Text Function In SQL 20240823-1747.md](https://github.com/user-attachments/files/17276105/uC13-35.Text.Function.In.SQL.20240823-1747.md)

### Config file

[data.json](https://github.com/user-attachments/files/17276192/data.json)

**Comment by st3v3nmw** [comment]
Thanks for the bug report @cstelmach. There was a parser change which has made the plugin much slower... I'm working on a fix.

**Comment by 4Source** [comment]
I have no freezes but I got a very long startup time if it is the first time starting obsidian after pc turned on
![image](https://github.com/user-attachments/assets/76b2e03c-1297-4cdf-bddd-cc7bcce52f94)

Second time starting obsidian it deceases drastically but still a bit high
![image](https://github.com/user-attachments/assets/9e7cff8c-859d-4c74-914f-3cb76f0600ef)

I have testet since 1.12.4 it is always about 500 to 600 ms for second startup

**Comment by st3v3nmw** [comment]
Hi all,

I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that should remedy the performance problem. Please try it and let us know if the performance has improved.

I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.

Cheers.

**Comment by st3v3nmw** [comment]
@cstelmach, please confirm if it's working fine now.
