### ISSUE TITLE
[Bug]: Convert folders to decks and subdecks turns obsidian to a laggy mess

### ISSUE THREAD

**Issue by rhhub** [st3v3nmw/obsidian-spaced-repetition#1115]
### Describe the bug

I **possibly** had this option turned on for some time without ever using it. At some point obsidian started lagging and I traced it to this plugin and this option. I turned the setting off and everything is good. Issues I had were obsidian sync needing to be initiated again, and obsidian re indexing when closing.

From system explorer I have 16000 files across 500 folders.

It was a silent failure. It's also a setting that I didn't need to enable but wanted to try out.

### To Reproduce

1. disable all other community plugins except spaced repetition.
2. enable convert folders to decks and subdecks

### Expected behavior

Either:
1. no lag
or
2. A performance warning added to the setting's button if there's no inherit bug responsible.

### OS of your device

Win10

### Obsidian version

v1.6.7

### Plugin version

v1.12.9

### Config file

[data.json](https://github.com/user-attachments/files/17351028/data.json)

**Comment by st3v3nmw** [comment]
Hi,

I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that should remedy the performance problem. Please try it and let us know if the performance has improved.

I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.

Cheers.

**Comment by st3v3nmw** [comment]
> However, after updating my settings menu disappeared.

This was fixed in v1.13.1. Thanks for the bug report!

I'll close this now.
