### ISSUE TITLE
[Bug]: Flash cards Parameter is bugged 

### ISSUE THREAD

**Issue by TheBrightSoul** [st3v3nmw/obsidian-spaced-repetition#1123]
### Describe the bug

The plugin is pulling flashcards from tags that I haven't defined in the configuration settings. Additionally, it's not including some of the tags that previously contained flashcards. For context, I recently reinstalled the plugin after uninstalling it due to a slow processing issue (which I had reported earlier). While that issue seems to be resolved, I've now encountered this new bug.

### To Reproduce

1. Add flashcards across multiple files with different tags.
2. The plugin will automatically register all flashcards from those files, even without defining the tags in the configuration.

### Expected behavior

The `FlashcardTags:` parameter should function correctly, including only the files with the specified tags. This issue is problematic, as I have numerous coding projects saved in my vault, and the plugin is incorrectly registering lines from code blocks as flashcards (see screenshots).

### Screenshots

![image](https://github.com/user-attachments/assets/42df348c-08d7-440b-af34-ecd89e4b7806)
![image](https://github.com/user-attachments/assets/dcce1205-1ac7-4e19-a17f-d1083285490b)
![image](https://github.com/user-attachments/assets/c70781d4-5be0-4b83-9cea-ec64ccf20b15)
![image](https://github.com/user-attachments/assets/112662e5-15b4-45a5-bd50-bbd68f904620)

### OS of your device

Win11

### Obsidian version

1.6.7

### Plugin version

1.13.0

### Installer version

'5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.6.5 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36'

### Config file

[data.json](https://github.com/user-attachments/files/17359510/data.json)

**Comment by st3v3nmw** [comment]
> I wasn't able to locate the option in plugin settings

It's under Flashcards > Tags & Folders.

> It worked. it's fixed now.

Thanks for confirming, I'll close this now.
