### ISSUE TITLE
[Bug]: Plugin unavailable after 1.13.0 update

### ISSUE THREAD

**Issue by thematthiasleitner** [st3v3nmw/obsidian-spaced-repetition#1124]
### Describe the bug

Hey,
Suddenly, after installing the update (1.13.0) of Spaced Repetition on my MacBook (M1, Sonoma 14.7), I neither have access to Spaced Repetition in Obsidians preferences, nor to the application as a whole.

### To Reproduce

See Screenshot

### Expected behavior

Well i guess it would be lovely to have this beautiful application up and running again.

### Screenshots

<img width="1072" alt="Capture d’écran 2024-10-14 à 14 54 34" src="https://github.com/user-attachments/assets/2277be27-640f-43c1-9680-4d362bff7b3b">

### OS of your device

Sonoma 14.7

### Obsidian version

1.6.7

### Plugin version

1.13.0

**Comment by AlberkaSP** [comment]
Same issue here, I'm also experiencing problems with Spaced Repetition after updating to version 1.13.0 on Windows 11. The plugin doesn't show up in Obsidian's preferences, and I can't access the application either.

**Comment by alberti42** [comment]
Same here. The plugin is no longer usable. It fails loading:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'contains')
    at upgradeSettings (plugin:obsidian-spaced-repetition:11543:69)
    at _SRPlugin.loadPluginData (plugin:obsidian-spaced-repetition:26650:60)
    at async _SRPlugin.onload (plugin:obsidian-spaced-repetition:26358:5)
```
The way around is to manually delete the previous configuration. Then it loads with default configurations. I did not test it thouroughly but I assume it will work.

**Comment by st3v3nmw** [comment]
Hi all, I've just made a new release that should do the upgrade properly. Please give it a try.

**Comment by st3v3nmw** [comment]
> There are no instructions. I guess one can figure it out by trial and error. Is 123 a delimiter? Or represented just an example for a content?

I'll link to the documentation in the next release. For now, here are the docs -> https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cloze-cards/#cloze-types. The "Cloze Types" & "Custom Cloze Patterns" should explain how to create custom patterns.

> `==[123;;]answer[;;hint]==`

For instance, this pattern replaces picks up `==highlights==` but you can add Anki-like sequencing. For instance `==1;;this== and ==1;;this== creates a single card` (similar to Anki's `{{c1:this}} and {{c1::this}} creates a single card`):

![image](https://github.com/user-attachments/assets/35ec8dba-8df3-40bf-9320-484b44a7beb9)

 You  can also add hints to your clozes, so for instance `==this;;hint== will be rendered as`:

![image](https://github.com/user-attachments/assets/4556ea0b-45f0-4e3b-91ed-f072909b796d)
