### ISSUE TITLE
[Bug]: Missing "View Statistics" command (v1.12.9 - v1.13.1)

### ISSUE THREAD

**Issue by AlberkaSP** [st3v3nmw/obsidian-spaced-repetition#1128]
### Describe the bug

Hi there,

Since updating to version 1.12.9 of the Spaced Repetition plugin for Obsidian, I have noticed that the command "Spaced Repetition: View statistics" no longer appears. Unfortunately, this issue persists even after updating to version 1.13.1.

### To Reproduce

1. Open the command palette in Obsidian.
2. Search for "Spaced Repetition: View statistics".
3. Notice that the command is not available.

### Expected behavior

I expected to find and be able to run the "Spaced Repetition: View statistics" command as in previous versions, but it seems to be missing.

### OS of your device

Win11 and Android

### Obsidian version

1.13.1

### Plugin version

1.13.1

### Installer version

v1.6.7

### Additional context

I really appreciate all the work that's gone into improving this plugin. It’s been an incredibly helpful tool for my workflow. Thank you so much for your time and effort on this project!

**Comment by dmantisk** [comment]
I believe it's removed because statistics are now viewable in the plugin settings.

**Comment by AlberkaSP** [comment]
Thanks, I hadn't seen it. It’s a shame that command disappeared. I used it in a button for quick access. Now I’ll check directly in the plugin settings.. it’s not too much of a hassle :)
