### ISSUE TITLE
[Bug]: Inline Reversed Flashcards Not Working after 1.13.1 update

### ISSUE THREAD

**Issue by Jack0gh** [st3v3nmw/obsidian-spaced-repetition#1132]
### Describe the bug

Hello, I use the <:> syntax to create inline reversed flashcards, and :> to mark standard inline flashcards. However, since the update, the plugin incorrectly interprets the < as part of the word, and it only displays the card in one direction instead of as a reversed card.

And all of my previously created reversed flashcards have been converted to one-directional cards. Additionally, the scheduling data for the reverse direction have been completely erased.

### To Reproduce

Please refer to the attached screenshots.

### Expected behavior

I expect that my previous scheduling data will be restored, and the inline reversed flashcards will function correctly...

### Screenshots

<img width="1552" alt="SCR-20241016-esbr" src="https://github.com/user-attachments/assets/4ead60db-ebef-44c6-908e-e6adc41f20b2">
<img width="1552" alt="SCR-20241016-esip" src="https://github.com/user-attachments/assets/d64560c1-3607-4d26-a909-8b978fed897a">
<img width="1552" alt="SCR-20241016-errj" src="https://github.com/user-attachments/assets/f604f299-a301-4024-95f5-60b10121111a">

### OS of your device

Sequoia 15.0.1

### Obsidian version

1.6.7

### Plugin version

1.13.1

**Comment by st3v3nmw** [comment]
Hi @Jack0gh. This issue has been fixed in #1143. I'll make a release soon.

**Comment by st3v3nmw** [comment]
@Jack0gh,
Please try the new release (v1.13.2) and let me know.

**Comment by Jack0gh** [comment]
The plugin works well after the update. However, since I had manually restored the scheduling data from a previous file, I can’t tell if the update resolved the issue of the deleted data. Thank you for your comments and for the plugin update!
