### ISSUE TITLE
[Bug]: Questions in multiline flashcard extend beyond the empty line above it

### ISSUE THREAD

**Issue by Struting-Kitty** [st3v3nmw/obsidian-spaced-repetition#1136]
### Describe the bug

Typically, the question in a multiline flashcard would start below an empty line and continues until it reaches the separator for multiline flashcards.
After upgrading to version 1.13.1, the questions in multiline flashcard would not start from the empty line, but rather, the end of previous question.

### To Reproduce

1. Have multiple multiline flashcard in the same note
2. Tag the note with a flashcard tag
3. Review flashcard

### Expected behavior

The question should start from the immediate empty line above it.

### Screenshots

![image](https://github.com/user-attachments/assets/2ccd78c9-a93f-4996-b9f8-56bf804d4dbc)
![image](https://github.com/user-attachments/assets/d9ab3dce-c39a-4592-93ea-c5b7f8e2fccb)
![image](https://github.com/user-attachments/assets/d0e6e916-e5f3-4723-967f-4cebe3c38f1a)
![image](https://github.com/user-attachments/assets/692cb298-908e-45b9-b143-fbcd65d783ad)

### OS of your device

Win 11

### Obsidian version

v1.6.7

### Plugin version

v1.13.1

### Installer version

v1.4.13

**Comment by LeonelRFF** [comment]
I also found this problem, what could be done temporarily is to add those characters before starting the card and at the end. Regarding the latter, something similar was mentioned in #601, which could be a solution, however the [documentation ](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cards-with-blank-lines/)does not seem to indicate that this should be used to delimit the text that is before the question.

**Comment by alberttra** [comment]
i also have this issue, now everything above the question mark of the multiline card. I have roughly a few thousand cards, so applying the workaround above is impossible. Plz fix this issue. Thx

**Comment by Struting-Kitty** [comment]
@alberttra 
You don't have to manually apply the workaround mentioned @LeonelRFF  to every flashcard. You can use regular expression in a software like VS code to batch modify your notes.

Remember to backup your vault before trying in case anything goes wrong.

For the example I have above, try a find pattern of `(^$\n)(.*\n^\?\?$)` and a replace pattern of `$1????\n$2`.
To revert the changes once the issue is fixed, you can use this find pattern `(^$\n)\?\?\?\?\n(.*\n^\?\?$)` and this replace pattern `$1$2`.
You would have to update the pattern to match the separator you use. You can experiment on https://regex101.com first.

**Comment by st3v3nmw** [comment]
Hi all,
This issue has been fixed in #1142. I'll make a release soon.

**Comment by st3v3nmw** [comment]
Please try the new release (v1.13.2) and let me know.

**Comment by zoyart** [comment]
Hi, update v1.13.2 helped, thanks!

**Comment by alberttra** [comment]
It works, thank you very much 🚀
