### ISSUE TITLE
Http(s) images not parsed properly

### ISSUE THREAD

**Issue by Nicolau0** [st3v3nmw/obsidian-spaced-repetition#117]
Hi! 

Clicking on the review flashcards icon or using the command palette "Spaced Repetition: Review Flashcards" doesn't do anything and yields the following error:

![Captura de Pantalla 2021-06-05 a les 11 17 35](https://user-images.githubusercontent.com/85391066/120886718-a3bf2200-c5ef-11eb-918c-6e7390559210.png)

The note reviews work fine. I have version 0.12.3 of obsidian installed.  

Thank you for your very nice work!

**Comment by st3v3nmw** [comment]
Thanks for the bug report, I'll fix this in the next release.

**Comment by Nicolau0** [comment]
Great, thank you!

**Comment by st3v3nmw** [comment]
Quick follow-up,
Which operating system are you on? &
Had the plugin rendered images correctly before?

**Comment by Nicolau0** [comment]
I'm using macOS 10.15.5. I have only one image in one flashcard: 

this yields an error:
Question :: ![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/NumberSetinC.svg/440px-NumberSetinC.svg.png)

this doesn't: 
Question :: ![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMAdScElOnv0U2zAdd9vDpjqiHtNtdH0RqJQ&usqp=CAU)

**Comment by st3v3nmw** [comment]
Aaah, I see. Thanks!
