### ISSUE TITLE
Review Specified Portion of Note 

### ISSUE THREAD

**Issue by Positron010** [st3v3nmw/obsidian-spaced-repetition#12]
Hi,
Thanks for building this amazing plugin! 

I don't know the technical aspect of this suggestion, but IMHO the plugin would be much better, if it allowed to review only certain blocks in a note, tagged with a specific tag for example, rather than reviewing the whole note. That way if one wants to review questions, he wouldn't need to make a note/question, which is cumbersome. The plugin then will be much like **roam/sr** or **Remnote**.

Hope this helps. Thanks!

**Comment by st3v3nmw** [comment]
I've just checked out RemNote, the flashcard review popup looks good. I'll implement that in the next iteration of this plugin.
Though it won't be backwards compatible with the current version.

Thanks for the feedback.

**Comment by Positron010** [comment]
Hello again,
Glad to hear this! Wish you all the best!

**Comment by st3v3nmw** [comment]
Hey,

In retrospect, I don't think I can achieve the same level of functionality & versatility as Anki (+ Pseudonium's Obsidian_to_Anki) within the time constraints that I have.
So, for now, this plugin will remain note-level spaced repetition.
Sorry.

**Comment by Positron010** [comment]
Hi,
No worries my friend! You already did a great job! Wish you all the best!

**Comment by st3v3nmw** [comment]
Reopening this after some thought (+ this seems to be a popular request): #20.

**Comment by st3v3nmw** [comment]
Support for flashcards is now available on the latest release (v1.3.0).
Card types:
1. Single line (`::` separator) i.e. 
```markdown
the question goes on this side::answer goes here!
```
2. Multiline (`?` separator) i.e.
```
As per the definition
of "multiline" the prompt
can be on multiple lines
?
same goes for
the answer
```

**Comment by Positron010** [comment]
Hi,
Amazing work @st3v3nmw !
Thanks a lot! 
All the best.

**Comment by st3v3nmw** [comment]
Glad I could help.
Closing this...
