### ISSUE TITLE
Exclude certain folders when reviewing

### ISSUE THREAD

**Issue by wenlzhang** [st3v3nmw/obsidian-spaced-repetition#13]
Notes in certain folders may be archived, or they may be reference notes. Therefore, it would be great if notes in certain folders can be excluded for reviewing.

This feature may combine well with the following issue:
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/10

**Comment by st3v3nmw** [comment]
Hello,

In the latest release, only notes with a certain tag(s) are considered for reviewing. It's `#review` by default but it can be changed in settings. I think this can help.

**Comment by isle99** [comment]
Can we get a blacklist option too in one of the future updates?

**Comment by st3v3nmw** [comment]
@isle99,
Yes, I'll put that on the roadmap.

**Comment by st3v3nmw** [comment]
@isle99, which version are you currently using?

**Comment by isle99** [comment]
I've just updates it, so 1.2.2 .

**Comment by st3v3nmw** [comment]
Okay, with that version I don't think there's any need to blacklist folders since only notes with certain tag(s) are considered for reviewing.

**Comment by isle99** [comment]
Do you maybe know a plugin which automatically adds a tag to all new notes? This would be a decent fix for me.

**Comment by st3v3nmw** [comment]
Nope, I don't know of any

**Comment by aviskase** [comment]
There is a still need for blacklisting in case of using templates. It's annoying to see files from template directory in the review queue =(

**Comment by st3v3nmw** [comment]
Reopening this...

**Comment by jakeoung** [comment]
Can we also exclude certain folders for flashcards? I would very appreciate that..
