### ISSUE TITLE
[FEAT] Nested decks by folder fix

### ISSUE THREAD

**Issue by Couriuss** [st3v3nmw/obsidian-spaced-repetition#136]
**Is your feature request related to a problem? Please describe.**
In the deck review panel, the plugin does show folders without flashcards if they are not empty. 

**Describe the solution you'd like**
Show folders based on the presence of flashcards inside of them instead of files.

![image](https://user-images.githubusercontent.com/84443032/120936714-91d1a200-c709-11eb-9374-f8751fc32a5a.png)
``

**Comment by st3v3nmw** [comment]
I'll fix this.

**Comment by st3v3nmw** [comment]
The fix should be available soon.
