### ISSUE TITLE
Resize window and Full Screen (distraction free mode) [FEAT]

### ISSUE THREAD

**Issue by DryIce1** [st3v3nmw/obsidian-spaced-repetition#139]
**Is your feature request related to a problem? Please describe.**
flashcards that contain a large image are not shown well in the review window

**Describe the solution you'd like**
- ability to resize the review window - large screen, full-screen, e.g. on YouTube videos 
![image](https://user-images.githubusercontent.com/59501376/120992784-380dbe00-c783-11eb-912a-075863f94228.png)
- additional benefit no distractions with full screen mode

**Additional context**
![image](https://user-images.githubusercontent.com/59501376/120993695-17923380-c784-11eb-9112-5d4d942b47db.png)

Thank you, I really value this plug in!
best,
T

**Comment by st3v3nmw** [comment]
I've introduced the large screen mode. Fix should be available in the next release.

**Comment by DryIce1** [comment]
thank you!

https://Ko-fi.com/home/coffeeshop?txid=7d5ab9dc-f7be-4e65-99e7-ae5a5e85572c&mode=public&img=ogbuymeacoffee

**Comment by st3v3nmw** [comment]
Thanks for your support!
