### ISSUE TITLE
Hotkey to call EASY or HARD

### ISSUE THREAD

**Issue by Quorafind** [st3v3nmw/obsidian-spaced-repetition#14]
WHY

When I wanted to jump to next note or quick react to note, I need to use mouse to select EASY or HARD

**Comment by st3v3nmw** [comment]
Hello,

I've added the necessary commands. You can create custom hotkeys for them in `Settings -> Hotkeys`.

**Comment by Quorafind** [comment]
@st3v3nmw Thanks. Closed
