### ISSUE TITLE
Blank lines in codeblocks

### ISSUE THREAD

**Issue by st3v3nmw** [st3v3nmw/obsidian-spaced-repetition#148]
One other issue I've just noticed: if I have a note like

~~~
How do you create a computed property in Python?
?
```
one line

another line
```
~~~

then it gets changed to

~~~
How do you create a computed property in Python?
?
```
one line
<!--SR:2021-05-20,4,270-->

another line
```
~~~

Perhaps the multiline notes should ignore blank lines if they're in the middle of a code block? This isn't a huge problem as I can add some spaces to the blank line to make the plugin skip that line

_Originally posted by @OliverBalfour in https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/76#issuecomment-841778702_

**Comment by st3v3nmw** [comment]
Kinda related to #122.

**Comment by bjoernwe** [comment]
There's a similar issue when the question is a code block with an empty line:

````
```python
x = True

print(x)
```
?
```python
True
```
````

The flashcard will only show "print(x)" (as regular text - not code).

**Comment by st3v3nmw** [comment]
Fix should be available in the next release once I'm done with testing.

**Comment by OliverBalfour** [comment]
Awesome, thanks for doing this! I've just noticed a subtle bug with this new behaviour though:

1. Set "Save scheduling comment on the same line as the flashcard's last line?" to true
2. Add a card with a multiline code block answer
3. Review the card

What happens is pretty predictable: the comment is added on the same line as the three backticks:

![image](https://user-images.githubusercontent.com/11626018/129278874-392c571f-228f-4ea4-b0f1-f385728cdbfd.png)

However, then the three backticks don't close the code block and everything afterwards including other SRS cards is included, giving some very funky behaviour.

Disabling the same line setting is a good temp fix but I think the same line setting should simply not apply to code blocks

**Comment by st3v3nmw** [comment]
@OliverBalfour, this should be fixed in the next release.
