### ISSUE TITLE
Feature request: third state (good?)

### ISSUE THREAD

**Issue by aviskase** [st3v3nmw/obsidian-spaced-repetition#15]
Andy Matuschak uses [spaced repetition system for working on writing inbox ](https://notes.andymatuschak.org/z7iCjRziX6V6unNWL81yc2dJicpRw2Cpp9MfQ).

In short, there are four possible actions:

- skip note (increase interval for `x`)
- work on it, mark as fruitful work (decrease interval)
- work on it, mark as unfruitful work (increase interval for `y`)
- convert to evergreen note (stop using in space-repetition prompts)

(where `x < y`)

As you can see, your plugin can be used for such practice, where:
- fruitful == mark as `hard`
- skip or unfruitful == mark as `easy`
- convert to evergreen == remove `#review` tag

But it would be nice, if the plugin had a third state between easy and hard, so that it would be possible to distinguish between skipped and unfruitful states. Anki algorithm supports four states: again, hard, good, easy. If the plugin adds `good` state, this will cover all use cases, thus:

- fruitful == `hard`
- skip == `good`
- unfruitful == `easy`

**Comment by st3v3nmw** [comment]
Okay, I'll add the `good` state in the next release

**Comment by st3v3nmw** [comment]
This should be fixed in the latest release (v 1.2.3).

**Comment by aviskase** [comment]
Cool, tested on the latest version, fits perfectly!
