### ISSUE TITLE
[FEAT] Review flashcards in note

### ISSUE THREAD

**Issue by Couriuss** [st3v3nmw/obsidian-spaced-repetition#151]
**Is your feature request related to a problem? Please describe.**
It would be a nice feature to have the ability to review flashcards in notes.
A potential use scenario may be; after writing about a particular topic, object of study, you may want to review the note as a form of understunding, I beliave that a good way is to fraction the study material in flashcards and reviewing them.

**Describe the solution you'd like**
1. Ability to review cards into notes.

A problem about which cards to show in the review may arise from the fact that some cards may alredy be studied.
A potential solution:
- Show only cards with no [Spaced data], new cards basically. (sorry I don't know any programming term.) 
- Only attribute [Spaced data] if all cards have got a rating of Good or better.

So for example. In the case you already have a note about a topic, with some alredy studied flashcards in it, and it happens that you have to go more in depth about that particular topic, you will only review the cards that are new, and attribute [Spaced data] in the case you reviewed all the cards "Good", so you can conclude that you understood the material.

**Additional context**
I do believe that it's a good feature to have to better differentiate between your plugin and third party softwares. In this case you will provide the community with a different value proposition; you provide a feature that sinergize with the obsidian note taking experience. 
This factor may increase interest in the community, by differentiating from alredy existing plugins, and, thus, increasing the amount of people reached by the value this plugin offers.

**Comment by wyatt** [comment]
+1

**Comment by st3v3nmw** [comment]
Fix should be available in the next release.
