### ISSUE TITLE
[FEAT] Resize image to fit flashcards review UI

### ISSUE THREAD

**Issue by CavalloneChen** [st3v3nmw/obsidian-spaced-repetition#159]
If I add an image into the flash card, it won't fit well into the UI window. I have to constantly do horizontal scrolling to view its content properly.
For example, in the following screenshot, the horizontal scroll bar indicates that the embedded image is too large.
![image|400](https://user-images.githubusercontent.com/28266566/121827805-11ee9d80-ccf0-11eb-95f8-74e585eed6f0.png)

**Comment by st3v3nmw** [comment]
A question: do you specify the size of the image directly i.e. `![[image.png|100x100]]`?

Related to #139.

**Comment by CavalloneChen** [comment]
> A question: do you specify the size of the image directly i.e. `![[image.png|100x100]]`?
> 
> Related to #139.

Yes I did. `![[Pasted_image.png|300]]` in my case.

**Comment by st3v3nmw** [comment]
> Yes I did. `![[Pasted_image.png|300]]` in my case.

Nice, I'll fix this soon.
https://github.com/mgmeyers/obsidian-kanban/blob/main/src/components/MarkdownRenderer.tsx

**Comment by st3v3nmw** [comment]
Images are now being resized based on the `![[Pasted_image.png|300]]` format. If no size is specified, the images are resized to fit the flashcard modal view.
Fix should be available in the next release.

**Comment by Nitero** [comment]
Is there a way to turn this back off again? It sucks having to scroll if the card does not only consist of an image.
