### ISSUE TITLE
Stats like that of Anki

### ISSUE THREAD

**Issue by KALKI-the-avataar** [st3v3nmw/obsidian-spaced-repetition#16]

**Comment by st3v3nmw** [comment]
Hello,
Currently, the plugin does not track the past responses, so we can have the following stats:
1. Future due (the number of reviews due in the future - count per day)
2. Review intervals
3. Card ease

Adding the tracking, we can have:
1. Past review counts (& possibly a heatmap)
2. Response types

I hope these cover everything you want

**Comment by st3v3nmw** [comment]
Stats might be useful to help one tweak the algorithm options.
