### ISSUE TITLE
[BUG] No message or error when image does not exist

### ISSUE THREAD

**Issue by rubbish** [st3v3nmw/obsidian-spaced-repetition#161]
**Describe the bug**
I recently had a flashcard in which the image didn't exist. However, there wasn't any alert or anything other than this in the console.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/1580/121938064-fba50980-cd10-11eb-8cd0-aae6b074ebd6.png">

**To Reproduce**
1. Create a note with this:
```markdown
![[does-not-exist.jpg]]
?
maybe should error
```
2. Click "Review flashcards"
3. No alert or message other than in the console.

**Expected behavior**
Either it just shows the broken link in the flashcard (my preference) or it alerts that a flashcard could not be rendered.

**Versions (please complete the following information):**
 - OS: Mac Big Sur
 - Obsidian version: v0.12.4
 - Plugin version: v1.5.6

**Comment by st3v3nmw** [comment]
Thanks for the bug report!

**Comment by st3v3nmw** [comment]
Fixed, should display the broken link now.
Should be available in the next release.
