### ISSUE TITLE
Duplicated cards in decks [FEAT]

### ISSUE THREAD

**Issue by The-Eighth-Man** [st3v3nmw/obsidian-spaced-repetition#164]
Let's say I have a file with #tag1 and #tag2. Previously, only the first tag was recognized as a deck. In the current version, this file would go to both decks and these get stacked very quickly. 

The main problem is an issue with duplicates and how overwhelming is to the eye seeing the number of cards left for reviewing when in fact they are the same, but in different decks.

My solution is an option, like a toggle, for allowing to count all the tags and put them in each deck (some people may like this way) or selecting just the first tag as the deck.

**Comment by st3v3nmw** [comment]
I'd made a change that caused the bug. It's now back to selecting only the first tag.
Fix should be available in the next release.
Thank for the bug report!
