### ISSUE TITLE
tag can not be set in setting

### ISSUE THREAD

**Issue by vipassanak** [st3v3nmw/obsidian-spaced-repetition#17]
updated to 1.2.2 

I set #review in setting and when I reopen the setting the tag disappears. I have tried several times.

Then when I do the review,it alerted " Please tag the note appropriately for reviewing."

**Comment by st3v3nmw** [comment]
Hello,

Is there an error on the console? (CTRL + SHIFT + I)

**Comment by st3v3nmw** [comment]
My guess is that this is occuring since the tag setting was not available in previous versions. Try uninstalling and reinstalling the plugin.

**Comment by vipassanak** [comment]
I deleted the plugin folder and reinstalled the plugin.Now it seems ok

**Comment by st3v3nmw** [comment]
Now that its fixed, I'll close this issue
