### ISSUE TITLE
[FEAT] Ignore flashcards in `<!-- HTML -->` comment blocks

### ISSUE THREAD

**Issue by OliverBalfour** [st3v3nmw/obsidian-spaced-repetition#173]
**Is your feature request related to a problem? Please describe.**
Sometimes I'd like to ignore a flashcard temporarily without deleting it for good or moving it to another file without the flashcard tag. For example, if there are two similar sounding vocabulary flashcards and you'd like to bury one to avoid confusion.

**Describe the solution you'd like**
One solution would be to ignore flashcards inside Obsidian's `%%multiline comments%%`. Another alternative might be something like Anki's bury/suspend feature (although perhaps if this were added, it would just comment out the card.) I think the comment idea is pretty simple and intuitive though.

**Comment by Couriuss** [comment]
Problem is that I write all my flashcards in comments `%%`  so I don't them in preview mode.

**Comment by OliverBalfour** [comment]
That's fair, maybe %% isn't the best solution for burying cards then. I can't think of any other nice methods for burying cards, so I might close this ticket for now

**Comment by OliverBalfour** [comment]
On second thoughts, perhaps adding HTML style comments could be a good solution?
I've just noticed a bug where adding remnote style tasks in comments like `<!-- Question::Answer -->` displays a blank question, so it can't interfere with any other workflows people have.
It would be nice if HTML comments were a documented way to temporarily disable flashcards of any type, any thoughts?

**Comment by st3v3nmw** [comment]
Hey @OliverBalfour, sounds good. Should be a quick fix.

**Comment by st3v3nmw** [comment]
Fix should be available in the next release once I'm done with testing.
