### ISSUE TITLE
[BUG] Only making deck of first tag in yaml

### ISSUE THREAD

**Issue by MatthewJMullins** [st3v3nmw/obsidian-spaced-repetition#178]
**Describe the bug**
Plugin seems to only be reading the first tag in yaml. 

**To Reproduce**
1. Put "flashcards/finance" and "flashcards/terms" into yaml of three notes
2. Run the plugin

**Expected behavior**
There should be one main deck "flashcards" with two sub-decks "finance" and "terms". Currently it is only outputting deck "Flashcards" and sub deck "Finance", leaving off sub deck "Terms".

**Versions (please complete the following information):**
 - OS: MacOS
 - Obsidian version: 12.5
 - Plugin version: 1.5.7

**Comment by st3v3nmw** [comment]
We've had a back and forth about this i.e. in #164. I'll provide an option which defaults to the current behavior and can be configured to fit yours.

**Comment by MatthewJMullins** [comment]
Thanks for the response. I think if you just default it to how Anki works many users would find this familiar. Of course your call!

**Comment by ronzulu** [comment]
Hi @MatthewJMullins 

Beta release is now available. Please see https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/834 for details

And latest code, version `B` available at https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/834#issuecomment-1915996120

Any feedback appreciated.

Ronny

**Comment by 4Source** [comment]
@ronzulu If I see this correct this Issue is closed?

**Comment by ronzulu** [comment]
Thanks @4Source I'll close this now.
