### ISSUE TITLE
[BUG] Statistics view displays overdue cards on the right of the chart with days=-1

### ISSUE THREAD

**Issue by OliverBalfour** [st3v3nmw/obsidian-spaced-repetition#186]
**To Reproduce**
Note: as it takes a day to do this I haven't reproduced this multiple times
1. Create some flashcards and do them daily
2. Forget to do them one day
3. Open the statistics view the next day without touching anything else
4. See the attached screenshot

**Expected behavior**
I would have expected the plugin to reschedule overdue cards to today (eg the chart could just iterate through negative days and add them to today's notes). I also would have expected the overdue notes to appear on the left if they were to appear, the X axis is very nonlinear.

**Screenshots**
![image](https://user-images.githubusercontent.com/11626018/124335805-e9ffa500-dbde-11eb-990d-f2ab2cf48bdb.png)
There are no logs in the JS console.

**Versions (please complete the following information):**
 - OS: Manjaro Linux
 - Obsidian version: v0.12.9
 - Plugin version: 1.5.7
 - Installer version: `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36`

**Comment by st3v3nmw** [comment]
Fix should be available in the next release.
