### ISSUE TITLE
[FEAT] Alternating flash card sides presented

### ISSUE THREAD

**Issue by Ace19444** [st3v3nmw/obsidian-spaced-repetition#189]
I am using this app with Spanish flash cards and would like the ability to randomly see either side of the cards and have to guess what's on the other. Another useful alternative would be for correct guesses to automatically alternate to the other side of the card the next time it comes up (but only for correct guesses).

Thanks! Digging the app so far.

**Comment by st3v3nmw** [comment]
Reversed cards (#49, #58) could be used for this use case, I think.

**Comment by st3v3nmw** [comment]
Reversed cards were implemented a while back, you could 'em a whirl and see if they fulfill this particular usecase.

**Comment by SimonEggert** [comment]
Thanks for this great plugin and the reversed cards feature!

I am also trying to add two-way flash cards without having to duplicate the questions/answers and would like to know if this is a use case for reversed cards. Is a reversed card adding the "normal" direction as well, e.g. would `A:::B` produce `A::B` and `B::A`? Or would I need to duplicate the card myself, like `A::B` and `A:::B` (with the `:::`-notation helping in making the process easier and quicker)?

**Comment by st3v3nmw** [comment]
Hello @SimonEggert,
`A:::B` will produce both `A::B` and `B::A`, so you won't have to do any duplication on your end.

**Comment by st3v3nmw** [comment]
> Reversed cards were implemented a while back

Closing...

**Comment by SimonEggert** [comment]
Great, thanks for the clarification! Guess I need to double-check my config :wink:
