### ISSUE TITLE
[BUG] Cannot be enabled in mobile app

### ISSUE THREAD

**Issue by Tony-zf1** [st3v3nmw/obsidian-spaced-repetition#190]
Obsidian mobile app is available now. But it seems that Spaced-Repetition plugin can't be enabled in it(v.1.0.2).

Hope this problem can be fixed.

Thank you very much!

**Comment by Tony-zf1** [comment]
By the way, my phone is Huawei P30 powered by Android 10.

**Comment by zhixiangCai** [comment]
It works well in iPhone with iOS14

**Comment by Tony-zf1** [comment]
> It works well in iPhone with iOS14

Yes, it does. And it can also be used in some Android systems. 

Unfortunately, it doesn't work in my Huawei Phone with Android 10. I know a few users have the same problem but we don't know how to fix it.

**Comment by st3v3nmw** [comment]
Hey @Tony-zf1, is your Chrome version updated to the latest version? I had a problem with mine and updating Chrome fixed it (since Obsidian relies on the underlying Chrome).
Let me know if that helps, otherwise I'll dig deeper.

**Comment by Tony-zf1** [comment]
@st3v3nmw 
Thanks for your reply! And using this debugging method, I get the error code as below:
```
 Plugin failure: obsidian-spaced-repetition SyntaxError: Unexpected token '='
    at eval (<anonymous>)
    at app.js:1
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1 
```
So far, this plugin just can't be enabled in Huawei devices including my phone and pad and my friends' Huawei phone.  I think there might be some confliction caused by Huawei's system settings.

**Comment by st3v3nmw** [comment]
@Tony-zf1,
My, I forgot to mention, run `navigator.appVersion` in that debugging console. If the Chrome version is less than 85, it won't support the plugin since it's using the `??=` operator somewhere. You could post the same here as well.
Looking at your error log, it looks like something that was reported [here](https://forum.obsidian.md/t/plugin-for-flashcards-note-level-spaced-repetition-all-inside-obsidian/16498/36). I also experienced the same after I restored the factory version of Chrome on my Android. Updating Chrome fixed both issues.

**Comment by Tony-zf1** [comment]
@st3v3nmw 
Thank you so much! It's good now!
My chrome app version is 91, but the webview version is 84. After I installed the `Android System WebView_v91` from google play, the plugin works well! 
Thanks again for your wonderful plugin and helpful reply!

**Comment by Tony-zf1** [comment]
Actually, `Android System WebView_v91` can work properly on my phone, but can't run on my pad. The reason is that the phone uses `google webview` along with the pad using `huawei webview v83`. Unfortunately, the `huawei webview` updates very very slowly, so it may take a long time for me to enjoy this plugin on my pad. What a pity! 
Anyway, thank you again!
