### ISSUE TITLE
[FEAT] Card context-automatic based on parent-child relationship under Outliner mode

### ISSUE THREAD

**Issue by zhixiangCai** [st3v3nmw/obsidian-spaced-repetition#194]
### Discussed in https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/193

<div type='discussions-op-text'>

<sup>Originally posted by **zhixiangCai** July 15, 2021</sup>
Many obsidian users prefer using Outliner mode by [Oultiner plugin](https://github.com/vslinko/obsidian-outliner) to write notes like RoamResearch and RemNote. 

If the flash cards can automatic have the parent items context of the answers will highly improve the efficiency of flascards making and memory, because the parent items can directly and easily provide recall clues.

The flashcard is like the following:

-----
The flashcard in edit mode:

- a
- b
  - c
    - d
      - Question:: Answer

The flashcard in preview mode:

- b (note: no "a" above)
  - c
    - d
      - Question:: 
----

Answer

</div>

**Comment by st3v3nmw** [comment]
Gee, there's three copies?
Closing dup...
