### ISSUE TITLE
[FEAT] Multiple review queues

### ISSUE THREAD

**Issue by erichalldev** [st3v3nmw/obsidian-spaced-repetition#203]
Thank you so much for this plugin! I mainly use the note reviewing functionality. It would be great if separate queues could be maintained, kind of like having separate decks. For example one for "#workideas" and "#personalideas". That way I could review them separately.

**Comment by dummifiedme** [comment]
+1
A choice on reviews by tags would be amazing. It could act like decks for review :D

**Comment by erichalldev** [comment]
I've made a first pass at implementing this. There's a little more to do, but the bones are there, I think. https://github.com/erichalldev/obsidian-spaced-repetition/commit/069619c56b40879ef3d80e2e2bf855a7a34aef9f

**Comment by st3v3nmw** [comment]
Hey @erichalldev, looks good so far!

**Comment by erichalldev** [comment]
Thanks @st3v3nmw. It doesn't look like I'll have a lot of time to work on it in the next month or two, unfortunately.

**Comment by st3v3nmw** [comment]
@erichalldev, if you have a minute or two, you could open a PR to the `multiple-note-review-queues` branch that I've created so that I can pick up from where you've left. Thanks.

**Comment by erichalldev** [comment]
Thanks for creating that branch for me, @st3v3nmw! I just created PR #234. I wish I could spend more time on this because it's been such a game-changer for my workflow and I want to give back as much as I can.

**Comment by dummifiedme** [comment]
@erichalldev, @st3v3nmw 
Does it work now? and how to enable it?

**Comment by st3v3nmw** [comment]
@dummifiedme, not yet. Should be available in the next release once I finish up.

**Comment by st3v3nmw** [comment]
Released!

**Comment by erichalldev** [comment]
This is great! Thank you so much.
