### ISSUE TITLE
[FEAT] Remove folder expansion icon for decks without child decks

### ISSUE THREAD

**Issue by OliverBalfour** [st3v3nmw/obsidian-spaced-repetition#218]
**Is your feature request related to a problem? Please describe.**
In the tree view of nested decks, decks which don't have child decks still have a triangle icon next to them that expands to show nothing.

In the below image only one of the subdecks has children:
![image](https://user-images.githubusercontent.com/11626018/127854217-b2afd206-4ac2-4042-8c0e-6e2d98bc119b.png)

**Describe the solution you'd like**
It would be nice if the icons only appeared if there were children, that way it's easier to scan the list for deeply nested decks

**Comment by st3v3nmw** [comment]
Fix should be available in the next release.
