### ISSUE TITLE
Notes assigned for today lost if not marked easy/good/hard [BUG]

### ISSUE THREAD

**Issue by yeruvan** [st3v3nmw/obsidian-spaced-repetition#221]
**Describe the bug**
If a note is due on a given day, and I don’t mark it as easy/good/hard, the note doesn’t get pushed to the next day, nor does it show up in the “New” category on the sidebar. Its due date remains the date in the past. Effectively, my note has disappeared from my writing calendar.

Of course, the workaround is to make sure I mark all notes at the end of the day, but inevitably there will be days when this isn’t possible. So is there a way to automatically push missed notes to the next day?

**To Reproduce**
1. Make new note.
2. Tag with assigned note tag.
3. Mark as easy/good/hard and set due date to today.
4. Wait till the next day: the note will be nowhere in the review queue.

**Expected behavior**
I expected there to be a section in the review queue for "Yesterday" or "Missed Cards" or for yesterday's date; or else for the new card to be pushed to today.

**Versions (please complete the following information):**
 - OS: Windows 10 + Android
 - Obsidian version: v0.12.10
 - Plugin version: 1.5.7
 - If on desktop, Installer version: [run `this.navigator.appVersion` on the developer console, e.g. `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"`]

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by ronzulu** [comment]
Hi @yeruvan 

This probably was fixed a long time ago.

On 26 January 2024, I see the following with "yesterday" and other dates in the past.
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/199b34cb-0e42-458f-882f-7fb25cce7ccf)

Does this address your issue?

Cheers
Ronny

**Comment by 4Source** [comment]
@st3v3nmw  / @ronzulu think this could be closed
