### ISSUE TITLE
[BUG] I cant the change the Base ease value

### ISSUE THREAD

**Issue by drstrangez0** [st3v3nmw/obsidian-spaced-repetition#224]
**Describe the bug**
 Cant change the Base ease value, if changed it goes to the default value (250)

**To Reproduce**
1. Go to plugin setting 
2. Then base ease
3. Set the value to 130
4. After closing the value will return to 250 

**Expected behavior**
The base ease will be set to 130

**Comment by st3v3nmw** [comment]
Fix will be available in the next release. Thanks for the bug report!
