### ISSUE TITLE
[BUG] display on mobile broken

### ISSUE THREAD

**Issue by mkschulze** [st3v3nmw/obsidian-spaced-repetition#231]
**Describe the bug
Looks like with the latest Mobile update, the canvas broke. 

**To Reproduce**
Install latest mobile version for iOS, open the app and start the review from the sidebar icon.
**Expected behavior**
The main plugin container should adapt responsive.

**Screenshots**

![image](https://user-images.githubusercontent.com/3390820/128646888-2998edad-31b4-4285-a43c-4ae8b2b73f34.png)

**Versions (please complete the following information):**
 - OS: iOS
 - Obsidian version: [1.0.4]
 - Plugin version: [1.6.0]

**Comment by st3v3nmw** [comment]
That shouldn't happen by default, but you can change the size of the flashcard modal in settings.

**Comment by mkschulze** [comment]
Ah ok, yes that works well. Thx
