### ISSUE TITLE
[BUG] empty deck

### ISSUE THREAD

**Issue by Wikunia** [st3v3nmw/obsidian-spaced-repetition#235]
**Describe the bug**
I have a note with a #review tag but it doesn't show up in the review flashcards deck. Same is true for #flashcard tagged notes

**To Reproduce**
1. Open a note 
2. Add tag `review`
3. Open review flashcards
4. All deck numbers are 0

**Expected behavior**
Show a deck in the root folder with one new card

**Screenshots**
![Screenshot from 2021-08-09 16-15-52](https://user-images.githubusercontent.com/4931746/128721087-db44e607-6082-4c9f-b280-0f5525308fe6.png)

**Versions (please complete the following information):**
 - OS: Linux 
 - Obsidian version: v0.12.12
 - Plugin version: v1.6.0
 - If on desktop, Installer version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.10 Chrome/89.0.4389.128 Electron/12.0.14 Safari/537.36

**Comment by st3v3nmw** [comment]
Could you please confirm if you have that `#review` tag added in settings for the flashcard tags bit?
What's the status of the `Convert folders to decks & subdecks` option?
You could also post the text for the offending flashcard.

**Comment by Wikunia** [comment]
The two relevant screenshot:
![Screenshot from 2021-08-09 21-13-04](https://user-images.githubusercontent.com/4931746/128761333-592e7172-e2b5-4cef-a571-33e7bee7cf51.png)
![Screenshot from 2021-08-09 21-13-20](https://user-images.githubusercontent.com/4931746/128761337-d0fc5f80-d619-4b5a-885f-406dfddc26b0.png)

The card/note:
```
This is a test note
#review 
```

**Comment by st3v3nmw** [comment]
So, for the notes, the review is done in the normal Obsidian UI & then use the menu on the top right to select a review response based on how you find the material. Documented [here](https://github.com/st3v3nmw/obsidian-spaced-repetition/wiki/Notes).

For flashcards (those that appear in that flashcards modal), use something like:
```markdown
#flashcards

Question::Answer
``` 
Or any of the other flashcard types as documented [here](https://github.com/st3v3nmw/obsidian-spaced-repetition/wiki/Flashcard-Types) & [here](https://github.com/st3v3nmw/obsidian-spaced-repetition/wiki/Reviewing-flashcards).

I hope that helps.

**Comment by Wikunia** [comment]
Oh I see thanks I somehow didn't read the "right" pane and missed it as it's normally closed in my setup.

**Comment by st3v3nmw** [comment]
No worries!
