### ISSUE TITLE
[FEAT] Use bold text as cloze test along highlighted one

### ISSUE THREAD

**Issue by bhickta** [st3v3nmw/obsidian-spaced-repetition#238]
## Feature
* Use ** or Bold text for **cloze**  card
## Why
* In most of the websites, bold texts can be directly copied to the notes, and most of the time those bold texts are the important facts/figures to remember
## Solution
* add a toggle in the plugin setting, where bold and highlight as cloze text could be togggled
* add a toggle
  * use both ** bold** and ==Highlight==

**Comment by st3v3nmw** [comment]
Fix should be available in the next release.
