### ISSUE TITLE
Wrong version number cause installation error

### ISSUE THREAD

**Issue by Quorafind** [st3v3nmw/obsidian-spaced-repetition#24]
![image](https://user-images.githubusercontent.com/13215013/115169786-99a19c80-a0f1-11eb-9f84-ebfdd6b446c0.png)

This should be 1.2.4?

**Comment by st3v3nmw** [comment]
Hello,
Sorry for that. I forgot to revert a version change after deleting a release I'd made. This should be fixed now.
If it isn't, Obsidian still has the old data cached. It should clear after a while. Alternatively, you can reboot to have it cleared faster.

**Comment by st3v3nmw** [comment]
Also, I've released v1.3.0.
