### ISSUE TITLE
[BUG] Not detecting all the cards.

### ISSUE THREAD

**Issue by dummifiedme** [st3v3nmw/obsidian-spaced-repetition#246]
**Describe the bug**
I have around 960 cards denoted by #flashcard itself. (Muktiline cards), but the plugins picks only a few. Including all my close cards too, the total number of cards amounts to 200. I am pretty much sure cards aren’t getting added to deck even when manually checking many cards for tag deck and the separator.

**To Reproduce**
1. Change separator to #flashcard
2. Change deck to #note
3. Go to review queue.

**Expected behavior**
It should clearly have more than 1200 cards. But it shows only 200 odd cards.

**Comment by dummifiedme** [comment]
I found an anomaly. If I manually edit a note containing a card, it gets added. Doesn’t matter if I only add a space somewhere or something.it just needs to be modified and the card magically appears. I have tried reloading the app multiple times, also tried to close and open the app many times. The number of cards remain same. 

Is there a criteria for this plugin to add only the cards which are recently modified?

p,ease fix this. I migrated from Anki to this plugin, and it breaks my workflow. 💔

**Comment by st3v3nmw** [comment]
I think I know what the issue is, I'll do a fix in a few.

**Comment by dummifiedme** [comment]
@st3v3nmw please, thanks!

**Comment by st3v3nmw** [comment]
What happens when you uninstall then reinstall the plugin?

**Comment by dummifiedme** [comment]
Haven’t tried that yet, will do.
Also, I have different .obsidian folders for mobile and desktop. Will it cause any issue? Or the queuing is purely based on the ID tags?

**Comment by st3v3nmw** [comment]
The different  .obsidian folders shouldn't be a problem. I implemented caching in the latest version to reduce trips to disk & I think this might be the issue.
Which OS are you on?

**Comment by dummifiedme** [comment]
I am currently on iPad. Though I use on laptop too. I migrated today itself, so mostly on iPad for now.

@reinstalling, it now has 700 cards. Still short.

**Comment by st3v3nmw** [comment]
Does this problem exist on your laptop as well?

**Comment by dummifiedme** [comment]
> Does this problem exist on your laptop as well?

I can only check after 10-12 hrs. Will check and get back.

**Comment by dummifiedme** [comment]
> 
> 
> Does this problem exist on your laptop as well?

So I checked it. It had the same "problem". 
I realised, the problem was with the notes itself. Not with the plugin. I am really sorry about it. The tag I made as deck was missing on many files. That is the reason maybe that it wasn't showing up. Also, my files has `#flashcard ` many times (when you type in `#` it suggests a tag and if you press enter, it automatically adds a space at the end), so a fraction of cards weren't displaying because of this spaced tag.

I regexed them all, and now it seems to recognize them all.


I do have a small query as well, is there a way I can make it a priority to have a card which is in multiple deck to show in a particular deck first? e.g I have two tags one is to indicate the 'level' of notes and other for the 'category'. Currently not all the notes have the category, but most have. But when I make decks selecting both the level and category tags, all the cards are shown inside the level deck. 

I am guessing it is because the level tag is before the category tag in my files. So, is there a way I can prioritize them to go into category deck first and then into the level deck? My suggestion would be to assign the priority based on how they are listed in the settings of the plugin. 


I am sorry again for all the trouble! Looking forward to use it from now on, instead of the ANKI :)
Good work :)

**Comment by st3v3nmw** [comment]
> I am sorry again for all the trouble! Looking forward to use it from now on, instead of the ANKI :)

No worries!

> I am guessing it is because the level tag is before the category tag in my files. So, is there a way I can prioritize them to go into category deck first and then into the level deck? My suggestion would be to assign the priority based on how they are listed in the settings of the plugin. (Should I raise an enhancement issue?)

Oh yes, please do raise an issue.

**Comment by richardrl** [comment]
Hey @st3v3nmw I'm afraid I also have this issue. I have 259 cards using the search bar, yet the plugin only shows 185 cards.
