### ISSUE TITLE
[FEAT] Prioritzing the deck for the cards having multiple possible deck.

### ISSUE THREAD

**Issue by dummifiedme** [st3v3nmw/obsidian-spaced-repetition#247]
**Is your feature request related to a problem? Please describe.**
If we have multiple tags in a note for various indicators like "maturity level", "category" etc, and we decide to review the flashcards in them by converting those tags as deck, the cards are shown in the deck for which the tag is defined first in the file. eg. if my tags line is `tag: level/seed category/A`, then the cards from this deck would show only in the deck `level/seed`.

**Describe the solution you'd like**
Ability to prioritize the decks in case of multiple tags as decks. 
As per my suggestion, the priority should be based on how they are listed in the deck field of the settings dor plugin. If for the above case, I have listed like this in the deck field: `#category level`, then the cards from the note above, should be in the deck `category/A`. The cards will go into `level` deck only when the `category` is missing.

**Comment by st3v3nmw** [comment]
I fixed this, please confirm if it works correctly.
