### ISSUE TITLE
[BUG] Not updating

### ISSUE THREAD

**Issue by gfidias** [st3v3nmw/obsidian-spaced-repetition#262]
![spaced_repetition](https://user-images.githubusercontent.com/23036873/130316272-07dd4369-650d-4078-99f6-5d83ee649ffa.jpg)
When updating from v.1.6.0, obsidian reports: "update successful" but the plugin version remains 1.6.0, not 1.6.1.

**Versions (please complete the following information):**
 - OS: macOS 11.5.2
 - Obsidian version: v0.12.12
 - Plugin version: v1.6.0
 - Installer version: "5.0 (Macintosh; Intel Mac OS X 11_5_2) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.12 Chrome/89.0.4389.128 Electron/12.0.14 Safari/537.36"

**Comment by st3v3nmw** [comment]
i forgot to update the manifest file.
I've updated the release files, please check if its fixed now.

**Comment by gfidias** [comment]
Fixed. Thx.
