### ISSUE TITLE
[FEAT]: Review flashcard of any specific notes with command palette like interface

### ISSUE THREAD

**Issue by bhickta** [st3v3nmw/obsidian-spaced-repetition#270]
### Problem
* Currently in big note repository, it becomes tedious to review flashcards in a specific notes via Spaced repetition plugin, as one has to navigate that note/topic via clickable interface
### Solution
* Option - Review the current note's flashcard
* Providing command palette like interface to directly review flashcards of any specific note/specific tag/specific folder

**Comment by st3v3nmw** [comment]
Cool, should be a quick fix. Linking to #151...

**Comment by st3v3nmw** [comment]
Fix should be available in the next release.
