### ISSUE TITLE
[FEAT] Specify notes to review by folder path, instead of tags

### ISSUE THREAD

**Issue by dsteinbock** [st3v3nmw/obsidian-spaced-repetition#272]
Problem:

Like [some Obsidian users](https://forum.obsidian.md/t/increasingly-atomic-folders-a-workflow/14345), I primarily use folders to organize my notes, not tags. I would love to use Spaced Repetition on a folder basis.

Solution:

- I have an Inbox folder. 
- Under Spaced Repetition settings -> Notes, I enter the path to my Inbox folder. (I could enter more paths if I wanted, to have multiple queues.)
- All notes in my Inbox folder are included in my review queue.
- If I move a note out of the Inbox folder, it will no longer be included in the review queue.

**Comment by Hxppdv** [comment]
This is very helpful, especially when I have so many notes that tagging all of them is difficult.

**Comment by ceciliamay** [comment]
+1 to this feature request!!

**Comment by meskill** [comment]
Any chance this could be implemented?

**Comment by zhengbuqian** [comment]
Plus one to this!

**Comment by dsteinbock** [comment]
[Looks like this has been implemented](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#using-folder-structure).

**Comment by gerardo** [comment]
@dsteinbock the feature was implemented for flashcards, not for notes. This should be re-opened, unless I'm missing something.

**Comment by gerardo** [comment]
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/648
