### ISSUE TITLE
[FEAT] Customize labels for easy/good/hard

### ISSUE THREAD

**Issue by dsteinbock** [st3v3nmw/obsidian-spaced-repetition#273]
**Problem**
I'm using Spaced Repetition for [incremental note writing](https://github.com/st3v3nmw/obsidian-spaced-repetition/wiki/Incremental-writing), not flashcard learning. Anki's learning-specific terms — "easy/good/hard" — don't correspond at all to the incremental writing use case. There's frustrating cognitive friction in having to mentally translate the commands every time I do a review into terms relevant for writing. 

**Solution**

- Add a setting for customizing the 3 command labels. 
- As an incremental writer I might use: skip or snooze (for 'good'), fruitful or upvote (hard), unfruitful or downvote (easy)
- This feature would benefit everybody by allowing even flashcard learners to specify their own preferred terms.

My workaround is to make my hotkeys correspond to my own mental labels, but it would greatly help if the UI corresponded to and reinforced my mental labels.

**Comment by eleanorkonik** [comment]
Same here to say this exact thing :)

**Comment by benhughes** [comment]
Would love this feature too.

As a workaround until this feature is implemented I open up this file: `.obsidian/plugins/obsidian-spaced-repetition/main.js` 

and replace the following lines:
<img width="253" alt="Screenshot 2021-09-11 at 21 50 56" src="https://user-images.githubusercontent.com/1478194/132961301-d876dfbc-f7ca-4e2d-8871-0fedf303d37e.png">
with 
<img width="320" alt="Screenshot 2021-09-11 at 21 50 37" src="https://user-images.githubusercontent.com/1478194/132961305-48668a45-9f28-4adb-861a-b606ac60eddf.png">

This helps me alot, the biggest caveat is you have to do it on every update but not a huge issue.

**Comment by AB1908** [comment]
This is actually relatively easy to implement. I'll see if I can work on it. Do you want these to be exposed as plugin settings?

**Comment by dsteinbock** [comment]
Yes please. That would be super helpful.

**Comment by AB1908** [comment]
Think I have it down.

![image](https://user-images.githubusercontent.com/14124383/179352798-49d66070-383b-4dd2-b02b-14babe0554ba.png)

**Comment by AB1908** [comment]
I feel like I want to clean up the labels a bit if possible. 1 day vs 2 days should be easy as well.
