### ISSUE TITLE
[FEAT] Review Flashcards any time

### ISSUE THREAD

**Issue by st3v3nmw** [st3v3nmw/obsidian-spaced-repetition#279]
**Is your feature request related to a problem? Please describe.**

Suggested by safrilth [here](https://forum.obsidian.md/t/plugin-for-flashcards-note-level-spaced-repetition-all-inside-obsidian/16498/69?u=st3v3n).

> Usually i use this plugin to review my flashcard. When exam day is still far away, its very useful to review flashcard using spaced repetition. Easy flash card rarely show up, so do the opposite.
> But when exam day is close, we need to review all card regardless its easy or hard. Its like using regular flashcard, without spaced repetition. My current work arround is to delete stamp, that created in the card after we reviewing flashcard as easy/medium/hard, but its pain in the ass.

**Describe the solution you'd like**

> i’m not programmer, but i wonder… is there a way to ignore that time stamp. It would be great if there is a button somewhere or a toggle in settings.

**Comment by cbonfante** [comment]
Love the app. Thank you soo much. Totally agree. An ability to WIPE the stamps clean would be magic. Tried replace but doesn't work.

**Comment by sebastian-muthwill** [comment]
Maybe whipping the timestamps is not necessary. 
Currently when you start a repetition for a deck in the decks overview it will show you only those flashcards that are due.
Would it be possible to add a button (or context menu or so) to the decks overview where you select "review all". This will put all cards from this deck to the que regardless of the due date.

**Comment by navakelvin** [comment]
Very necessary:
1. Review without timeline in isolation. As OP suggests.
2. Allow to change button interval time, especially hard. It is painful to wait a whole day even if you have indicated that you have forgotten.

**Comment by steppinio** [comment]
This would be so helpful!
Any news on this one?

**Comment by joelrdz** [comment]
This would be lovely!

**Comment by Perchant76** [comment]
Its really important for me to be able to review all cards anytime i need. My tests are not scheduled so it can come anytime. And this feature will allow me to study my cards anytime i need

**Comment by visaeryon** [comment]
there is a workaround for this, the time stamp is added or changed only if you review the card Easy or Hard or Good, if you skip the card without reviewing it as Easy or Hard or Good you can review it again as many times as you would like to. you just have to close the review window and open it again for it to reset the count.

but there is a catch, it only shows the flashcards which are due in the past not those scheduled in the future.

**Comment by ronzulu** [comment]
Hi @st3v3nmw I guess the cram feature was implemented to address this request.

Can we close this now?

Cheers
Ronny
