### ISSUE TITLE
YAML tags support

### ISSUE THREAD

**Issue by link-ding** [st3v3nmw/obsidian-spaced-repetition#28]
When I use the tag #flashcards in the YAML the plugin can not recognize the note with this tag, It seems like only detect the tag in the real file. Hope it can recognize the tags in the YAML

**Comment by st3v3nmw** [comment]
Hello, I'll work on fixing that in the next release.

**Comment by st3v3nmw** [comment]
This should be fixed in the latest release (v1.3.2).
