### ISSUE TITLE
[BUG] multiple cloze tags not hidden

### ISSUE THREAD

**Issue by mkschulze** [st3v3nmw/obsidian-spaced-repetition#283]
**Describe the bug**
When having multiple cloze ==tags== in one card, they should all be hidden and only show up, after answering.

**To Reproduce**

Having this card here:
```markdown
#cloze<br>
Condition 1: ==explanation for 1==<br>
Condition 2: ==explanation for 2==<br>
Condition 3: ==explanation for 3==<br>
Condition 4: ==explanation for 4== <br>

```
![Bildschirmfoto 2021-08-30 um 21 34 25](https://user-images.githubusercontent.com/3390820/131394827-c1d0d67f-c7cf-4501-8863-1b5a38596895.png)
![Bildschirmfoto 2021-08-30 um 21 34 58](https://user-images.githubusercontent.com/3390820/131394886-213016ff-508e-400b-b4b3-b595391c20fc.png)

So this goes through the single cloze tags, but meanwhile always shows the other tags that should be hidden, I think.

If that could be fixed, it would be perfect I think, yes.

**Versions (please complete the following information):**
 - OS: [macOS 11.3]
 - Obsidian version: [v0.12.15]
 - Plugin version: [v1.6.2]
 - If on desktop, Installer version: [v0.12.13]

**Comment by st3v3nmw** [comment]
I don't think this is a bug really. That's how Anki clozes work too. Only one deletion is occluded at a time.
I think what you're referring to is something like the [Cloze Overlapper Anki add-on](https://ankiweb.net/shared/info/969733775).

Also, you don't need the `<br/>`, the plugin will pick everything just fine.

**Comment by st3v3nmw** [comment]
You can bury siblings cards in settings till the next day which fixes that
issue.

**Comment by mkschulze** [comment]
Ok, need to try later on desktop. On mobile I just activated that setting, but couldn’t see a difference. The highlights were still visible.

**Comment by mkschulze** [comment]
Ah, burry means to postpone. I thought it means something like blur. Well, I still think it’s at least a design flaw. If I do a single cloze tag in a card it is hidden away. Why should that not apply to multiple cloze tags.

**Comment by st3v3nmw** [comment]
I still don't think it's a design flaw. Taking an example like `=Nairobi== is the capital of ==Kenya==`, hiding _all_ clozes doesn't make much sense.
The current implementation doesn't afford the flexibility like what's described in #93.

Since what you have are enumerations, what's needed is something like Anki's Cloze Overlapper that I linked earlier. & that's a new feature really.

**Comment by mkschulze** [comment]
Ok yes, makes sense. I didn’t think of that case. And would thereby a chance to see a cloze overlapper feature maybe? 🍀

**Comment by st3v3nmw** [comment]
Sure sure, but it will take a little while due to the current issue backlog.

**Comment by mkschulze** [comment]
Could I boost it up again? :)

**Comment by st3v3nmw** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f642.png)

Sure, sure! 😁
