### ISSUE TITLE
[Feat] Flashcard compatibility with lists

### ISSUE THREAD

**Issue by ShreyasKallingal** [st3v3nmw/obsidian-spaced-repetition#29]
**Description**
This is a similar issue to [one I posted on the Flashcards plugin](https://github.com/reuseman/flashcards-obsidian/issues/33#issuecomment-822942172) but I thought it was extra relevant here since this emulates Remnote's features!

When creating inline flashcards using "::" in a list, the card ID is added to the next line, which breaks the list structure.

Example:
<img width="382" alt="Screen Shot 2021-04-19 at 8 20 04 PM" src="https://user-images.githubusercontent.com/23715862/115332419-a2738c00-a14c-11eb-84d9-90f3d7cfcc60.png">

**Proposed solution**

Append the card ID to the end of the line instead of creating a new line. At least for lists, I believe this should be the default behavior. For non-list structures, perhaps this could be a user-configurable option.

Example:
<img width="505" alt="Screen Shot 2021-04-19 at 8 20 42 PM" src="https://user-images.githubusercontent.com/23715862/115332464-b919e300-a14c-11eb-9d37-81986ed4b724.png">

**Markdown used**
- hello
	- question?::answer

**Comment by st3v3nmw** [comment]
Hello,
As discussed on this thread #20, I'll provide a setting to make this user configurable. This should be available in the next release.
Thanks for your feedback.

**Comment by st3v3nmw** [comment]
This should be fixed in the latest release (v1.3.2).
The user setting allows you to change where you want the HTML comment placed _the first time_ (after 1st review). The comment can be in either location & still be recognized correctly so you can move it around as you wish later.

**Comment by ShreyasKallingal** [comment]
Thank you very much!
