### ISSUE TITLE
[Bug] Totals don't fit

### ISSUE THREAD

**Issue by st3v3nmw** [st3v3nmw/obsidian-spaced-repetition#293]
![image](https://user-images.githubusercontent.com/43380836/132978430-3ac36ca8-6e91-4819-b2b6-c5db81a67d47.png)

**Comment by ronzulu** [comment]
Hi @st3v3nmw looks like this has been fixed, perhaps by you a long time ago :smile:

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/96a3f31c-cc61-4035-aad0-9b6c757c2e4b)


Cheers
Ronny
