### ISSUE TITLE
[Feat] Topic decks

### ISSUE THREAD

**Issue by TonyAtlas** [st3v3nmw/obsidian-spaced-repetition#30]
Is there any possibility to add a topic deck feature? In order to learn different topics separately (I don't want to mix English lessons and programming for example).

**Comment by st3v3nmw** [comment]
Yes, I think it can be done. i.e. have an option like `sr-deck: deckname` in the frontmatter to specify the deck for cards in the entire note.

Although it won't be a high priority task for now since I'll be time-constrained for the next few weeks.

**Comment by st3v3nmw** [comment]
Pull requests on this are welcome.

**Comment by whitenoisedev** [comment]
Would it be easier to just use tags instead of introducing another YAML attribute?

**Comment by st3v3nmw** [comment]
Oh yeah, that's pretty neat since we won't be having subdecks.
I'll just expand number of tags one can use for the flashcards.

**Comment by st3v3nmw** [comment]
The latest release (v1.4.3) has support for topic decks.
