### ISSUE TITLE
The whole note viewed as an answer 

### ISSUE THREAD

**Issue by TonyAtlas** [st3v3nmw/obsidian-spaced-repetition#31]
Could you make it possible to make the whole note be viewed as an answer? Or, if not, to be able to open the note associated with the flashcard without aborting the review session?

**Comment by st3v3nmw** [comment]
You mean open the entire note as another modal/pop-up above the flashcard session?

**Comment by TonyAtlas** [comment]
> You mean open the entire note as another modal/pop-up above the flashcard review session? It's not clear.

I mean to make it possible to view the entire note directly in the flashcard window, within its borders. In other words, entire note serves as an answer in the answer field after you hit 'show answer' button. With a possibility to scroll long notes down (I have already requested this feature).
And the 'question' could be some line from this note (marked specifically). Thus it would be possible to not create separate notes for reviewing/learning, but to use existing  notes, rich in text and all other things.

I have made a fake-shot for better understanding. You can see a flashcard window and - inside it - my entire note, as if shown after I have hit 'show answer'. You can also see a scroll bar. Many of my notes are pretty long so it is crucial for me to be able to scroll them down.

Another great bonus of this whole thing  - is that the review session will not be aborted. Because now, when I need some more information on my question and hit 'Open file', the review session is aborted.

![Untitled-2](https://user-images.githubusercontent.com/82872888/115964333-9a409580-a52c-11eb-822b-25cf56f977a1.jpg)

**Comment by st3v3nmw** [comment]
Hello,
I think the reviewing-entire-notes workflow is more suitable for this (described [here](https://github.com/st3v3nmw/obsidian-spaced-repetition#notes)).
Apart from that, we can have the `Open File` link open the file inside the modal as you have demonstrated above. But the problem is, the Obsidian API doesn't let you render the markdown properly (documented in issue #25): we'll end up losing most of the rich text features like images and links. I'll look into other solutions.

**Comment by st3v3nmw** [comment]
It's much easier to save the state of the session. The only problem is that the user might go as far as deleting flashcards text which would lead to file corruption when they try to continue the session.
On the other hand, I find that most people will want to use the `Open File` option to _edit_ their files. Which again, might lead to file corruption if we don't scan for the flashcards afresh.
There's no easy way out either way.
