### ISSUE TITLE
Scrolling option for flashcards

### ISSUE THREAD

**Issue by TonyAtlas** [st3v3nmw/obsidian-spaced-repetition#32]
There is no scrolling option in flashcards for large notes.

**Comment by st3v3nmw** [comment]
Hello,
How large are the cards you're creating?
Can you please post a sample?

**Comment by TonyAtlas** [comment]
> Hello,
> How large are the cards you're creating?
> Can you please post a sample?

Hi! Of course.
Here is the example. 

![Pic_20210423_085011](https://user-images.githubusercontent.com/82872888/115824992-7c324280-a411-11eb-8140-06f974b7bcb3.jpg)
 from a note.

**Comment by st3v3nmw** [comment]
I'll reiterate what I've said in the #31 issue.

I think the reviewing-entire-notes workflow is more suitable for this (described [here](https://github.com/st3v3nmw/obsidian-spaced-repetition#notes)). A card this big isn't really a flashcard.
