### ISSUE TITLE
Reviewing a note collapses folders in review queue

### ISSUE THREAD

**Issue by Signynt** [st3v3nmw/obsidian-spaced-repetition#321]
**Describe the bug**
Reviewing a note as easy, good or hard causes all the open folders in the review queue to collapse.

**To Reproduce**
1. Open the review queue
3. Expand some folders, for example the `Today` one
4. Review a note and select easy, good or hard
5. The next note will open and the open folders in the review queue will collapse

**Expected behavior**
The open folders in the review queue should remain open while moving to the next card.

**Screenshots**
![Bug](https://user-images.githubusercontent.com/67801159/141687360-ca04b8a3-6419-4a38-ad4a-e360106c9d3d.mov)

**Versions (please complete the following information):**
 - OS: macOS
 - Obsidian version: v0.12.19
 - Plugin version: v0.0.17
 - If on desktop, Installer version: `5.0 (Macintosh; Intel Mac OS X 12_1_0) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.10 Chrome/89.0.4389.128 Electron/12.0.14 Safari/537.36`

**Comment by st3v3nmw** [comment]
Hi @Signynt, the new release (v1.7.0) includes fixes that someone else worked on, could you confirm if it fixes this for you?

**Comment by Signynt** [comment]
Hi @st3v3nmw, the new release has indeed fixed this issue for me. 
However now I always need to mark a note as "good, bad or easy" twice before it's status gets updated. Should I mark this issue as closed and open a new issue for this issue?

**Comment by st3v3nmw** [comment]
A new issue will do
