### ISSUE TITLE
[BUG] Cannot show the back-front reversed card during first time learn with randomize card selected 

### ISSUE THREAD

**Issue by into233** [st3v3nmw/obsidian-spaced-repetition#322]
**Describe the bug**
Cannot show the back-front reversed card during first time learn with randomize card selected 

**To Reproduce**
1. randomize card option selected
2. create a new reversed card: `question ::: answer`
3. start lean new card just created
4. see the front-back card and click good
5. see the empty back-front reversed card

**Expected behavior**
See the back-front card in step 5.

**Screenshots**
![image](https://user-images.githubusercontent.com/32983381/142000575-ac2b5f35-ec6d-47c4-be61-8f1a0e5a07bd.png)

**Versions (please complete the following information):**
 - OS: linux
 - Obsidian version: v0.12.19
 - Plugin version: v1.6.2
 - "5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.4 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"

**Comment by st3v3nmw** [comment]
Fixed, should be available in the next release.
