### ISSUE TITLE
[Feat] "Again" option for flashcard review

### ISSUE THREAD

**Issue by ShreyasKallingal** [st3v3nmw/obsidian-spaced-repetition#33]
It would be nice to have an "Again" option when reviewing flashcards, as described in the [Anki documentation](https://docs.ankiweb.net/#/studying?id=learning). This would penalize wrong answers immediately, while currently, you can only reduce the review time using "Hard."

**Comment by st3v3nmw** [comment]
The settings provide a way to configure the interval change when you review something as hard. It's currently set to 50% of the previous interval. But you can change that to say 0% for a restart.

**Comment by ShreyasKallingal** [comment]
Ah, I see. It stipulates that it must be over 0%, however. Would it be possible to add the "Again" button, if it's not too much trouble?

**Comment by st3v3nmw** [comment]
Actually for the hard button, a restart would have to be the next day even if you put the setting as 1%.

Getting full-ish Anki-like behavior would require us to have more tracking information in the HTML comment which would clutter up the notes. For instance, the Again button would require us to keep track of the learning steps, like maybe 1 minute, then 10, then the next day. It's a matter of tradeoffs.

**Comment by miro-hofmann** [comment]
Adding Hour and Minute to the HTML comment could solve this. Also, this would only be needed if that card is to be reviewed on the same day, so it is a reasonable amount of clutter. 

That would be so nice and useful when learning languages or for school. :)

**Comment by st3v3nmw** [comment]
I'll change the date format to ISO8601 as it's more compact (as suggested [here](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/20#issuecomment-822635377)), then I'll add the time & the again button.
I'll do this in the next iteration of the plugin over the weekend.

**Comment by st3v3nmw** [comment]
We now have a rudimentary way to reset a card's progress (v1.4.0). Use the `Reset card progress` link at the top right of the modal or press `0`. The card's scheduling will be reset & it will be put behind the review queue for the current review session.
