### ISSUE TITLE
[BUG] HTML comments from other plugins cause the creation of some cards to be left out.

### ISSUE THREAD

**Issue by andrewcrook** [st3v3nmw/obsidian-spaced-repetition#349]
HTML comments from other plugins cause the creation of some cards to be left out.

**example** 
IDs for 3 cards from the plugin Obsidian to Anki 

<img width="884" alt="image" src="https://user-images.githubusercontent.com/803618/147673884-a7e78850-a960-4de2-a7d7-63627ecb56c4.png">

**result** 
2 cards created for spaced repitition the middle one missing 

** expected **
3 cards for spaced repetition 

** cause **
code checks for the closing of a HTML comment on the next line when it should be the same line.

https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/5514b1a2159bcade9071f3661b2cd66017a2f0f6/src/parser.ts#L38

**Comment by andrewcrook** [comment]
Pull request created #350

**Comment by st3v3nmw** [comment]
PR merged, released in v1.7.0
