### ISSUE TITLE
Tags in YAML still does not work

### ISSUE THREAD

**Issue by link-ding** [st3v3nmw/obsidian-spaced-repetition#35]
I update the plugin to 1.3.2 but the tags #flashcard still does not work. Can you give me a example how to achieve it?
![image](https://user-images.githubusercontent.com/49264539/115698622-2b3a3400-a3a8-11eb-9c9e-4c1fa0c1f50a.png)
![image](https://user-images.githubusercontent.com/49264539/115698664-368d5f80-a3a8-11eb-9df0-ce83cbf0206c.png)
![image](https://user-images.githubusercontent.com/49264539/115698705-43aa4e80-a3a8-11eb-8567-ac4d023c29ea.png)

**Comment by st3v3nmw** [comment]
Hello, like so (remove the quotes around the tag):

```markdown
---
tags: [flashcards]
---
```

**Comment by st3v3nmw** [comment]
There should be a space between `tags:` and `["flashcards"]` so that the YAML is properly formatted.

```yaml
tags: ["flashcards"]
```

**Comment by st3v3nmw** [comment]
Hello,
did it work?

**Comment by link-ding** [comment]
> Hello,
> Did it work?

Sorry, I forgot to reply. That works. Thank you
