### ISSUE TITLE
[BUG] Flashcard Review Decks bug after the recent update

### ISSUE THREAD

**Issue by dummifiedme** [st3v3nmw/obsidian-spaced-repetition#360]
**Describe the bug**
There is an extra deck based on my multi-line card separator. 

**To Reproduce**
1. Go to 'SidePane’
2. Click on 'Spaced Repetition Plugin icon'
4. See error in the decks. 

**Expected behaviour**
Only the decks I have entered in the plugin settings.

**Screenshots**
There is an extra deck ‘Flashcards’, which is actually my flashcard separator. You can see, I cont have a deck named Flashcard in the settings.

![332AC38C-E985-46CD-8C5C-1DE78342F9FE](https://user-images.githubusercontent.com/68785729/147866586-16a5d549-a659-4c6f-8c10-80da7c43fdea.png)
![85E4C0F5-CF9C-48B2-B5FE-F440EB0DC9F6](https://user-images.githubusercontent.com/68785729/147866587-f3a091e0-9e12-42bc-8e4a-95f0e5f5de74.png)

**Versions (please complete the following information):**
 - OS: iPad, Linux
 - Obsidian version: 0.13.14
 - Plugin version: Latest

**Comment by st3v3nmw** [comment]
Try the new release, I think it should be fixed now.

**Comment by dummifiedme** [comment]
Thanks. It’s fixed now.
