### ISSUE TITLE
[FEAT] Adjust style for smaller screens (e.g. iPhone)

### ISSUE THREAD

**Issue by janek** [st3v3nmw/obsidian-spaced-repetition#361]
**Is your feature request related to a problem? Please describe.**
I tried using an iPhone (SE2, so size of 7/8).  I wasn't assuming it would work, but it seems like it can! It's just that the interface was sized wrong, especially for 

**Describe the solution you'd like**
The plugin should take as much space as possible. I'd definitely hope for 100% width, and maybe also height. We may then need a close button.

**Additional context**

| Vertical | Horizontal |
| ------------- | ------------- |
| ![IMG_0887](https://user-images.githubusercontent.com/2146927/147870554-b4960c9e-7d92-4e66-9757-dafcba3febd0.PNG)  | ![IMG_0888](https://user-images.githubusercontent.com/2146927/147870556-3916686c-b84d-4faf-82d6-6c1b9136e09a.PNG)

**Comment by st3v3nmw** [comment]
Hi, you could try adjusting the flashcard height & width in settings

**Comment by janek** [comment]
Worked perfectly, very sorry for not noticing it was a dupe of #231. I did look through the issues and wiki before, but missed it. I'd just found It in the discussions though :)
