### ISSUE TITLE
Subdeck not working properly

### ISSUE THREAD

**Issue by chenxin-yan** [st3v3nmw/obsidian-spaced-repetition#367]
**Describe the bug**
Subdecks do not work for me in both tag or folder method. When I run "Review flashcards from all notes" command. Only the top level folder would show up, without any subdecks.

**To Reproduce**
1. turn on folders as subdecks
2. run "review flashcards from all notes" command

**Expected behavior**
the subdecks should show up and can be reviewed separately.

**Versions (please complete the following information):**
 - OS: macOS 10.15.7
 - Obsidian version: 0.13.9
 - Plugin version: 1.7.1

**Comment by chenxinYan2004** [comment]
Here is the screen shot
![image](https://user-images.githubusercontent.com/71162231/148594018-81a10f4f-cbed-491a-bc88-ae12d3d03763.png)

**Comment by Peingxious** [comment]
**open a random for review**, it's not working

**Comment by ronzulu** [comment]
Hi @chenxin-yan @Peingxious 

Much of the code has been reworked since you posted the issue.

Please let us know if this is still an issue for you.

Cheers
Ronny

**Comment by ronzulu** [comment]
It appears that this has been resolved, so I'll close this now.

Feel free to reopen if this is still an issue.

Cheers
Ronny
