### ISSUE TITLE
[FEAT] add command "cram flashcards from all notes" and/or option to disable adding SR HTML comments

### ISSUE THREAD

**Issue by blackace72** [st3v3nmw/obsidian-spaced-repetition#370]
**Is your feature request related to a problem? Please describe.**
I like the "cram flashcards in note" option, thank you for adding it. I wish it would allow you to cram from all your notes however, because it is tedious to keep opening up "cram" for all my notes. I thought maybe I should just do a normal "review all flashcards" and then delete the HTML comments afterwards, but that is even more tedious due to possibly needing to learn RegEx, having flashcards on MANY files, etc.

**Describe the solution you'd like**
A few options:
- Allow a toggle/option in settings to disable saving the SR html comment/SR data for flashcards (hopefully it can be separate for flashcards and notes, so I can SRS notes, but cram flashcards)
- Create a command like "cram flashcards from ALL/EVERY note"

**Additional context**
Great job! Love the plugin.

**Comment by pathophysiologicalchariotaleeas** [comment]
I also want this!

+1 for this👍🏻

I would like to see something like "cram from all notes"
Or "custom cram"(by selecting decks)

**Comment by blackace72** [comment]
Thank you. Cramming flashcards from any and all decks works now! Thanks so much.
