### ISSUE TITLE
[FEAT] allow changing review result labels

### ISSUE THREAD

**Issue by 229c9cf0** [st3v3nmw/obsidian-spaced-repetition#396]
Review labels are currently fixed "easy" / "good" / "hard". Since I use it for task management and incremental writing, I'd prefer the labels to be something along the lines of "unimportant" / "nothing done" / "progress". Having to mentally invert the meanings when selecting leads to repeated mistakes. ("Hard" is actually good, and "good" is bad.)

This could be done by adding text fields in the settings to override the default labels.

**Comment by AB1908** [comment]
Is #273 related?

**Comment by 229c9cf0** [comment]
Yes, it's an exact duplicate of #273 (seems I missed that one when I searched and then opened this); thanks for noticing!

**Comment by 229c9cf0** [comment]
Duplicate of #273

(seems GitHub is picky about the syntax for marking as duplicate… this should do it.)
