### ISSUE TITLE
[BUG] Inline flashcard inside a multi-line flashcard does not work

### ISSUE THREAD

**Issue by mateusfbsoares** [st3v3nmw/obsidian-spaced-repetition#405]
**Describe the bug**
given a multi-line flashcard, if its back has a inline flashcard, only the inline flashcard will work, and the multi-ilne flashcard will not work

**To Reproduce**
1. create a multinline flashcard such as:
multi-line question
?
multi-line answer

2. add an inline flashcard in one of the lines of the multi-line flashcard, such as:
multi-line question
?
multi-line answer
inline question :: inline answer

3. realize that only the inline flashcard works

**Expected behavior**
for both flashcards to work simultaneously

**Video**
https://user-images.githubusercontent.com/43099047/155275924-c2d5f556-a0c2-46a1-b9de-67ac7d1ba933.mp4

**Versions**
 - OS: ubuntu 20.04
 - Obsidian version: v0.13.23
 - Plugin version: v1.7.2
 - Installer version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.13.23 Chrome/91.0.4472.164 Electron/13.6.2 Safari/537.36

**Comment by st3v3nmw** [comment]
Hi @mateusfbsoares,
You should separate the two cards with a new line to create separate cards. Like so:
```
multi-line question
?
multi-line answer

inline question :: inline answer
```

**Comment by Daniprabha** [comment]
Hi @st3v3nmw 

I know this ticket is closed. But we have many usecases of having inline flashcard inside a multi-line flashcard.
I would like to show an example here:

![image](https://github.com/user-attachments/assets/7d02ef10-7526-4151-8397-aa53f0ef0139)

Here, in this note , we can answer for two questions
1.fruits that are rich in vitamin C ?  ( This will help to remember what are the fruits which are rich in vitamin C
2. BlackCurrants is ?  ( This helps to remember what blackurrants is )

But Currently , only inline card is working  and Multiline card is not showing as Flashcard.
Yes we can manually create seperate note for BlackCurrants and have inline card for it and it will be result in duplication of note.

So Kindly, Please implement this suggestion, It will help lot of people. I am not a techy person But I still wanted to give suggestion on this issue. Sorry for commenting in the closed Ticket. Thank you!
