### ISSUE TITLE
[FEAT] Unfold desks and subdesks 

### ISSUE THREAD

**Issue by huangziwei** [st3v3nmw/obsidian-spaced-repetition#410]
**Is your feature request related to a problem? Please describe.**
I organize my flashcards in folders and enabled “Convert folders to decks and subdecks”. Something like:

```
- language
    - german
        - book 1
            - flashcard 1
            - flashcard 2
        - book 2
            - flashcard 3
        - etc
    - japanese
    - etc
```

By default, all desks were folded. So if I want to practice a specific deck under German, I have to click multiple times and most often I just clicked on a upper level deck..

**Describe the solution you'd like**
My current fix is to change line 1962 in `main.js` to "block", but it would be nice to add an option in the setting to allow unfolded decks.

**Comment by PaperOrb** [comment]
> **Is your feature request related to a problem? Please describe.** I organize my flashcards in folders and enabled “Convert folders to decks and subdecks”. Something like:
> 
> ```
> - language
>     - german
>         - book 1
>             - flashcard 1
>             - flashcard 2
>         - book 2
>             - flashcard 3
>         - etc
>     - japanese
>     - etc
> ```
> 
> By default, all desks were folded. So if I want to practice a specific deck under German, I have to click multiple times and most often I just clicked on a upper level deck..
> 
> **Describe the solution you'd like** My current fix is to change line 1962 in `main.js` to "block", but it would be nice to add an option in the setting to allow unfolded decks.

This has been annoying me, so I just want to thank you for finding the line in order to change this! ;)
