### ISSUE TITLE
[FEAT] Cram All Cards in Specified Deck

### ISSUE THREAD

**Issue by 23727** [st3v3nmw/obsidian-spaced-repetition#418]
**Is your feature request related to a problem? Please describe.**
Currently, we have the ability to cram flashcards of a particular file but not in an entire deck

**Describe the solution you'd like**
I would like to expand on the above concept by allowing the user to cram all flashcards of a particular deck

**Additional context**
Example, instead of a user cramming Integration and then Differentiation, they would be able to cram Calculus. I imagine being able to right click the deck from the queue window and having an option to 'cram cards in deck' 

This would be incredibly helpful when notes are atomic and cramming each note individually would be a lot more cumbersome than cramming per deck

**Comment by LennyPhoenix** [comment]
Going to try and get a rough implementation of this now
