### ISSUE TITLE
[FEAT] Cloze Overlapping Generalization

### ISSUE THREAD

**Issue by MotaOcimar** [st3v3nmw/obsidian-spaced-repetition#426]
### Is your feature request related to a problem? Please describe
A feature that I really like about Cloze Overlapping is that it makes it possible to hide or show some information according to the possibility that it spoils or helps to remember the content.

A classic example is an ordered list:
```
- [[oc1::Item 1]]
- [[oc2::Item 2]]
- [[oc3::Item 3]]
- [[oc4::Item 4]]
```

In Anki, you could configure it to show the item before the one asked and hide the others.

The way of setting it up, however, was one of the main drawbacks of Cloze Overlapping for me. In the card edition itself, it was not so clear what the current configuration was. Also, it was limited to the ability to show only neighboring items as a cue.

This means that if the cue/context text is not neighboring the asked text, it cannot be configured to be displayed only when needed. For example:

```
Some context to items 2 and 4, but that could spoil items 1 and 3.
.
- [[oc1::Item 1]]
- [[oc2::Item 2]]
- [[oc3::Item 3]]
- [[oc4::Item 4]]
```

In general and in summary, I would like to propose 3 things for this Obsidian extension:
- Implementation of a cards similar to Cloze Overlapping (#284);
- That this feature has a simpler configuration;
- That in this feature it is possible to create customized asking modes, solving the problem described above.

### Describe the solution you'd like
While the first point is being addressed in issue #284, I can propose a solution to the other two points.

One way to set up your overlaping clozes right in the card edition and enable personalized asks is as follows:
- Each cloze is identified by a sequence of actions on how it will behave in each card:
    - `a` for ask
    - `h` for hide
    - `s` for show

Example:
```
==Some context to items 2 and 4, but that could spoil items 1 and 3. Notice it even need to be asked==[^hshs]
.
- ==Item 1==[^ashh]
- ==Item 2==[^hash]
- ==Item 3==[^hhas]
- ==Item 4==[^hhha]
```

In this example 4 cards will be generated, where items 1 to 4 will be asked sequentially. When asking `Item 1`, all other text will be hidden. When asking `Item 2`, both the `Item 1` and the _context text_ will be displayed. When asking `Item 3`, only the `Item 2` will be displayed. Finally, when asking  `Item 4`, both the `Item 3` and the _context text_ will be displayed.

Note that the _context text_ could be an image or rich text that wouldn't be worth putting in a hint. What's more, you might also want to ask the _context text_, in which case this generalization would also help:

```
==Some context to items 2 and 4, but that could spoil items 1 and 3.==[^ahshs]
.
- ==Item 1==[^hashh]
- ==Item 2==[^hhash]
- ==Item 3==[^hhhas]
- ==Item 4==[^hhhha]
```

### Additional context
Related to #284 and #93

**Comment by ronzulu** [comment]
Hi @MotaOcimar, very powerful functionality! I'm wondering if you could clarify a few things.

# Q1
```
Some context to items 2 and 4, but that could spoil items 1 and 3.
.
- [[oc1::Item 1]]
- [[oc2::Item 2]]
- [[oc3::Item 3]]
- [[oc4::Item 4]]
```

I'm not sure how to interpret the above. Normally the `[[ ` and `]]` are used to enclose Obsidian links.

# Q2
> One way to set up your overlaping clozes right in the card edition and enable personalized asks is as follows:

Curious about the meaning of `edition` in `card edition`

Also, what does the "overlapping" refer to?

# Q3

Above there is the following example:
```
==Some context to items 2 and 4, but that could spoil items 1 and 3. Notice it even need to be asked==[^hshs]
.
- ==Item 1==[^ashh]
- ==Item 2==[^hash]
- ==Item 3==[^hhas]
- ==Item 4==[^hhha]
```

Does _context text_ refer to `Some context to items 2 and 4, but that could spoil items 1 and 3. Notice it even need to be asked`?

Is the full stop on the second line there simply to ensure the parser treats the full six lines as a single question, or does it have any other significance?

There are 5 clozes, but only 4 characters in each of the action sequences. Is that why the first cloze is treated as the context text? If there were only 3 characters in each of the action sequences, would it treat the first 2 as the context text, and only 3 cards generated? Or would that be treated as an error?

# Q4

From #943:
> In this example, 4 cards will be generated, where items 1 to 4 will be asked sequentially. 

I'm curious about the sequential ordering. Do you mean that it should be sequential even if the configuration setting `Order cards in a deck are displayed during review` is set to random?

# Q5

I'm curious about how the code knows that `[^hash]` is an action sequence, because the format is the same as for hints.

# Q6

Is it valid to have multiple clozes with an `a` action character in the same position? e.g. in the following both item 1 and 4 have `a` in the first position.

```
==Some context to items 2 and 4, but that could spoil items 1 and 3. Notice it even need to be asked==[^hshs]
.
- ==Item 1==[^ashh]
- ==Item 2==[^hash]
- ==Item 3==[^hhas]
- ==Item 4==[^ahha]
```

Does this mean that when item 1 is asked, item 4 is also asked. However, when item 4 is asked item 1 is hidden?

Thanks
Ronny

**Comment by MotaOcimar** [comment]
Hi @ronzulu!! Thanks for reviewing this feature and for the questions!

# Q1
Sorry, I didn't make it clear, but this syntax using `[[` and `]]` was originally used by the [Cloze Overlapper](https://github.com/glutanimate/cloze-overlapper), the Anki plugin that introduced this overlap cloze idea. So, no need to worry about using this syntax in Obsidian. In the proposal here, I changed it to use highlights, and in the implementation of #943, it kept using the user-chosen cloze syntax.

# Q2
When I originally wrote this issue, I used the expression `card edition` to refer to the raw note the user writes (which will eventually be transformed into cards).

I also ended up using the term "overlapping" a lot here (and "overlapped" in PR #943) as an adjective for the clozes that are part of the functionality proposed here or originally proposed by Glutanimate in his Anki plugin.

Maybe I got some terms confused back then 😅 Thank you for asking for clarification. Please feel free to correct me or suggest better terms.

# Q3
> Does _context text_ refer to `Some context to items 2 and 4, but that could spoil items 1 and 3. Notice it even need to be asked`?

Yes, that's right. This "context text" wouldn't be a formal term, just an expression I chose to refer to something the user might want to hide and show without necessarily questioning.

> Is the full stop on the second line there simply to ensure the parser treats the full six lines as a single question, or does it have any other significance?

It’s just to ensure the parser treats all six lines as a single "note"; it doesn't have any other relevant significance. It’s a pattern I ended up adopting in my notes for the plugin when I want to have a "blank" line in the middle of the note without breaking it into several. I’ll take the opportunity to ask: is there a more appropriate way to do this?

> There are 5 clozes, but only 4 characters in each of the action sequences. Is that why the first cloze is treated as the context text? If there were only 3 characters in each of the action sequences, would it treat the first 2 as the context text, and only 3 cards generated? Or would that be treated as an error?

No. The first cloze is treated as "context text" because it doesn't have the action of being questioned. The number of characters in the action sequence doesn't need to have a direct relation to the number of clozes. It is actually related to the number of cards that will be created. For example, the following note would be valid and would generate only a single card, showing the context, questioning the first item, and hiding the remaining items:

```
==Some context to items 2 and 4, but that could spoil items 1 and 3. Notice it even need to be asked==[^s]
.
- ==Item 1==[^a]
- ==Item 2==[^h]
- ==Item 3==[^h]
- ==Item 4==[^h]
```

Already anticipating, a case that does need to be handled is each cloze having a different number of action characters. Although this could generate an error, in the implementation of PR #943, I preferred to [define "show" as the default action for these cases](https://github.com/MotaOcimar/clozecraft/blob/b3ce3d3bf6fcffa1ea743d0bc73e7ce8c5bcb78c/src/implementation/ClozeNoteOL.ts#L70).

For example: `This is a ==cloze1==^[a] ==cloze2==^[sha] ==cloze3==^[ha]` will be the same as `This is a ==cloze1==^[ass] ==cloze2==^[sha] ==cloze3==^[has]`

# Q4

> I'm curious about the sequential ordering. Do you mean that it should be sequential even if the configuration setting `Order cards in a deck are displayed during review` is set to random?

No, this doesn't change the plugin's ordering settings. It just means that the [cards are passed sequentially to the plugin](https://github.com/MotaOcimar/obsidian-spaced-repetition/blob/b1a700925a07d108e71ea0797a271634492b8add/src/QuestionType.ts#L105). To be honest, I'm not sure how the plugin orders the cards; I haven't explored this functionality much. If you think I should correct the PR description, please let me know.

# Q5

> I'm curious about how the code knows that `[^hash]` is an action sequence, because the format is the same as for hints.

In PR #943, I actually proposed that hints follow the format `^[footnote hint]`, which differs by having the `^` outside the `[]` instead of inside. Thus, there's no conflict.

If the user, however, configures it in a conflicting way, the code will choose the pattern that matches first, [since it uses regular expressions](https://github.com/MotaOcimar/clozecraft/blob/b3ce3d3bf6fcffa1ea743d0bc73e7ce8c5bcb78c/src/implementation/ClozeRegExp.ts#L16). Ideally, the user should avoid configuring it this way, but I'm not sure yet how to prevent it.

# Q6

> Is it valid to have multiple clozes with an `a` action character in the same position? e.g. in the following both item 1 and 4 have `a` in the first position.
> 
> ```
> ==Some context to items 2 and 4, but that could spoil items 1 and 3. Notice it even need to be asked==[^hshs]
> .
> - ==Item 1==[^ashh]
> - ==Item 2==[^hash]
> - ==Item 3==[^hhas]
> - ==Item 4==[^ahha]
> ```

Yes, it's valid. To help understand, you can remember that each action character is directly linked to the card of the position it is in. So, for the cloze `==Item 1==[^ashh]` from the example above, we have:

```
[^ashh]
  |||└> Action on the 4th card is to be hidden both front and back
  ||└> Action on the 3rd card is to be hidden both front and back
  |└> Action on the 2nd card is to be shown both front and back
  └> Action on the 1st card is to be questioned
```

> Does this mean that when item 1 is asked, item 4 is also asked. However, when item 4 is asked item 1 is hidden?

It means something close to that. For the example above, 4 cards will be created. On the first card, both items 1 and 4 are questioned. But on the fourth card, only item 4 is questioned, while item 1 is only hidden.

To make it clearer, here are the 4 cards:

## Card 1
Front:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/2fe5c58b-465b-48cf-90a4-1f4c81b8ceb4)
Back:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/1a0d29d6-ae51-43b0-afb3-09d2a0d0b4d2)

## Card 2
Front:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/be611b26-be42-41ec-8ed5-b3c7fb023d9b)
Back:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/e24260d7-5565-4a89-8910-17d90051e3be)


## Card 3
Front:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/18143359-fdb8-4b2a-a5d4-64c663ca61ec)
Back:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/f0bb7e05-2e06-4ca8-9f7d-023b13b92343)

## Card 4
Front:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/2793c9a4-b110-435e-9c98-7d78ed92b1ea)
Back:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/29007115/8770a847-cd99-4515-ac58-df13bcf74dba)


Best,
Ocimar

**Comment by st3v3nmw** [comment]
Hi,

I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that ships with custom cloze patterns 🥳 all thanks to #943. The updated documentation is live [here](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cloze-cards/#cloze-types).

I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.

Cheers.

**Comment by LeonelRFF** [comment]
This is great, I tried it and it works fine 👏💪 For future versions, I would add a "-" sign before the hint so that it is only visible if necessary.
It would be like this: `-hint`
On the card it would look like this

```
# Test items anki
.
{{ashh;;anki Item 1;;-hint anki 1}}
{{hash;;anki Item 2;;-hint anki 2}}
{{hhas;;anki Item 3;;-hint anki 3}}
{{hhha;;anki Item 4;;-hint anki 4}}
```

Although of course, for that, it would be necessary to add one more button that has the function of showing the hint.
Greetings.
