### ISSUE TITLE
[FEAT] allow copying flashcard

### ISSUE THREAD

**Issue by jeromeshih1** [st3v3nmw/obsidian-spaced-repetition#428]
**Is your feature request related to a problem? Please describe.**

The flashcard cannot be copied.

**Describe the solution you'd like**

allow copying flashcard like text

**Additional context**

if flashcards can be copied, they will be of additional usage.

**Comment by AB1908** [comment]
Can you give a step by step descriptive example of how you would use this feature?

**Comment by st3v3nmw** [comment]
This should be fixed in the latest release, v1.9.2.

It has a change to make the flashcard text selectable which makes it easy to copy. Related: https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/538

If this isn't what you meant, feel free to reopen this issue
