### ISSUE TITLE
[Feat] Allow for fixed chain repetition

### ISSUE THREAD

**Issue by mkschulze** [st3v3nmw/obsidian-spaced-repetition#43]
It would be a great help to learn schemata that have a fixed order of steps.

Say I want to learn a scheme to solve a legal case, for example:

Title: Scheme to argue on claim XY

1. condition 1 (card 1 front) / explanation (card 1 back)
2. condition 2 (card 2 front) / explanation (card 2 back)
3. condition 3 (card 3 front) / / explanation (card 3 back)
intermediate result

So, if I want to learn this scheme, the cards would need to be a fixed chain for the repetition.

### Idea:
Maybe the title could be a card deck and with a certain tag on the #flashcard, the ordering could be fixed.

Like a YAML instruction
cards-deck: schemefolder::subdeck-schemexy

This is how card decks and subdecks can be done in Anki with Obsidian Flashcards
![Bildschirmfoto 2021-05-01 um 23 28 53](https://user-images.githubusercontent.com/3390820/116795408-0004c280-aad5-11eb-97df-1be8929873f1.png)
![Bildschirmfoto 2021-05-01 um 23 29 13](https://user-images.githubusercontent.com/3390820/116795415-0c891b00-aad5-11eb-83f9-9dbde61def5d.png)

Then having the order fixed with further tags, within the deck container.
1. condition 1 #card1
2. condition 2 #card2
3. condition 3 #card3     

I could then open the deck and start the repetition chain.

This would be a huge help for me.

Thanks for consideration!
Mark

**Comment by st3v3nmw** [comment]
Since this issue also mentions decks & subdecks, I'll start with that (also opened #30) then get to the fixed chain repetition.

**Comment by st3v3nmw** [comment]
For clarification, here's how I've thought of this:
If we start a review session, we go through all the cards & schedule the scheme as a whole. Such that the "sub-cards" (i.e. `condition 1 #card1`) are not scheduled independently. & then they'll all show up at once in the same order during the next review.

Is that right?

**Comment by mkschulze** [comment]
> For clarification, here's how I've thought of this:
> If we start a review session, we go through all the cards & schedule the scheme as a whole. Such that the "sub-cards" (i.e. `condition 1 #card1`) are not scheduled independently. & then they'll all show up at once in the same order during the next review.
> 
> Is that right?

Yes, that's right. The spaced repetition on the sub-cards could be deactivated and instead the spaced repetition could work on the deck as a whole.

**Comment by mkschulze** [comment]
Hey, just wanted to ask, wether this is getting closer for consideration?

**Comment by st3v3nmw** [comment]
I've been interning, haven't had enough time in my hands, but we'll get there soon.

**Comment by st3v3nmw** [comment]
Apart from bug fixes, I'll be working on this next.

**Comment by mkschulze** [comment]
Nice, maybe it could work with a new tag category, alphabetical or numeral. For example, #A-1 #A-2 #A-3 which would be Deck #A and then the sorting reference number. Just an idea maybe.

**Comment by st3v3nmw** [comment]
I've given this some thought & think that this particular use case is better served by multiline cloze cards. This way, the subcards are scheduled independently to make sure that they're all memorized independent of each other. So if one is having issues remembering `condition 2 (card 2 front) / explanation (card 2 back)` it shouldn't prevent `condition 3 (card 3 front) / explanation (card 3 back)` from making progress if it's an easy "subcard".
Also, the upcoming release makes sure that one will always see new "subcards" in cloze cards in order even when randomizing card order (like in Anki).
& since your donation was a feature request for this issue, I have refunded both payments. Thanks.
Closing...

**Comment by mkschulze** [comment]
Ok, so this would look like:

Learn the steps in order:
1. ==CONDITION1==
2.==CONDITION2==
3.==CONDITION3==
?
1. Title of CONDITION1 + Explanation
2. Title of CONDITION2 + Explanation
3. Title of CONDITION3 + Explanation

But wouldn't that essentially mean, that this all sits in one CLOZE card?
I think I don't get the subcard point yet.

> Also, the upcoming release makes sure that one will always see new "subcards" in cloze cards in order even when randomizing card order (like in Anki).
This means I make a #deck1 and all the subcards appear in order?

**Comment by st3v3nmw** [comment]
I think something like this would work:
1. Condition 1: ==explanation for 1==
2. Condition 2: ==explanation for 2==
3. Condition 3: ==explanation for 3==

**Comment by mkschulze** [comment]
ok, will try. thx!

**Comment by mkschulze** [comment]
Sorry to bother you again @st3v3nmw 

I struggle with setting things up, like you described, I think.

How do I get this to work:
> Also, the upcoming release makes sure that one will always see new "subcards" in cloze cards in order even when randomizing card order (like in Anki).

I now created the following multiline flashcard with cloze tag:
```markdown
#clozeexample
Condition 1: ==explanation for 1==
Condition 2: ==explanation for 2==
Condition 3: ==explanation for 3==
?
Condition 1: ==Test1==
Condition 2: ==Test2==
Condition 3: ==Test3==
```

This is nice, but it doesn't help so much, if I have like 20 conditions I want to remember. 
Then I'd ideally have separated flashcards. But how do I get them to appear in exact order within the chosen deck?

Do you have an idea, am I missing something?

**Comment by st3v3nmw** [comment]
> ```gfm
> ?
> ```

This mixes up card types (cloze & multiline basic), currently the plugin only works for one card type at a time.

> This is nice, but it doesn't help so much, if I have like 20 conditions I want to remember.

Yes, I agree, the cards would be too big. Not sure how I can help though, since it's the source material that's the issue here. Is there a way to break them down & create clozes for subsections of the schema?

**Comment by mkschulze** [comment]
Ok, I think I got the idea now. With multiple cloze tags, they will need to be answered one by one in a fixed order, right? I didn't work with cloze tags yet, but that would work, yes.

However, I think there is a bug, maybe.

Having this card here:
```markdown
#cloze
Condition 1: ==explanation for 1==
Condition 2: ==explanation for 2==
Condition 3: ==explanation for 3==
Condition 4: ==explanation for 4==
```
![Bildschirmfoto 2021-08-30 um 21 16 55](https://user-images.githubusercontent.com/3390820/131393156-e927d522-15f7-4bd6-996e-104bb369ca52.png)

![Bildschirmfoto 2021-08-30 um 21 23 31](https://user-images.githubusercontent.com/3390820/131393545-246eb956-a105-42c0-b4b6-7bf4e02ee2a4.png)

So this goes through the single cloze tags, but meanwhile always shows the other tags that should be hidden, I think.

If that could be fixed, it would be perfect I think, yes.
