### ISSUE TITLE
 Custom syntax or {{Curly Brackets}} for cloze flashcards

### ISSUE THREAD

**Issue by DryIce1** [st3v3nmw/obsidian-spaced-repetition#431]
Would it possible to add either the ability to make a custom cloze syntax or add {{Curly Brackets}} cloze syntax.

I would prefer to only use ==highlights== in my notes for highlights. 

Thanks!

_Originally posted by @DryIce1 in https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/244#discussioncomment-1555405_

**Comment by MotaOcimar** [comment]
Related to #387

**Comment by st3v3nmw** [comment]
Fixed in #438, pending release, will update after change goes out

**Comment by MotaOcimar** [comment]
in #439 XD

**Comment by st3v3nmw** [comment]
> in #439 XD

Oops, updated
