### ISSUE TITLE
[BUG] Grade buttons overlap longer multiline answer

### ISSUE THREAD

**Issue by JonThom** [st3v3nmw/obsidian-spaced-repetition#434]
**Describe the bug**
When reviewing flashcards, the grade buttons overlap longer multiline answers

**Screenshots**
![image](https://user-images.githubusercontent.com/30726223/161711994-159f1f4a-f252-4441-a8de-721bd9a4411d.png)

**Versions (please complete the following information):**

-   OS: macOS
-   Obsidian version: [e.g. v0.12.4]
-   Plugin version: 1.7.2

**Comment by daamiian** [comment]
This issue still persists. I only have 4 lines on mine 😕

**Comment by 4Source** [comment]
@st3v3nmw / @ronzulu this should be fixed

**Comment by ronzulu** [comment]
Agreed, seems fixed to me. I'll close now.
