### ISSUE TITLE
[BUG] Update number of notes after a review

### ISSUE THREAD

**Issue by johnsonsuqs** [st3v3nmw/obsidian-spaced-repetition#437]
**Describe the bug**
![image](https://user-images.githubusercontent.com/100344601/162563933-936840b6-6de4-425e-9ed1-ad54bfb1ddc2.png)
Above are my settings
![image](https://user-images.githubusercontent.com/100344601/162563885-842fdbff-d063-493b-b887-ae88173d21ab.png)

These days, occasionally I review many notes according to the prompts, and also submit the choice, the system also responded correctly, but the number of review notes on the bar remains the same

![image](https://user-images.githubusercontent.com/100344601/162564057-6751b265-a100-491a-903c-5c75aa936312.png)
And the time to provide me with notes dul has not arrived,I have a lot of notes that I don't review without prompting me.

I tried to overload the plugin, and installing the latest version didn't solve the problem

**Versions (please complete the following information):**

-win10 
**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by ronzulu** [comment]
@[karimod](https://github.com/karimodm)

I'm pretty sure you fixed this whilst fixing #424 😊

For anyone wanting this fix, there is a beta version available at:
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/424#issuecomment-1873654236

Hopefully will be included in the mainstream release in the next few weeks. 

Cheers
Ronny

**Comment by 4Source** [comment]
@st3v3nmw / @ronzulu this should be fixed

**Comment by ronzulu** [comment]
Agreed, seems fixed to me. I'll close this now.

**Comment by 4Source** [comment]
@ronzulu is this a help for you If I check old issues and mention you if there are fixed? Maybe we can reduce the mass of problems, if you are interested in it.

**Comment by ronzulu** [comment]
@4Source great if you can do that. I was doing that for a while, but lately I've been trying to finish off #878 instead.

**Comment by 4Source** [comment]
> @4Source great if you can do that. I was doing that for a while, but lately I've been trying to finish off #878 instead.

Great if I got time I will check some and mention you hopefully this will reduce the issues
