### ISSUE TITLE
Add setting to remove "Review: Easy Good Hard" from page options

### ISSUE THREAD

**Issue by DaveyUS** [st3v3nmw/obsidian-spaced-repetition#44]
Here's what I'm referring to:

![Image 1](https://user-images.githubusercontent.com/53842399/116800294-b2785d80-aab4-11eb-99a4-5b164d29b6b4.png)

Adding 3 items to the page options modal seems like a bit much. Personally I use your plugin by creating flashcards and reviewing them in the queue all in one go. I won't ever be using these 3 items and would love the option to remove them. If I'm being totally honest, I think they are an overreach and should be disabled by default, especially because you can get to them with commands... but that's open for debate.

**Comment by st3v3nmw** [comment]
Hello,
I will provide an option to disable them in the next release.
I think having them there by default provides a way for non power users to get started much quicker.

**Comment by DaveyUS** [comment]
Totally understand, thanks!

**Comment by st3v3nmw** [comment]
The setting is now available in v1.4.2 in the Notes section.

**Comment by DaveyUS** [comment]
Just saw. Thanks for the really quick turn around!

**Comment by st3v3nmw** [comment]
Nice, I'll close this then.
