### ISSUE TITLE
Embed block

### ISSUE THREAD

**Issue by Klaudioz** [st3v3nmw/obsidian-spaced-repetition#440]
I have the following test note:

> #flashcards
> 
> Favorited quote ?::[[Quotes#^5a0bf2]]

Any chance I can see the content of [[Quotes#^5a0bf2]] in the solution or at least see it after putting the mouse on it. I just want to don't repeat myself.

![TestNote](https://user-images.githubusercontent.com/632625/165138658-7e194ed6-9415-4ded-81f3-24a3aafb77df.png)

**Comment by vasalx** [comment]
@Klaudioz Works with transclustions, e.g., **!**[[Quotes#^5a0bf2]], if you do not mind having the contents in the card note.

**Comment by dominik-selmeci** [comment]
Hi!
I have the same problem: I don't know how to use the whole block as an answer. I tried:
`Why we are using hooks?::![[Why we are using hooks]]`

But the result is the same as @Klaudioz had.

![image](https://user-images.githubusercontent.com/17047331/179679850-e81e8146-a050-498a-986e-be9eb7f399c9.png)

**Comment by dominik-selmeci** [comment]
Ah, my bad. I didn't update plugins for some time :)...

After updating the plugin, everything works fine.
Thanks for such a great plugin!

**Comment by st3v3nmw** [comment]
Hi @Klaudioz, @vasalx's / @dominik-selmeci's solution should fix this, closing..
