### ISSUE TITLE
[FEAT] Less interval time for hard button

### ISSUE THREAD

**Issue by navakelvin** [st3v3nmw/obsidian-spaced-repetition#443]
I would like the repeat interval for the "hard" option to be set to less than one day.

Why wait a whole day to repeat a card you forgot?

Going down from a day to hours, minutes, or seconds is critical when you want to quickly and intensively memorize content for an upcoming test.

**Comment by st3v3nmw** [comment]
Duplicate of #503 
Will be tracking this issue there
