### ISSUE TITLE
[BUG] Stats don't work anymore

### ISSUE THREAD

**Issue by superouioui** [st3v3nmw/obsidian-spaced-repetition#447]
I have Obsidian Charts  3.6.1 and Spaced Repetition 1.7.2

**Comment by st3v3nmw** [comment]
Hey @superouioui,
SR 1.8.0 doesn't rely on Obsidian Charts anymore, you could confirm if this is still happening

**Comment by ronzulu** [comment]
Hi @superouioui 

We haven't heard back from you, and no one else has reported this issue.

I'll close this now, but feel free to reopen if this is still an issue.

Cheers
Ronny
