### ISSUE TITLE
[BUG] New sidebar focus makes plugin difficult to use

### ISSUE THREAD

**Issue by yeruvan** [st3v3nmw/obsidian-spaced-repetition#460]
Recently Obsidian started allowing you to treat the right sidebar as your current focus pane. This makes certain Spaced Repetition hard to use. If I am already focused on the sidebar, when I open a note from the sidebar, it replaces the Spaced Repetition tab with that note, and I can’t get back to SR without restarting obsidian.

To see reproduction and behavior, see this video:

https://forum.obsidian.md/t/new-sidebar-focus-has-made-some-plugins-unusable/39056

Windows 11, Obsidian 0.15.2, Spaced Rep 1.7.2

**Comment by AB1908** [comment]
Can you check if this is fixed?

**Comment by isle9** [comment]
> Can you check if this is fixed? If not, can you give steps to reproduce this error?

It is not fixed.

1. Enable note review and add a couple of notes using the tag you chose.
2. Click on the pane with note reviews.
3. Click on any of the notes inside the pane.
4. The note will not open in the center, and will instead overwrite the pane itself.

**Comment by AB1908** [comment]
Yes, I think I fixed this in #469. It was just merged and a new version should be available.

**Comment by st3v3nmw** [comment]
This is fixed in the new release v1.8.0.
