### ISSUE TITLE
[BUG] Notes Review Queue Pane get replaced with Note

### ISSUE THREAD

**Issue by AstronosMK** [st3v3nmw/obsidian-spaced-repetition#468]
When clicking on a Note in the Notes Review Queue Pane.
Instead of opening a new Pane for the clicked note, the Notes Review Queue Pane get replaced by the note

**Comment by fredriksy** [comment]
I'm also experiencing the same issue, it appears to be related to the latest version of obsidian

**Comment by AB1908** [comment]
Let me see if I can repro.

**Comment by AB1908** [comment]
Yup, fairly easy to repro.

**Comment by AB1908** [comment]
What was the original behavior? I hadn't used this feature before and want to preserve functionality.

**Comment by AB1908** [comment]
In case Stephen doesn't get around to merging the fix soon, you should be able to use the release from my repo using the BRAT plugin.

**Comment by fredriksy** [comment]
> What was the original behavior? I hadn't used this feature before and want to preserve functionality.
> 
> Edit: never mind, the original text says it opened a new pane to review the note. Seems easy enough to add back in.

Sorry for the late response! Your understanding is correct

**Comment by fredriksy** [comment]
> In case Stephen doesn't get around to merging the fix soon, you should be able to use the release from my fork using the BRAT plugin.
> 
> https://github.com/AB1908/obsidian-spaced-repetition/

Thanks a bunch, I haven't tried the BRAT plugin yet but I'll have a look. I'll also look at the PR so I can maybe learn what happened

**Comment by jvmachados** [comment]
Same issue here! Commenting just to get notified of future replies.

**Comment by st3v3nmw** [comment]
This is fixed in the new release v1.8.0.
