### ISSUE TITLE
Issue with Horizontal Rules in the notes

### ISSUE THREAD

**Issue by xelaras** [st3v3nmw/obsidian-spaced-repetition#48]
If I try to review for te first time a Note that already has it's own YAML code in it AND has other Horizontal Rules (---), the plugin puts it's YAML code where the last Horizontal Rule is, and not in the YAML header. (Using Obsidian v.0.12.2)

Thanks

**Comment by st3v3nmw** [comment]
Thanks for the bug report.

**Comment by st3v3nmw** [comment]
The fix should be available in the next release this weekend.
