### ISSUE TITLE
[BUG] Rule of Two Spaces Support

### ISSUE THREAD

**Issue by Servinjesus1** [st3v3nmw/obsidian-spaced-repetition#484]
**Bug Description**

A slightly obscure spec of Markdown is that line breaks which should be interpreted as such (and not paragraph breaks) should be preceded by two spaces on the previous line. In Obsidian, this isn't really much of a problem, unless you're like me and use Obsidian Linter. This plugin reformats my notes on save to be inline with many Markdown spec rules, including that paragraphs should be separated by two lines, unless two spaces exist on the line previous.

Sadly, this affects Spaced Repetition, as neither separation of multi-line flashcard delimiters (`::` or `??`) by two blank lines, nor two white spaces on the same line as the delimiter seem to be valid syntax. Weird behavior happens with the former (lots of blank cards), and cards are unrecognized (or front/back concatenated when clozes are present) with the latter.

**To Reproduce**

1. Go make cards
2. Add two spaces on the front and delimiter of multi-line cards
3. Validate the behavior of Obsidian Linter (make sure Ignore Two Lines under Trailing Linebreaks is on)
4. If linting does not affect your desired structure, then case two above happens (Cram -> cards not recognized)
5. If linting does mess up your desired structure (or really, adheres it to Markdown specs), case one happens.

**Expected behavior**

Lines with a flashcard multi-line delimiter and two spaces should be parsed like lines with just the delimiter (or to be uber conformant, the standard should be multi-line delimiters of the form (`??  ` or `::  `)

**Other Relevant Details**

v1.8.0 | Linter v1.3.6 | Obsidian v0.15.9

**Comment by Erimus-Koo** [comment]
Same situation.

```
como  
?  
吃  
第一人称: yo **com*o*** nosotros/<br>nosotras **com*emos***  
第二人称: tú **com*es*** vosotros/<br>vosotras **com*éis***  
第三人称: él/ella/<br>usted **com*e*** ellos/ellas/<br>ustedes **com*en*** 
```

Markdown linter automatically add 2 space after every line, and cards can not be recognized.

**Comment by Erimus-Koo** [comment]
> Same situation.
> 
> ```
> como  
> ?  
> 吃  
> 第一人称: yo **com*o*** nosotros/<br>nosotras **com*emos***  
> 第二人称: tú **com*es*** vosotros/<br>vosotras **com*éis***  
> 第三人称: él/ella/<br>usted **com*e*** ellos/ellas/<br>ustedes **com*en*** 
> ```
> 
> Markdown linter automatically add 2 space after every line, and cards can not be recognized.

I found in settings set the **Separator for multiline flashcards** with `?  ` (2 spaces after), and it works.

**Comment by Servinjesus1** [comment]
Lol, I should have tried this. Thanks @Erimus-Koo, good solution.
