### ISSUE TITLE
[FEAT] Allow displaying words in clozed completions

### ISSUE THREAD

**Issue by putzwasser** [st3v3nmw/obsidian-spaced-repetition#496]
**Is your feature request related to a problem? Please describe.**
If you have a cloze it hides everything within it. It would be nice to allow displaying "fill" words or other hints within the cloze. It would require a little bit of extra syntax, though.

**Describe the solution you'd like**
Given you'd indicate a “multiple cloze” clozed completion with surrounding curly brackets you'd achieve this:

`Consumer surplus is the difference between {==the maximum price== a consumer is willing to pay and the ==actual price== they do pay}`

The flascard would look like:

`Consumer surplus is the difference between […] a consumer is willing to pay and the […] they do pay`

You'd have to answer all blanks at once and the answers get shown at once.

So, all clozes within `{` and `}` get “combined” and hidden/shown together. 

As my flashcards are separated from my actual notes, I'd have no problem by adding some wrapping curly braces. For people who mix/store their “content” notes and flashcards within the same note the syntax could be `%%{%%Your ==multi== clozed ==completion==%%}%%`

This is more verbose, but it hides the curly braces if you're just reading the note.

**Comment by jvmachados** [comment]
This feature would be truly amazing!

**Comment by putzwasser** [comment]
Maybe a more anki like syntax (`{1:first} cloze {1:still first} deletion {2:text}`) would be preferable. #439 paves the way here.

**Comment by st3v3nmw** [comment]
Tracking this in #93, comment moved there
