### ISSUE TITLE
[BUG] Reviewing a Notes doesn't update the yaml correctly

### ISSUE THREAD

**Issue by AstronosMK** [st3v3nmw/obsidian-spaced-repetition#504]
**Describe the bug**
When reviewing a note sometimes the new yaml gets pasted below the old, instead of updating it

**To Reproduce**

Go to Review Queue
Update card with any response
Yaml gets added a second Time
Doesn't always happen, but quite often.
Unknow it which cases it does and doesn't happen

**Expected behavior**
Yaml should just update instead of getting added twice

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77455517/192986036-3aba6999-ef09-46bf-b3cd-36fa1aa74b06.png)

**Versions (please complete the following information):**

-   OS: Windows 10
-   Obsidian version: [e.g. v0.15.9]
-   Plugin version: [e.g. v1.8.0]

**Comment by st3v3nmw** [comment]
Hey @AstronosMK, how often is this occurring (as an estimate percentage of your reviews)?

**Comment by AstronosMK** [comment]
@st3v3nmw ~25% of the time

**Comment by AstronosMK** [comment]
Found out why it happens.
Had my hotkey for review as Easy as Ctrl + del
The del key still triggers when used in a hotkey combination.
it removed one "-" of the frontmatter, therefore making it invalid and new frontmatter gets added
