### ISSUE TITLE
[FEAT] Remember expand/collapse status of cards

### ISSUE THREAD

**Issue by Erimus-Koo** [st3v3nmw/obsidian-spaced-repetition#508]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/17139670/194740639-24e46b98-90ff-4a62-adb2-15e6c0e794ca.png)
I have to click many times to reach a child card.

**Describe the solution you'd like**

There is 2 suggestions:

1. Remember tree status
2. Add a button like `expand/collapse All` 

**Additional context**

**Comment by MostlyArmless** [comment]
You may find that [this PR](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/510) helps this problem. It's already been merged to master but no new release has been made since then.
