### ISSUE TITLE
[BUG] webp images not printing on screen while reviewing flashcards

### ISSUE THREAD

**Issue by mathisgauthey** [st3v3nmw/obsidian-spaced-repetition#517]
**Describe the bug**
Some of my flashcards are made of a question and a picture is the answer. Some of them are webp. They are not printing correctly inside the reviewing process, whereas it works correctly on Obsidian.

**To Reproduce**
Create a multiline card like : 
```
Meilleur assemblage de fromage ?
?
![[k8xx1shsgqv91.webp]]
```

**Expected behavior**
Image should be printing when answering.

What is happening is as follow :
![image](https://user-images.githubusercontent.com/46576952/198285275-35a5e2d7-807a-4fcc-9679-24747efcbcaf.png)

**Versions (please complete the following information):**

-   OS: Windows
-   Obsidian version: 1.0.3
-   Plugin version: 1.8.0
-   If on desktop, Installer version: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.15.6 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36'

**Additional context**
None

**Comment by st3v3nmw** [comment]
Fixed in #560, should be available in the next release
