### ISSUE TITLE
[FEAT] Option to hide seperator character in read mode 

### ISSUE THREAD

**Issue by PieterDeKruiff** [st3v3nmw/obsidian-spaced-repetition#520]
I love this plugin, but I'm missing a visual component. Say we have this line of text in obsidian:

_Spaced repetition
?
Spaced repetition is an evidence-based learning technique that is usually performed with flashcards._

I'd like to see this when I turn on read mode 

_Spaced repetition
Spaced repetition is an evidence-based learning technique that is usually performed with flashcards._

or 

_Spaced repetition is an evidence-based learning technique that is usually performed with flashcards._

Some people maybe don't care for it so I thought it could just be a setting that you can turn on and off or a format type thing you set yourself in the settings.

**Comment by AB1908** [comment]
This is actually quite hard to do as we'd have to write a CodeMirror extension (if I understand correctly).

**Comment by PieterDeKruiff** [comment]
> 

No problem! I just changed the character "?" to a visually more pleasing one: 

![image](https://user-images.githubusercontent.com/116900254/201520564-1e2de728-a700-425e-a7fa-33abbf71fd55.png)

Thanks for the response!
