### ISSUE TITLE
[BUG] Decks don’t show in mobile

### ISSUE THREAD

**Issue by silora** [st3v3nmw/obsidian-spaced-repetition#521]
**Describe the bug**
Decks don’t show in Obsidian mobile

**To Reproduce**

1. Click on Review flashcard or Cram/Review cards in this note
2. Decks wont show

**Expected behavior**
Show the decks

**Screenshots**
![0844D600-2AA3-441B-84E5-9C36C97EAC60](https://user-images.githubusercontent.com/73022221/198930303-48cde28e-e8c3-44f4-8c94-65ac91c2d832.png)
![99338CC5-8BA7-4EEC-9780-0ECBFB59A041](https://user-images.githubusercontent.com/73022221/198930317-c080bb10-aeb6-4154-9bbb-515cd2578f0e.png)

**Versions (please complete the following information):**

-   OS: iOS 16.0
-   Obsidian version: v1.4.1
-   Plugin version: v1.8.0

**Comment by AB1908** [comment]
Can you reproduce this in a sandbox vault?

**Comment by st3v3nmw** [comment]
Is this still occurring in the latest release?

**Comment by ghelton** [comment]
I also have this issue on the latest iOS. Here's a screenshot from the latest version(v1.10.2). I can see content now but the modal isn't cooperating.
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/48418/e3fb2753-fa9c-4d7b-9528-922c609cc1ab)

**Comment by AB1908** [comment]
Have you changed width percentage in plugin settings?

**Comment by ghelton** [comment]
Yep that was the issue for me, I must have set that a while ago, looks great now. That you
