### ISSUE TITLE
[FEAT] Pomodoro linked opening of card review.

### ISSUE THREAD

**Issue by vorpalvorpal** [st3v3nmw/obsidian-spaced-repetition#526]
**Is your feature request related to a problem? Please describe.**
It takes effort to actually do spaced repetition. 

**Describe the solution you'd like**
Could obsidian be set up to automatically pop up a single card every x minutes. 25 minutes is the standard Pomodoro length, but the exact number should obviously be able to be set by the user.

**Additional context**

**Comment by ronzulu** [comment]
Hi @vorpalvorpal 

Unfortunately no one else has requested this feature, and isn't likely to be something that would be implemented in the plug-in for the foreseeable future.

Have you considered some kind of macro playback utility? something like:
https://autohotkey.en.softonic.com/

Perhaps that can be configured to wait 25 minutes, bring the Obsidian window to the front, simulate pressing a hot key that would activate the flashcard review window.

(autohotkey - Not a particular product recommendation) 

Cheers
Ronny

**Comment by vorpalvorpal** [comment]
No worries. I might try using the [custom js plugin](https://github.com/saml-dev/obsidian-custom-js) to get the functionality.
