### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sfield541** [st3v3nmw/obsidian-spaced-repetition#537]
**Describe the bug**
Error message produced is: "Failed to install Space Repetition"
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain the bug. This could be the logs in the developer console (`CTRL` + `SHIFT` + `i`).

**Versions (please complete the following information):**

-   OS: [e.g. iOS]
-   Obsidian version: [e.g. v0.12.4]
-   Plugin version: [e.g. v1.4.9]
-   If on desktop, Installer version: [run `this.navigator.appVersion` on the developer console, e.g. `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"`]

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by myownstandard** [comment]
the same here 
OS: mac and windows
Obsidian version: 1.0 , 1.0.3, 1.1.2

**Comment by AB1908** [comment]
This has been remedied in the latest release. Kindly double check and close.
