### ISSUE TITLE
[FEAT]  Support multiple spaced repetition algorithms

### ISSUE THREAD

**Issue by changefu** [st3v3nmw/obsidian-spaced-repetition#551]
**Is your feature request related to a problem? Please describe.**
The SM-2 algorithm is inflexible and out of date，Algorithms need to be provided that can be chosen by people。

**Describe the solution you'd like**
A friend of mine is also an expert on spaced repetition algorithms and has published a paper at ACM SIGKDD proposing a modern spaced repetition algorithm. Here is the free access version https://www.maimemo.com/paper/
**Additional context**
Both Remnote and Anki already support the new algorithm, and I hope your plugin will support it too. Here is his contact information: 
    twwitter:   https://twitter.com/JarrettYe?s=20

**Comment by st3v3nmw** [comment]
Hey,
Thanks for the suggestion! I'll look into the algorithm

**Comment by st3v3nmw** [comment]
Tracking in #516 instead
