### ISSUE TITLE
[FEAT] Single card with multiple simultaneous clozes 

### ISSUE THREAD

**Issue by Celeblith** [st3v3nmw/obsidian-spaced-repetition#552]
### Problem
Currently each cloze segment (highlighted or bolded portion of a card) creates a separate card. So if an entry has three clozes, three cards will be added to the deck, one for each cloze. Which is great sometimes as it makes creating contextual cards for language learning much more efficient. But ...

### Feature
It would also be nice to have an additional and alternative cloze that allows multiple cloze replacements to appear on the same card. This is useful for cards where multiple segments of the card go together. For example, when creating cards for Latin, I might make a card like:

>In castrīs sunt quattuor mīlia mīlit==um== fort==ium==

In the above card, the endings of _mīlitum_ and _fortium_ agree with each other, so correctly answering the card would require supplying both endings at the same time. However, if I made this entry, it would instead create two separate cards, bloating my deck and making the cloze less valuable. 

### Context: Current Workarounds
My current workaround is to make cards like this one:

>In castrīs sunt quattuor mīlia mīlit_[...]_ fort_[...]_ :: In castrīs sunt quattuor mīlia mīlit_um_ fort_ium_

The problem with this workaround is that it takes much longer to make the card, the color and format of the italic blanks does't match the usual blue, non-italic clozes, and italicizing brackets sometimes does weird things to my formatting. Most of these issues are aesthetic, but multiple clozes per card would still be a nice feature nonetheless.

**Comment by st3v3nmw** [comment]
Added comment to #93 for tracking there, closing this duplicate issue...
