### ISSUE TITLE
[FEAT] Custom cloze tokens

### ISSUE THREAD

**Issue by polyipseity** [st3v3nmw/obsidian-spaced-repetition#556]
Currently the plugin provides `==highlights==`, `**bold text**`, and `{{curly brackets}}` (d8c0e9eca2c569f38dd2d656b564d4656c0ec1d3) for clozes. It might be better to allow user-inputted characters as the opening and closing tokens like the separator options now.

However, currently you can enable all three cloze options simultaneously, unlike the separator options where you can only specify one separator, so this might need to be handled by either:
1. Multiple cloze tokens can be specified (perhaps extend this to the separator options)
2. Add the custom token option while keeping the current three options (maybe deprecate the latter later)

I am willing to put the work into implementing it but I want to see if this is a good idea first.

**Comment by st3v3nmw** [comment]
Hi,

I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that ships with custom cloze patterns 🥳 all thanks to #943. The updated documentation is live [here](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cloze-cards/#cloze-types).

I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.

Cheers.

**Comment by polyipseity** [comment]
> Hi,
> 
> I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that ships with custom cloze patterns 🥳 all thanks to #943. The updated documentation is live [here](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cloze-cards/#cloze-types).
> 
> I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.
> 
> Cheers.

Thanks! Two quick issues that I have found:

- Upgrading settings does not work.

```

**Comment by polyipseity** [comment]
> Hi,
> 
> I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that ships with custom cloze patterns 🥳 all thanks to #943. The updated documentation is live [here](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cloze-cards/#cloze-types).
> 
> I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.
> 
> Cheers.

Thanks! One quick issue that I have found: Upgrading settings does not work. It expects the property `clozePatterns` to exist in `data.json` in order to upgrade the settings, but clearly said property does not exist in old versions of the plugin. The stacktrace is as follows:

```
plugin:obsidian-spaced-repetition:11549 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'contains')
    at upgradeSettings (plugin:obsidian-spaced-repetition:11549:72)
    at _SRPlugin.loadPluginData (plugin:obsidian-spaced-repetition:26650:60)
    at async _SRPlugin.onload (plugin:obsidian-spaced-repetition:26358:5)
```

**Comment by polyipseity** [comment]
Otherwise, the update looks fine to me!
