### ISSUE TITLE
[BUG]Unable to preview webp format images

### ISSUE THREAD

**Issue by Diplproveably** [st3v3nmw/obsidian-spaced-repetition#567]
Any image inserted in webp format cannot be previewed and only a file name can be seen.
The editing interface in obsidian looks like this
![image](https://user-images.githubusercontent.com/111405888/210080067-dc8830ea-6920-402b-9d19-e356b77711ac.png)
And when viewing the card it looks like this
![image](https://user-images.githubusercontent.com/111405888/210080238-3315ec5a-b1b0-4ed3-8898-6f8944fa8559.png)

**Comment by st3v3nmw** [comment]
This should be fixed in the new release, v1.9.2
