### ISSUE TITLE
Request: View Cards at Any Time

### ISSUE THREAD

**Issue by RaySimmons** [st3v3nmw/obsidian-spaced-repetition#568]
I would like to be able to review my deck at any time. However, it seems that once I review all the cards in a deck, it is not possible to review them until the next day. In other words, when I click on the deck, nothing happens.

**Comment by st3v3nmw** [comment]
Currently, the only supported method is "cramming" all cards in a note using the `Cram flashcards in this note` command. Will work on a per-deck thing

**Comment by st3v3nmw** [comment]
Likely fixed in https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/515 which will be available in a few days

**Comment by RaySimmons** [comment]
Thanks for keeping up with it.

**Comment by Nathan-Harlan** [comment]
Hey! love the plug-in. Checking in on this issue, has it been completed?

**Comment by Nathan-Harlan** [comment]
Found it! had to add a hot key. Thanks!

**Comment by mmngtb** [comment]
> Found it! had to add a hot key. Thanks!

Where did you find it?

**Comment by Nathan-Harlan** [comment]
If you go to add hotkeys to the plugin it shows up as an option to cram by deck

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/42306942/3a0b7719-3156-4b08-bfdb-40ed3e002894)

**Comment by Kangaroo9103** [comment]
A command to immediately review a deck is a game changer for the usefulness of this plugin; thank you @Nathan-Harlan for pointing this out! 

My only suggestion would be to implement this cramming functionality into the "Review flashcards" UI

**Comment by ronzulu** [comment]
> My only suggestion would be to implement this cramming functionality into the "Review flashcards" UI

Sounds good
