### ISSUE TITLE
[FEAT] Custom Convert To Cloze Options

### ISSUE THREAD

**Issue by claudiella** [st3v3nmw/obsidian-spaced-repetition#581]
**Is your feature request related to a problem? Please describe.**
With the use of other plugins such as the Annotator that uses highlights, Natural time codes that use curly brackets, and a hierarchy folder plugin that uses bolded text there is no other option for me to make a cloze that is custom and won't interact by bringing these random sections of notes into my cards. 

**Describe the solution you'd like**
Adding an option to choose your own cloze parenthesis brackets/symbols just like you can select your own card separators. E.g people may want to use -cloze- +cloze+ !cloze! ;cloze; etc.  

**Additional context**
Not sure if this is possible, first ever feature request, let me know if you need any more details!

**Comment by st3v3nmw** [comment]
Hi,

I've just made a release [v1.13.0](https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.13.0) that ships with custom cloze patterns 🥳 all thanks to #943. The updated documentation is live [here](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/cloze-cards/#cloze-types).

I've tested the release but not as extensively as I normally would. Perhaps we need a beta version of the plugin? That being said, I'm on standby to fix bugs ASAP. Just give me a shout.

Cheers.
