### ISSUE TITLE
Full screen card mode on Mobile

### ISSUE THREAD

**Issue by badjerphoenix** [st3v3nmw/obsidian-spaced-repetition#585]
**Is your feature request related to a problem? Please describe.**

Currently, when I use the plug in, it works great while on desktop (PC)

Being able to study the flashcards while on the go via my Android phone is a key feature I need/ want. However, when I try to do so the flashcard it is very narrow & hard to review. This not only effects the speed at which I can read the card but also the speed at which I can rate my understanding of the card

![2023-01-07 10 04 03](https://user-images.githubusercontent.com/78933852/211160612-972b8ea9-488f-43c0-a314-22df7712a667.jpg)

**Describe the solution you'd like**

I would simply like to be able to view the card in full screen view. It would be understandable not having a full screen option for the desktop but having it on mobile would be quite useful

**Comment by Gim3l** [comment]
On mobile you can set the size of the flashcard to 100% by going to the plugin's settings. Just drag the slider all the way to the right under the "Flashcard Width Percentage" option.
