### ISSUE TITLE
Access reset card progress w/o cutting off content - Mobile

### ISSUE THREAD

**Issue by badjerphoenix** [st3v3nmw/obsidian-spaced-repetition#590]
**Is your feature request related to a problem? Please describe.**

I typically study flashcards from mobile (Android phone) as I am often on the fly. When  I click on the answer & am taken to the *answerer side* it is not very easy to view the content of the answer.

Due to the placement of the *reset card progress* button the content of the answer ends up being viewed in a narrow column of sorts. This makes it quite difficult to view on mobile as a result of the limited screen real estate

See image. 
*Side note: The image I provided would not actually be used as a flashcard. I simply grabbed a random file that would iterate my point of the narrow view that had no info that I was unable to share due to confidentiality issues. So I am quite aware that I would normally structure the card differently*

**Describe the solution you'd like**

To place the *reset card progress* button in a way that it would not make the answer narrow when viewing it

Some possible options are: (1) place beside the easy, good & hard buttons at the bottom (2) Place beside the *edit later button*

Thanks for considering the feature request

![2023-01-07 13 58 07](https://user-images.githubusercontent.com/78933852/211179748-3f24dfdc-b52e-4756-91d0-0e753ad1234e.jpg)

**Comment by st3v3nmw** [comment]
This is in the pipeline (see https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/589) and will be available soon.
Thanks for the bug report!

**Comment by badjerphoenix** [comment]
Sounds good
Thanks for keeping me in the loop

**Comment by monstertank** [comment]
```
.sr-link {
    float: unset !important;
}
```
current temporary solution

**Comment by badjerphoenix** [comment]
> ```
> .sr-link {
>     float: unset !important;
> }
> ```
> 
> current temporary solution

How exactly does that work as I am not so familiar with that kind of thing? Also, if this on a per card basis where it has to be entered onto every flashcard?
