### ISSUE TITLE
Conflict  with Dataview Plugin

### ISSUE THREAD

**Issue by KALKI-the-avataar** [st3v3nmw/obsidian-spaced-repetition#60]

**Comment by KALKI-the-avataar** [comment]
The inline field of dataview plugin is rendered as flashcard

**Comment by st3v3nmw** [comment]
Could you please provide an example of this? I've not used the dataview plugin, yet.

**Comment by KALKI-the-avataar** [comment]
As dataview inline fields are as

Field Name::Field Value
the spaced repetition plugin recognises it as a flashcard.

**Comment by st3v3nmw** [comment]
There's really no way to fix this without changing the syntax for detecting inline flashcards.
& I don't think that's something I'm willing to do.

**Comment by xelaras** [comment]
Hello, I really hope you reconsider changing the syntax for detecting inline flashcards. Dataview is one of the most used plugin within the Obsidian community with more than 14,000 downloads. I think keeping the Spaced Repetition plugin compatible with Dataview will allow more people to use you plugin.

**Comment by st3v3nmw** [comment]
Hello,
We could have more ways for the inline flashcards syntax then.
Any suggestions?

**Comment by xelaras** [comment]
Maybe ";;" or "!!"?

**Comment by domkm** [comment]
You could make it configurable. Give the user a setting, defaulting to `::`, and build the regex from that.

**Comment by st3v3nmw** [comment]
This should be fixed in the next release.
I went with the domkm's configuration option for greater flexibility.
