### ISSUE TITLE
Mobile UI Issues 

### ISSUE THREAD

**Issue by overkill864** [st3v3nmw/obsidian-spaced-repetition#609]
Can't seem to see any of the information landscape or vertical mode on Android. 
![Screenshot_20230123_062504_Obsidian](https://user-images.githubusercontent.com/119825814/214064172-6121c66c-9c79-4dd3-b79f-b4ca770d1e34.jpg)

**Comment by mathisgauthey** [comment]
Same issue here

**Comment by mathisgauthey** [comment]
Fix : You need to max these two bad boys in the settings.

![image](https://user-images.githubusercontent.com/46576952/215597361-e7581c9b-89f8-4f83-b83a-aa14447d7260.png)

**Comment by philipgold** [comment]
> Fix : You need to max these two bad boys in the settings.
> 
> ![image](https://user-images.githubusercontent.com/46576952/215597361-e7581c9b-89f8-4f83-b83a-aa14447d7260.png)

Yes, it works for IOS. Thank you so much.

**Comment by st3v3nmw** [comment]
👍🏾 @mathisgauthey.

The new release (v1.10.0) also makes further UI improvements on mobile:

![Screenshot from 2023-02-06 13-42-19](https://user-images.githubusercontent.com/43380836/216956891-58c0d5db-d5c9-4925-93be-0f1da7d0de1c.png)
