### ISSUE TITLE
[BUG] Cloze card not working while using callouts

### ISSUE THREAD

**Issue by mathisgauthey** [st3v3nmw/obsidian-spaced-repetition#612]
**Describe the bug**

I'm using callouts to be able to have multiple cards on a single note with cloze. If I use "-" to make a list, the card reviewing shows the entire note. This way I get to have the linter working, and the note creation process is easy.

It wasn't happening before, even though I have not updated it. Don't know what changed.

**To Reproduce**

Create a note with multiples callouts, with close cards inside and using the repetition informations on the same line as the card.

**Expected behavior**

I should only see my callout with the cloze, note the whole note with a buggy callout.

**Screenshots**

![Screenshot_20230126-144724.png](https://user-images.githubusercontent.com/46576952/214852771-326a8afa-15dd-4fd9-95ea-85f8e57171ac.png)

![Screenshot_20230126-144736.png](https://user-images.githubusercontent.com/46576952/214852772-0865a096-c10f-4468-a582-77a9f1d4bba3.png)

![Screenshot_20230126-144944.png](https://user-images.githubusercontent.com/46576952/214852770-88437f91-cd9a-474c-b91a-292bb642136a.png)

**Versions (please complete the following information):**

-   OS: Android 13
-   Obsidian version: 1.4.1
-   Plugin version: 1.8.0

**Additional context**
Maybe it was because I used to have cards store informations at the end of the note and not at the end of the cloze line. I'm looking into it.

**Comment by AB1908** [comment]
This is a parser bug and relatively easy to fix and I'm open to mentor anyone who wants to attempt this. Roughly, we first need to add a couple of tests in the parser tests and then we need some mock data that reproduces this behavior. Once that's down and correctly captures cases like these, we can write some code against this to add the feature for better cloze parsing.

**Comment by mathisgauthey** [comment]
I think I got around by rebuilding manually every single cards to make them work with in-line informations. I'll keep this post updated if it evolves.
