### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by leitaosha** [st3v3nmw/obsidian-spaced-repetition#628]
It will be wonderful that word listening could be played automatically (options : once, twice and three times) when reviewing

**Comment by ronzulu** [comment]
Hey there, I think you will need to add more explanation about this feature request, e.g..

- What does "word listening" mean?
- Is this in the context of reviewing notes or flashcards?

Please include relevant screenshots and/or snippets from an existing note. Also please update the issue subject to include a brief summary.

Cheers
Ronny

**Comment by ronzulu** [comment]
Hi @leitaosha 

We haven't heard back from you, and I'm unclear about what you would like enhanced.

I'll close this now, but feel free to reopen if this is still an issue.

Cheers
Ronny
