### ISSUE TITLE
[FEAT] Mobile Phone style fix, Portrait mode screen 

### ISSUE THREAD

**Issue by stefandanzl** [st3v3nmw/obsidian-spaced-repetition#633]
I had the issue of not being able to use the plugin on mobile because of the box being too narrow. 
By adding the following custom CSS into the **.obsidian/snippets** folder and enabling it in **Settings > Appearance > CSS Snippets** I was able to fix it and make it detect the screen's portrait mode.
I would recommend adding this to the plugin's styling as now it is perfectly usable on my 2400x1080 phone screen in portrait mode.

```
@media only screen and (orientation: portrait) {

.modal {
	
	width: 100% !important;
	max-width: 100%;
	max-height: 100%;
}

}
```

**Comment by mayukhc** [comment]
I think there's 2 settings for width and height which needs to be set at 100 for mobile, see [231](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/231), [361](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/361) etc.

**Comment by stefandanzl** [comment]
Oh, thank you! 
But still, in the name of user friendliness it would be good to include some sort of media query to make the experience even smoother.
