### ISSUE TITLE
[BUG] Skip >> Produces Error.  Can't click on the Deck afterwards.

### ISSUE THREAD

**Issue by christopherAI2022** [st3v3nmw/obsidian-spaced-repetition#645]
**Describe the bug**

[BUG] Skip >> Produces Error.  Can't click on the Deck afterwards.

**To Reproduce**

1. Go to 'Review Flashcards'
2. Click on 'flashcards'
3. Click on 'Skip>>'
4. See error: Can't click on "Flashcards" deck again

**Expected behavior**
That Skip >> brings you back to the same original menu, listing of decks.  But it seems to disable the ability to click on the deck again.

**Screenshots**
-

**Versions (please complete the following information):**

-   OS: Mac OS 10.13.6
-   Obsidian version: [e.g. v0.12.4]
-   Plugin version: Version 1.1.16 (Installer 0.15.9)

**Additional context**
N/A

**Comment by AB1908** [comment]
Oof, I wonder if I broke the skip button haha. Will try and repro this if I can.

**Comment by ronzulu** [comment]
Hi @christopherAI2022, a lot of flashcard code has been restructured since you reported this issue.

Can you please upgrade to the latest version of the plug-in, and let us know if the issue occurs or not.

Cheers
Ronny

**Comment by ronzulu** [comment]
Hi @christopherAI2022 we haven't heard back from you.

I believe this is not a current problem, and will close the issue now.

Feel free to reopen if necessary.
