### ISSUE TITLE
[BUG] Marking a note for review removes older YAML data 

### ISSUE THREAD

**Issue by JYunth** [st3v3nmw/obsidian-spaced-repetition#647]
**Describe the bug**
Marking the note after review (Either easy, good or hard) creates a completely new YAML header with the new spaced repetition data, and disregards the previous YAML data

**To Reproduce**
1. Make a note with YAML data that doesn't just include the spaced repetition fields.
2. Mark it easy, good or hard

**Expected behavior**
The YAML data gets updated, leaving all the other fields and data intact.

**Screenshots**
![image](https://user-images.githubusercontent.com/76583660/224749102-5c5ffcde-2ac9-4231-964b-494257791164.png)

**Versions (please complete the following information):**

-   OS: Windows
-   Obsidian version: 1.1.16

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by ronzulu** [comment]
Hi @JYunth 

A related problem #776 has been fixed and was recently released.

Could you please upgrade to the latest release of the plug-in, and report back whether or not this is still a problem for you.

Cheers
Ronny

**Comment by ronzulu** [comment]
We haven't heard back from you, and no one else has reported this issue.

I'll close this now, but feel free to reopen if this is still an issue.

Cheers
Ronny
