### ISSUE TITLE
[BUG] External link is not rendered after pressing "Show answer"

### ISSUE THREAD

**Issue by mistadikay** [st3v3nmw/obsidian-spaced-repetition#659]
**Describe the bug**
Hi, love your plugin, but I have a strange bug I don't quite understand. If my flashcard note contains an external link, it is not rendered after I press "Show answer" but instead "disabled; enabled in settings" message displayed. I looked all over the settings of Obsidian and the plugin but couldn't find anything related. Can you help me understand if it's a bug or there is an obvious setting I'm missing? Thanks.

**To Reproduce**

1. Have a note with an external link
2. During review click on "Show answer"
3. Instead of external link "disabled; enabled in settings" is displayed

**Expected behavior**
External link should be rendered as usual and be clickable.

**Screenshots**
<img width="603" alt="Skärmavbild 2023-04-01 kl  15 06 58" src="https://user-images.githubusercontent.com/742056/229291353-38be70f6-2aab-475d-91f8-275ec593973a.png">
<img width="719" alt="Skärmavbild 2023-04-01 kl  15 07 04" src="https://user-images.githubusercontent.com/742056/229291355-a55bfbcb-c017-48a6-b4d2-a85546138067.png">

**Versions (please complete the following information):**

-   OS: MacOS
-   Obsidian version: 1.1.16
-   Plugin version: 1.10.0
-   If on desktop, Installer version: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.0.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36'

**Additional context**
-

**Comment by ronzulu** [comment]
Hi @mistadikay 

Is this still an issue? I tried this now and couldn't reproduce it.

```
#flashcards/test/b659

Possible to reproduce this problem
?
Here is the external link
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/659
```

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/11860039-fd45-4b77-b5f3-3130e18be82f)

Hovering over link works correctly:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/45aff93f-92f8-4d72-9f97-c67af8712d7a)

And clicking on the link opened a new tab in the browser for the specified URL.

Cheers
Ronny

**Comment by mistadikay** [comment]
Seems to be fixed now!
<img width="650" alt="Skärmavbild 2024-01-18 kl  10 29 26" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/742056/9d4a8ed2-c700-4496-a5ce-590475a89ea2">

**Comment by ronzulu** [comment]
Thanks for the quick response!
