### ISSUE TITLE
[FEAT] Add MathJax Support

### ISSUE THREAD

**Issue by pfabri** [st3v3nmw/obsidian-spaced-repetition#669]
**Problem**
Cards containing MathJax notation do not render when reviewing.
Simplified example: in MathJax the notation for *x squared* looks like this: `$x^2$`, which, inside Obsidian, renders nicely as you'd see in a book or PDF. But flashcards will only show the syntax of the expression i.e. `$x^2$`

**Preferred Solution**
Would it please be possible to have the cards display the rendered results of MathJax expressions?

**Additional Context**
[MathJax basic tutorial and quick reference](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference)

**Comment by maggaou** [comment]
I cannot reproduce this.
![](https://i.imgur.com/YPHIOzk.png)
![](https://i.imgur.com/L3jHAwV.png)

**Comment by pfabri** [comment]
@maggaou Apologies, you're right it does, indeed, work. I may have accidentally surrounded the MathJax expression with backticks. Sorry for the waste of space and time! Please feel free to close & delete the issue.

**Comment by pluckey** [comment]
It doesn't create cards for clozes containing only a single mathjax expression:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/10790397/8436bffa-a2fd-4c63-82ff-4280944e3ea0)
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/10790397/aa7a5d9b-9543-4300-9573-cbdaa5e1787b)

**Comment by ronzulu** [comment]
Hi @st3v3nmw, the OP @pfabri requests that this be closed.
