### ISSUE TITLE
Indentation to be preserved while making flashcard

### ISSUE THREAD

**Issue by semits20** [st3v3nmw/obsidian-spaced-repetition#67]
while making flashcards indentation is not being preserved when switching from editor to preview. If that can be preserved then it would be easy to be worked. I have tried to use indentation with obsidian core plugin and also with outliner plugin in both the case, it is the same issue. Can it be fixed?

**Comment by st3v3nmw** [comment]
Hello,
Do you mean that the scheduling information is stored on the next line hence breaking lists?

Say something like:

```
- list item 1
   - front::back
<!--SR etc -->
- other
```

**Comment by st3v3nmw** [comment]
If that's the case, there's a setting option to put the scheduling information on the same line hence not breaking cards (for the single-line q::a style)

**Comment by semits20** [comment]
No, i dint mean like that i meant like that 
* > Under the onslaught of colonial culture & ideology, instead of providing basis for d development of secular ethos, universalism into religious particularism towards d end of 2nd half of 19th century
		* evolution of ==alternative cultural ideological system & regeneration of traditional institutions==-> twin concern of these movements

if i use cloze then going back to preview, it is not preserving the indentation

**Comment by st3v3nmw** [comment]
Okay, got it. I'll provide a fix soon.

**Comment by semits20** [comment]
I love the plugin bcoz it is inbuilt in the Obsidian framework. I think i should have asked for this request separately but i am raising it here. Is there any alternative way to create multiple-line flashcard, because the use of "?" is not so intuitive. And if i use it with the outliner plugin or with the obsidian core plugin of indentation, it is a little bit cumbersome because I have to move that block out of the main context.  I think it would be much better like Remnote style.

**Comment by st3v3nmw** [comment]
The fix should be available in the next release.
I'll investigate the Remnote multiline flashcards style and see how it goes.

**Comment by semits20** [comment]
Recently the plug in got updated. But i think issue is still persisting. I dont know whether u have fixed the issue with this release.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by st3v3nmw** [comment]
Hmm,
Even after toggling that `Save scheduling comment on the same line as the flashcard's last line?` option?

**Comment by semits20** [comment]
I have uninstalled and installed the plugin, now its working fine. It is preserving the indentation. Thanks a lot for addressing the issue so spontaneously.
I have one question in case of multiline flashcard with indentation or outliner plugin working, the flashcard does not work. Is this feature going to be added in future? Or whether i am missing any point. I don't know.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by semits20** [comment]
Another point i have noticed, even after assigning tags the decks are not being mentioned @ the time of reviewing flashcards

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by st3v3nmw** [comment]
About the remnote-style multiline style, that's yet to be implemented.
Is the deck issue the same as the one raised in #83?: using command palette shortcut to review flashcards doesn't show any flashcards.

**Comment by st3v3nmw** [comment]
I'll close this since the main issue has been addressed.

**Comment by semits20** [comment]
I have not tried with command pallet but i use the sidebar icon. Using that i dont see any decks when reviewing the flashcards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by semits20** [comment]
U may close it. Thanks a lot for addressing the issue swiftly. Keep up the good work.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by st3v3nmw** [comment]
Please open a new issue with some more information (say the developer console log, Obsidian version, etc) so that we can address this. Thanks!
