### ISSUE TITLE
Label customizations not applying to menu items [BUG]

### ISSUE THREAD

**Issue by jehrich** [st3v3nmw/obsidian-spaced-repetition#670]
**Describe the bug**
As a user, when customizing the button labels, I expect to see the same values in the context menu and other areas, otherwise it can be confusing which option to select.

**To Reproduce**

1. Change the Easy, Good, Hard button labels from the settings panel to "Custom1", "Custom2", "Custom3".
2. Exit and re-open Obsidian for good measure.
3. Right-click on a note.
4. Notice the text still reads: "Review: Easy", "Review: Good", "Review: Hard"

**Expected behavior**
The context-menu items should read: "Review: Custom1", "Review: Custom2", "Review: Custom3".

**Versions (please complete the following information):**

-   OS: MacOS Ventura 13.3.1
-   Obsidian version: v1.1.16
-   Plugin version: v1.10.0
-  '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.1.16 Chrome/106.0.5249.199 Electron/21.4.1 Safari/537.36'

**Comment by lsolesen** [comment]
I also experience this.

Also it would be great if it was possible to create different labels for flashcards and notes. Then it would be possible to implement Andy Matuschak's terminology:

1. Fruitful
2. Skip
3. Unfruitful

When using the plugin for spaced repetition in the inbox.

**Comment by st3v3nmw** [comment]
This has been fixed in the latest release (v1.11.1). I'm closing this issue but if it's still occurring, please re-open the issue and we'll look into it further
