### ISSUE TITLE
[BUG] Flashcards are broken if the separator line contains spaces

### ISSUE THREAD

**Issue by carloslab-ai** [st3v3nmw/obsidian-spaced-repetition#690]
**Describe the bug**
Many times my flashcards do not appear in the deck.
I've tried to reload Obsidian multiple times in the hope that they would appear but in the end I became desperate.

Until today I just realized it's because I accidentally added spaces to the separator line.😭
These spaces are invisible so I can not detect them.

**To Reproduce**

1. Add a new flashcard
2. Add spaces to the separator line

For example:

abc
??_ _(add spaces here)
def

3. Review this deck
4. This flashcard does not appear in the deck

**Expected behavior**
The flashcard appear in the deck regardless of whether there were spaces in the separator line or not

**Versions (please complete the following information):**

-   OS: Android
-   Obsidian version: 1.4.5
-   Plugin version: 1.10.1

**Comment by AB1908** [comment]
Good report. Would you like to be the one to fix it? It should be a rather simple change in the parser.

**Comment by richardrl** [comment]
Very interesting find @carlos-truong !!!! This could be the reason why my cards were also invisible. #685

**Comment by richardrl** [comment]
I am working on fixing this. 

Another thing I want to simultaneously fix: we need a way to track which cards do not have ANY question separator (such as `multilineCardSeparator`.

Right now, if you make a card with NO separator, the card becomes invisible. Suppose you have 1000 cards. It becomes completely impossible to track down which cards are incomplete (i.e. no separator, you only took some rough notes on the card, you didn't clearly write down a question/answer).

My workflow with cards is I am constantly putting notes down, then adding a tag like #flashcards/my_subject. But often these notes/cards are incomplete.

But under the current system, it becomes impossible to sift through my massive number of cards to see which cards are incomplete. 

Perhaps I can make the parser also return notes, which do not have the separators, so the user knows which cards are "incomplete".

Or, we can treat cards without a separator as a new card type - i.e. more like a note, than a flashcard.

Thoughts? @AB1908 @st3v3nmw

**Comment by AB1908** [comment]
Hey Richard, these are pretty good ideas but I actually had some deeper thoughts on SRS and the ideas about context. I've been working on a separate plugin to actually address that as I'm finding it hard to help with this one. I have a flow in Figma as well. I think we should chat sometime as I'd really value your feedback.

**Comment by matterai** [comment]
Hey guys, 

Just fixed the problem mentioned in topic. Please, check this out. Hope it helps. Here is a little [PR](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/719).

**Comment by 4Source** [comment]
@ronzulu this should be fixed, may you could close it

**Comment by ronzulu** [comment]
Agreed, closing this now.
