### ISSUE TITLE
[BUG] iOS broken layout

### ISSUE THREAD

**Issue by AndrewPetrov** [st3v3nmw/obsidian-spaced-repetition#694]
**Describe the bug**
I have a broken layout in iOS device

**To Reproduce**
just tap on plugin button

**Expected behavior**
Layout close to fullscreen

**Screenshots**
Look at the attouchment

**Versions (please complete the following information):**

-   OS: iOS 16.5
-   Obsidian version: 1.4.6 (105)
-   Plugin version: 1.10.1 
-   iPhone 13 Pro

**Additional context**
Plugin works fine on MacOS and Android
![IMG_6745](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13622708/17e1818f-1866-4a59-91f8-369ca213be02)
![IMG_28DAD0FA0408-1](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13622708/a88d0ada-35f4-49ba-99c1-78d8750a9bca)

**Comment by AB1908** [comment]
Have you updated the height and width settings?

**Comment by AndrewPetrov** [comment]
Thank you, it helped
