### ISSUE TITLE
Avoid YAML attribute clash

### ISSUE THREAD

**Issue by whitenoisedev** [st3v3nmw/obsidian-spaced-repetition#7]
Hi,

We really like your plugin, but we are afraid some of the YAML attributes you chose are too common and might clash with other plugins.
Would you mind changing your attributes so that they are more specific to your plugin.
You could pretend a namespace, such as
due -> sr-due:
interval -> sr-interval:
ease -> sr-ease:

Thanks!

**Comment by st3v3nmw** [comment]
Hello, I'll fix that in a few.

**Comment by st3v3nmw** [comment]
This should be fixed in the latest release & PR #8.
