### ISSUE TITLE
[BUG] Decrease in Card Count after Pressing 'Reset'

### ISSUE THREAD

**Issue by Bluemoondragon07** [st3v3nmw/obsidian-spaced-repetition#704]
**Describe the bug**
I'm not sure if this is a bug or if it is intentional, but when you are going through the flashcards in a deck and you press "reset", the number of flashcards remaining goes down like it does for any other card. 

It's not a big problem, but the fact that 'reset' is pressed means that the card will show up again; therefore, the count should remain the same instead of going down. This bug (if it is a bug) causes the 'cards remaining' count to eventually go down into the negatives, leading to confusion for the user as to how many cards they actually have left.

**To Reproduce**

1. Open a deck to study
2. Reset a few cards
    3. Notice that the count goes down when you do this.
4. Continue to go through the flashcards in the deck.
5. You will see the number eventually reach the negative, and you will not be able to see the real number of cards left in the deck.

**Expected behavior**
When a card is reset, it remains in the deck, like Anki's **Again** button. Therefore, the count should not be affected.

**Screenshots**
![Screenshot 2023-07-06 164914](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/121056178/2c3f617a-e433-43ff-ad8a-01a724ecf7fa)

This is what I mean by 'Flashcard Count'.

**Versions (please complete the following information):**

-   OS: Windows 11
-   Obsidian version: v1.3.5
-   Plugin version: 1.10.1
-   If on desktop, Installer version: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.1.16 Chrome/106.0.5249.199 Electron/21.4.1 Safari/537.36'

**Comment by ronzulu** [comment]
Hi  @Bluemoondragon07 

This has been fixed in the newly released 1.10.2

Please upgrade and check.

Cheers
Ronny

**Comment by st3v3nmw** [comment]
Closing
