### ISSUE TITLE
[FEAT]Please support the Enter key on the numeric keypad in the shortcuts, making it more convenient for one-handed operation.

### ISSUE THREAD

**Issue by NoviceNi** [st3v3nmw/obsidian-spaced-repetition#706]
Please support the Enter key on the numeric keypad in the shortcuts, making it more convenient for one-handed operation.

**Comment by ronzulu** [comment]
Hi @NoviceNi 

This has been fixed in the latest release 1.10.2.

Please update to the latest version of the plug-in, and if all good, close off this issue report.

Cheers
Ronny

**Comment by ronzulu** [comment]
Hi @st3v3nmw I was hoping that the OP would test and close this issue, but he/she/they haven't.

Could you please close this instead.

Cheers
Ronny

**Comment by ronzulu** [comment]
> Hi @st3v3nmw I was hoping that the OP would test and close this issue, but he/she/they haven't.
> 
> Could you please close this instead.
> 
> Cheers Ronny

Hey Stephen, are you able to close this? Thanks.

**Comment by st3v3nmw** [comment]
Closed @ronzulu, sorry I missed this earlier
