### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dsouza-astro** [st3v3nmw/obsidian-spaced-repetition#707]
**Describe the bug**
The flashcards cannot be opened. New flashcards can be created or removed and the flashcard counter reacts appropriately, but the cards themselves cannot be opened. 

**To Reproduce**

1. Go to 'flashcard' icon
2. Decks pop up 
3. unable to open the flashcards even after clicking multiple times.

**Expected behavior**
I expect the flashcard to open when I click it. The number of flashcard increases when I add a new flashcard, but unable to open it.

**Screenshots**
<img width="397" alt="Screenshot 2023-07-15 at 14 38 01" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/138887618/3ca3c197-2ffd-4e61-9aeb-de74b55e2a9e">

**Versions (please complete the following information):**

-   OS: Mac OS Ventura. v13.4.1
-   Obsidian version: v1.3.5 (Installer 1.3.5)
-   Plugin version: v1.10.1

**Additional context**
The plugin was tested on my phone and the flashcards can be opened and the response to the flashcard is also saved successfully.

**Comment by EroyalBoy** [comment]
i have also met this issue!

**Comment by dsouza-astro** [comment]
Issue has been resolved. Instead of clicking the counter, if you click "flashcards". The cards will open.
