### ISSUE TITLE
[BUG] Cannot Click on the Deck

### ISSUE THREAD

**Issue by Jls0948** [st3v3nmw/obsidian-spaced-repetition#709]
I have noticed that after I  finish going through a deck, I can't click on the deck again to go back through. I have to exit out of the plugin and reload it. It is the same on my Macbook and iPhone. It seems to be a bug.

**Comment by tangxinxu** [comment]
I have encountered the same issue, unable to click on the deck to access the cards.

https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/41268511/befec5f0-aa6b-477a-a60a-aebb75111548

**Comment by Benjamin-Lyon** [comment]
I'm also unable to click on the deck. Updating Obisdian to version 1.4.5 seems to have caused this issue.

**Comment by Dima2014** [comment]
I found that it is only possible to open a deck by clicking right on the deck title, not on the free space of the row.
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/2078904/f9ab92c9-d85b-4a94-82ca-91bf78f1571c)

**Comment by manthonygfp** [comment]
https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/5498095/b6847c04-3f8c-48e6-b9d3-579291d98dfc

I'm having issues even when clicking directly on the text like @Dima2014 mentioned. My Obsidian version is `1.4.5`. My plugin version is `1.10.1`.

**Comment by NishantTharani** [comment]
@manthonygfp FWIW I am on Obsidian 1.4.13 and I can review by clicking directly on the text, thanks @Dima2014 for the tip. Still think this is a bug that should be addressed though.

**Comment by its-monotype** [comment]
The deck wasn't opening until I clicked on the text. Thanks for the tip, I hope this will be improved for better user experience

**Comment by dmatt** [comment]
Also experienced this problem in Version 1.4.14 (Installer 1.4.14) and I didn't think to click the text because the entire box around the deck row element highlights, so I was clicking that empty space. Version 1.4.14 (Installer 1.4.14).

**Comment by ronzulu** [comment]
Hi @Jls0948 

This has been fixed in the latest release 1.10.2.

Please update to the latest version of the plug-in, and if all good, close off this issue report.

Cheers
Ronny

**Comment by NishantTharani** [comment]
Thanks! I'm not the original reporter of the issue, but updating to the latest release does fix the bug for me.
