### ISSUE TITLE
Preference that clicking on links in documentation would open target page in a new tab

### ISSUE THREAD

**Issue by jimpfaff** [st3v3nmw/obsidian-spaced-repetition#712]
I have been reviewing your wiki document at https://www.stephenmwangi.com/obsidian-spaced-repetition/. This became frustrating.

Would you please update the document with a _blank tag in the html? I click on a link and then end up closing the tab in my browser instead of hitting the back button. I believe most people have this habit because most web pages open a new tab on links.

Maybe I'm the only one and this doesn't matter. But it did become a hassle for me when reviewing your documentation. And I suspect many others had the same problem. IMHO.

**Comment by ronzulu** [comment]
Hi @jimpfaff 

If we classify links in terms of internal to the web site and those that are external then we have:

(1), (2) are internal
(3), (4), (5) are to GitHub and could be classified as external

Are you suggesting that external links should be opened in a separate tab?

Out of curiosity, please send through a link to a web site that behaves as you suggest. I just tried Wikipedia and all links (both internal and external) don't open a new tab.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/dcc83729-1443-4ca1-ac79-8bf3c5b9b2d3)


Cheers
Ronny

**Comment by ronzulu** [comment]
We haven't heard back from you, and no one else has reported this issue.

I'll close this now, but feel free to reopen if this is still an issue.

Cheers
Ronny
