### ISSUE TITLE
[FEAT]: parent flashcard tags include all child flashcard tags

### ISSUE THREAD

**Issue by SiliasGH** [st3v3nmw/obsidian-spaced-repetition#727]
In the settings dialog flashcard tags, I have to insert all my different kind of flashcard tags, which - each of them - represent one flashcard deck.

All of my decks are tagged with the parent tag #flashcards/ (for example my work flashcards are tagged #flashcards/work, my flashcards concerning health-issues are tagged #flashcards/health and so on)

=> it would be nice, if I just could insert here "#flashcards/" once and automatically all related child-tags are concidered as own decks and I don't had to insert all different kind of child-tags.

**Comment by ronzulu** [comment]
Hi

Can you please explain more.

In the settings I only have `#flashcards` specified.

In my notes I have all kinds of tags, e.g.  `#flashcards/science/physics` and  `#flashcards/ml`. They are all recognized by OSR.

Are you saying that doesn't work for you?

Regards
Ronny

**Comment by ronzulu** [comment]
Hi @SiliasGH 

We haven't heard back from you, and I can't reproduce the issue.

I'll close this now, but feel free to reopen if this is still an issue.

Cheers
Ronny
