### ISSUE TITLE
[BUG] Plugin thinks flashcards are reviewed?

### ISSUE THREAD

**Issue by LennyPhoenix** [st3v3nmw/obsidian-spaced-repetition#734]
**Describe the bug**

Newly created flashcards are marked as reviewed by the plugin in some cases, meaning they will never turn up during review.

Example of affected flashcard:

```
What is Kepler's law?::$$T^2 \propto r^3$$
```

With workaround:

```
What is Kepler's law? :: $$T^2 \propto r^3$$
```

**To Reproduce**

Set the tag `#test` to be reviewed, then create the following file.

```md
---
aliases: []
tags: [test]
---

What is Kepler's law?::$$T^2 \propto r^3$$
```

Flashcard will be detected, but will be in the red group, meaning it can't ever be reviewed?

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/57148878/97c0b840-d8b7-4e4d-afc1-6ed5198baed3)

**Expected behavior**

Flashcard to show up in list:

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/57148878/6080178f-49d1-49a9-a4d8-88c652e99731)

**Versions (please complete the following information):**

-   OS: Windows 11
-   Obsidian version: v1.3.7
-   Plugin version: v1.10.1
-   If on desktop, Installer version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.0.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36

**Additional context**

Doesn't seem to apply for cramming for some reason.

**Comment by LennyPhoenix** [comment]
Whoops, got a little trigger-happy on the Ctrl+Enter there, Issue description should be complete now.

**Comment by ronzulu** [comment]
Hi @LennyPhoenix 

A lot of the flashcard code has been reworked in the newly released version 1.10.2

I couldn't reproduce the problem, could you please try again and let us know.

Cheers
Ronny

**Comment by LennyPhoenix** [comment]
I believe the issue is now solved following the recent update, I can't seem to replicate it right now but I will reopen if I encounter it again.

Thanks!

**Comment by ronzulu** [comment]
Sounds good 👍
