### ISSUE TITLE
Does not work on Android smartphone

### ISSUE THREAD

**Issue by foegra** [st3v3nmw/obsidian-spaced-repetition#742]
On Android smartphone calling the plugin - opens it in tiny window which essentially makes it unusable on the phone

**Comment by visaeryon** [comment]
you can change the height and width percentage of the flashcard in settings to 100%

here
![Screenshot (70)](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/70768824/413ab5fd-fa7e-4741-a995-ab0fc8087ca6)
