### ISSUE TITLE
[BUG] Revisons cannot be saved properly

### ISSUE THREAD

**Issue by tk166** [st3v3nmw/obsidian-spaced-repetition#745]
**Describe the bug**
If revise a multiline card when do space repetitions, The New revised contents will not be at the desired locations but will be place after the meta data.

**To Reproduce**

1. Create a multiline card (with self defined separator `++`)
2. Review the card in space repetition.
3. Revise the card by the revision button on the card and save.
4. Find that the revisions won't work.

**Expected behavior**
Revisions are expected to be saved properly.

**Screenshots**
Revision example
![p1](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/96829271/7e1676a0-585e-491d-bde4-1d3eed24372f)
Improper revision reult example
![p2](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/96829271/cea7794b-6ca0-4cc1-973d-fac742803fb8)

**Versions (please complete the following information):**

-   OS: Windows10 & Linux Mint 20.04
-   Obsidian version: v1.4.13
-   Plugin version: 1.10.1

**Additional context**
Self defined separator was set `++` and `+++` to make it easy to type these marks without switching the input methods between English and Simplified Chinese frequently, because different question marks (`?` and `？`) or other marks are adopted in them.

**Comment by ronzulu** [comment]
Hello

And just checking, before the card was edited, it started off as:

```
Test Card
++
Answer 1
```

**Comment by tk166** [comment]
> Hello
> 
> And just checking, before the card was edited, it started off as:
> 
> ```
> Test Card
> ++
> Answer 1
> ```

Yes, That's the original card

**Comment by ronzulu** [comment]
Hi

This has been fixed in a Beta release at:
https://github.com/ronzulu/obsidian-spaced-repetition/releases/tag/1.11.0-beta.0

If you would like to use it, you would need to manually download a couple of files as described in the release note.

Cheers
Ronny

**Comment by tk166** [comment]
Thanks for your hard work and the fixes works well.

**Comment by ronzulu** [comment]
Great, thanks for letting me know.

**Comment by ronzulu** [comment]
Hi  @tk166 

The fix for this has been included in the latest release 1.10.2.

Please update to the latest version of the plug-in, and if all good, close off this issue report.

Cheers
Ronny
