### ISSUE TITLE
[BUG] Bury Siblings Is Not Honored

### ISSUE THREAD

**Issue by LennyPhoenix** [st3v3nmw/obsidian-spaced-repetition#759]
It appears that since the recent flashcards code overhaul, the option to "Bury sibling cards until the next day" is no longer obeyed.

## To Reproduce

Enable the "bury siblings" option.

Add the tag `#test` to the flashcards tag list.

Create the following note:

```md
---
aliases: 
tags: test
---

# Test

The first answer is ==cloze 1==, the second answer is ==cloze 2==.
```

Review the `#test` deck, and note that both flashcards appear.

## Expected behavior

Only one flashcard from the pair should appear at any given day, according to the setting.

This was the behaviour before the overhaul.

## Screenshots

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/57148878/99afa949-d764-4fd8-b2cc-7f7b14b10d67)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/57148878/310f22b4-60ee-4687-87dc-87b1a26a7cf3)

## Version Details

-  OS: Bedrock (Arch) Linux
-  Obsidian version: v1.4.14
-  Plugin version: v1.10.2
-  Installer version: '5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.14 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36'

**Comment by LennyPhoenix** [comment]
CC @ronzulu

**Comment by nayyala** [comment]
Am running into this same exact issue. Honestly I wish I hadn't updated, I was happier with the previous release

**Comment by nayyala** [comment]
@LennyPhoenix Use the main.js file from 1.10.1, that fixes the issues temporarily for me. You may run into some flashcards you might have to reset though because i think the data is encoded differently, resulting in 23 year intervals 😆

**Comment by LennyPhoenix** [comment]
I prefer the newer update as it fixes some other problems with the flashcards system that I found far more problematic than this. This is really only a minor inconvenience to me so it's not worth downgrading in my case.

**Comment by ronzulu** [comment]
Oops, sorry... thanks for reporting. I'll fix ASAP.

Cheers
Ronny

**Comment by LennyPhoenix** [comment]
Apologies, I've probably not explained that super well

**Comment by ronzulu** [comment]
> Without randomisation: if the first card is reviewed, but the interval never increases to above a day then yes it will keep appearing, however this is intended behaviour. The next sibling card should only be shown once the original card's interval allows for it.

Thanks, that's really helpful. I've made the code changes, will write some new test cases, then publish to my branch. Will you be able to check before I put in a PR?

**Comment by ronzulu** [comment]
It seems that the setting "Bury sibling cards until the next day" could be better described.

It's written from the perspective of what the code is doing, not from the user's perspective.

I would suggest "**Maximum one sibling card per day**" would be easier for users to understand.

Also "... until the next day" does not seem totally accurate. Some sibling cards may not be shown the following day.

Feedback appreciated to help ensure I'm on the right track @LennyPhoenix @st3v3nmw

**Comment by LennyPhoenix** [comment]
Just tried testing with [your changes](https://github.com/ronzulu/obsidian-spaced-repetition/tree/enhanced-card-ordering), I'm getting some errors when attempting to load the plugin:

```
app.js:1 Obsidian Developer Console
node:electron/js2c/renderer_init:2 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
warnAboutInsecureCSP @ node:electron/js2c/renderer_init:2
logSecurityWarnings @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
load (async)
securityWarnings @ node:electron/js2c/renderer_init:2
./lib/renderer/common-init.ts @ node:electron/js2c/renderer_init:2
__webpack_require__ @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
___electron_webpack_init__ @ node:electron/js2c/renderer_init:2
(anonymous) @ node:electron/js2c/renderer_init:2
compileForInternalLoader @ node:internal/bootstrap/loaders:334
compileForPublicLoader @ node:internal/bootstrap/loaders:270
loadBuiltinModule @ node:internal/modules/cjs/helpers:56
Module._load @ node:internal/modules/cjs/loader:941
f._load @ node:electron/js2c/asar_bundle:2
executeUserEntryPoint @ node:internal/modules/run_main:96
(anonymous) @ node:internal/main/run_main_module:23
plugin:obsidian-spaced-repetition:21518 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'settings')
    at _SRPlugin.loadPluginData (plugin:obsidian-spaced-repetition:21518:32)
    at async _SRPlugin.onload (plugin:obsidian-spaced-repetition:21027:5)
loadPluginData @ plugin:obsidian-spaced-repetition:21518
await in loadPluginData (async)
e.load @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.loadPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.initialize @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.initializeWithAdapter @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1

```

**Comment by ronzulu** [comment]
Actually, I haven't finished testing or published the branch to GitHub yet. It's a different one to the one you tried.

I'll let you know when ready.

Did you have any feedback regarding my comments from earlier today (or last night depending where you are)

Thx

**Comment by LennyPhoenix** [comment]
The name change sounds fine, I'm not too fussed about the naming of things as long as it does what it needs to :)

**Comment by ronzulu** [comment]
Yes, if it's a choice between nice words or working functionality, functionality wins

I've published the fix at:
https://github.com/ronzulu/obsidian-spaced-repetition/tree/bug-bury-sibling-759-760

Cheers
Ronny

**Comment by LennyPhoenix** [comment]
Just tested it and it seems to work how it should, thank you!

**Comment by ronzulu** [comment]
hey @LennyPhoenix the fix has been included in the latest update 1.10.4

When you get a chance would you please verify and close the issue if all ok.

Cheers
Ronny

**Comment by LennyPhoenix** [comment]
I'll test over the next couple days and report back accordingly :+1:

**Comment by LennyPhoenix** [comment]
Seems to be working fine, will reopen if any further problems are encountered.

Thanks for your work!
