### ISSUE TITLE
Cloze and remnote notes conflict with code blocks

### ISSUE THREAD

**Issue by OliverBalfour** [st3v3nmw/obsidian-spaced-repetition#76]
First things first, this is an *awesome* plugin, thank you for making this!

I've just spent a little time testing and found the following issue. If I have a code block like the following two:

```py
a == b && b == c
```
```cpp
std::vector x{};
```
The plugin will detect the first as a Cloze task and the second as a remnote one, and has weird prompts when you open the flashcard review screen. I think anything inside code blocks should be ignored if possible (but being able to put code blocks after a multiline `?` prompt is great)

**Comment by st3v3nmw** [comment]
Hello, I'm glad that you like the plugin!

I'll work on fixing this.

Thanks for the bug report.

**Comment by OliverBalfour** [comment]
Thanks!

One other issue I've just noticed: if I have a note like

~~~
How do you create a computed property in Python?
?
```
one line

another line
```
~~~

then it gets changed to


~~~
How do you create a computed property in Python?
?
```
one line
<!--SR:2021-05-20,4,270-->

another line
```
~~~

Perhaps the multiline notes should ignore blank lines if they're in the middle of a code block? This isn't a huge problem as I can add some spaces to the blank line to make the plugin skip that line

**Comment by Masstronaut** [comment]
On version 1.5.2 I'm still seeing the issue @OliverBalfour mentioned in code blocks with blank lines. Adding spaces works, but it would definitely be preferable to have the entire code block be treated as a single block for review.

I tested with having a block reference `^likethis` immediately after a code block. That worked great:
1. The block reference wasn't included in the card
2. The SR HTML comment was inserted after the block reference, so it won't break any block references I have to that code block.

**Comment by st3v3nmw** [comment]
@Masstronaut, I only did a partial fix for this issue so the blank lines bit is still pending. Changing the regex to accommodate this got a little too complicated so I decided to fix other things first.

**Comment by st3v3nmw** [comment]
I'll create a new issue for the blank lines bit & close this one.
