### ISSUE TITLE
[BUG] Skipping a card seems to permanently bury it and make it impossible to review again in the same day

### ISSUE THREAD

**Issue by nayyala** [st3v3nmw/obsidian-spaced-repetition#760]
I have some flashcards I was using to test out the update. Turns out skipping a card is resulting in the cards being buried and being inaccessible after the fact. I cannot even pull them up for review after this by manually trying to review them from the note

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/8975517/e822aa8d-82e1-48e4-b3ca-973f740959fd)

**Comment by ronzulu** [comment]
Oops, sorry... thanks for reporting. I'll fix ASAP.

Cheers
Ronny

**Comment by ronzulu** [comment]
Hi  @nayyala 

I've published the fix at:
https://github.com/ronzulu/obsidian-spaced-repetition/tree/bug-bury-sibling-759-760

Let me know if you aren't technically minded and I'll include the built product  `main.js `

**Comment by ronzulu** [comment]
Hi  @nayyala this has been fixed in the latest update 1.10.4

When you get a chance would you please verify and close the issue if all ok.

Cheers
Ronny

**Comment by nayyala** [comment]
Hi Ronny,

Thank you for the work. However, I am still waiting on some of the outstanding issues to be fixed in the new update before I move back up from 1.10.1, as some of them are bugs that greatly interrupt my workflow.

**Comment by ronzulu** [comment]
> Hi Ronny,
> 
> Thank you for the work. However, I am still waiting on some of the outstanding issues to be fixed in the new update before I move back up from 1.10.1, as some of them are bugs that greatly interrupt my workflow.

Hi @nayyala I think from one of your other posts, you have upgraded to a newer version where this has been fixed.

If this is so, please close this issue.

Cheers
Ronny
