### ISSUE TITLE
[BUG] Minor UI issues with the flashcard review modal

### ISSUE THREAD

**Issue by 1-yan** [st3v3nmw/obsidian-spaced-repetition#773]
**Describe the bug**
When opening the decks, there is some overlap between the text and the title above the page. Also, in the current version, there is an abnormal margin at the bottom of the page in full-screen mode.
![IMG_0137](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/104848108/63e0121e-5dec-453b-8a03-fb09cd87bb47)

**Comment by ronzulu** [comment]
Hi @1-yan 

> Also, in the current version, there is an abnormal margin at the bottom of the page in full-screen mode.

Do you mean that you are expecting the bottom of the area labeled (1) should be positioned at (2)?

Is there any significance to the white area labeled (3)

Please also let us know what device you are using, and the version of the spaced repetition plug-in.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/37147152-1f4c-40bb-b75b-75fbe7b26b78)

Also, send through a screenshot of your settings for:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/baf2d4df-7ea6-45e1-995e-18806db5e68e)

Cheers
Ronny

**Comment by ronzulu** [comment]
We haven't heard back from you, and no one else has reported this issue.

I'll close this now, but feel free to reopen if this is still an issue.

Cheers
Ronny
