### ISSUE TITLE
List style with numbers

### ISSUE THREAD

**Issue by mkschulze** [st3v3nmw/obsidian-spaced-repetition#78]
So I made this list here, one with bullet points and one with numbers.
Looks like the number style doesn't get recognized as a list correctly.

![Bildschirmfoto 2021-05-16 um 11 58 22](https://user-images.githubusercontent.com/3390820/118393182-069b4a00-b63e-11eb-9c59-5748143b3bde.png)

![Bildschirmfoto 2021-05-16 um 11 57 22](https://user-images.githubusercontent.com/3390820/118393187-0c912b00-b63e-11eb-914d-125b0d54f2af.png)

**Comment by st3v3nmw** [comment]
Hello,
Could you please post the markdown you're using here? I'm not able to reproduce this.
Thanks for the bug report!

**Comment by mkschulze** [comment]
```markdown
---
tags: Umsatzsteuer
cards-deck: Umsatzsteuer::Schemata <!--SR:2021-05-19,3,250-->
---
# Lösungsschema USt 

## 1. Allgemeines
### 1.1 Klausuraufbau 
?
1. Vorspann
	- Unternehmereigenschaft
	- Rahmen des Unternehmens
	- Besteuerungsform (Regelbesteuerung oder Kleinunternehmer)
	- Besteuerungsart (Soll- oder Ist-besteuerung)
	- maßgeblicher Voranmeldezeitraum
	
2. Hauptteil
	1. Teilbereich
		1. Ausgangsumsätze
		2. Eingangsumsätze + Vorsteuerberichtigung
	2. Teilbereich
		1. Innergemeinschaftlicher Erwerb
		2. Vorsteuerabzug der "Erwerbsteuer"
	3. Teilbereich
		1. Einfuhr im Inland
		2. Vorsteuerabzug der EUSt
#fcard
```

**Comment by st3v3nmw** [comment]
After some testing, it looks like that #fcard line is causing the problem. Could you move it to the top, maybe in the frontmatter even since the tags are note-level? This makes it render properly on my end.

**Comment by mkschulze** [comment]
Ah nice, thank you! Yes, now it works. I deinstalled that plugin already, just cleaning my cards now to switch over to your plugin completely.

**Comment by mkschulze** [comment]
The issue can be closed then I guess. thx
