### ISSUE TITLE
[BUG] critical Flashcards issue (editing while reviewing flashcard)

### ISSUE THREAD

**Issue by Ankharna** [st3v3nmw/obsidian-spaced-repetition#783]
**Describe the bug**
Flashcard`s edit feature replaces a good chunk of text with "undefined".

**To Reproduce**

    precondition: option "Convert ==highlights== to clozes?" is checked
(i dont know if the error occurs with other options: **bold** or {{curly}})

1. have something marked with highlighter "==text=="
2. review flashcards
3. click "edit flashcard"- button
4. dont change anything (abort editing)
5. some text below or in the highlight gets replaced with "undefined" (you can see the "undefined" popping up if you have the right note open at the right place in the background of review window)
6. you CANT "undo" this action like you can if you change text yourself
7. text is lost and maybe you didnt even notice

**Expected behavior**
some text (the highlight or something after the highlight) gets irreversibly changed to "undefined"

**Versions:**

-   OS: win10
-   Obsidian version: 1.4.16
-   Plugin version: 1.10.4
-   If on desktop, Installer version: 
'5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36'

**Additional context**
==example text== and this text here
and here
and here
(and this too): will be deleted (replaced) to the very bottom of the note. so if youre unlucky the whole note gets irreversibly "replaced" and only text above the highlighted text remains

**Comment by ronzulu** [comment]
Hi @Ankharna, I could reproduce after clicking "save" but not "cancel"

In any case, I should be able to fix in the next day so, would be great is you could then Beta test before I request that @st3v3nmw  merges into the main branch.

Cheers
Ronny

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/971ed38f-c0fb-4971-925e-9258a3eaa477)

**Comment by Ankharna** [comment]
@ronzulu 
Sure will do!

**Comment by ronzulu** [comment]
@Ankharna, I think I've fixed this, but am not 100% sure.

I could only get the problem to happen intermittently (before the fix), hence my lack of confidence.

Anyway if you could please try the following:
[main.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13279141/main.zip)

Copy the `main.js` to the plug-in subfolder of your vault `Your-Vault\.obsidian\plugins\obsidian-spaced-repetition`. You will need to reload the plug-in (or restart obsidian) for it to take effect.

Cheers
Ronny

**Comment by Ankharna** [comment]
@ronzulu

hey, i tried it with hightlight, bold and curlies. the issue seems to be fixed!!

good stuff, thank you!

i created a test vault for this, but i copied .obsidian folder and applied your fixed file.

i didnt expect to receive a solution so fast :)

**Comment by ronzulu** [comment]
Glad the fix worked 😄 I've put in a merge request so that it can be included in the next release.

Cheers
Ronny
