### ISSUE TITLE
''Invalid Date'' instead of the actual date

### ISSUE THREAD

**Issue by gleboleinik** [st3v3nmw/obsidian-spaced-repetition#787]
When I choose the ''Review: Good" option, and the note is scheduled to revise on a specific date, instead of this date i only see a heading saying ''Invalid date'', so I can't actually understand when I'll have to revise that note.

OS: Windows 10

Obsidian version: v. 1.4.16

Plugin version: 1.10.3.

![изображение_2023-11-10_173621264](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/150454326/bdad372e-c099-4654-bfbf-39c749e8327d)

**Comment by MrStafeev** [comment]
+1 
Same problem with "Review: Easy". "Review: Hard" puts right date but shows incorrect period for the next review.
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/96488127/ae165756-0112-4c20-aad6-095171a0e22e)

**Comment by MrStafeev** [comment]
I've found the root the problem: if there is link to not .md file that is in your vault (tested with .pdf or .png), it will show invalid date (but only with "Review: Easy" and "Review: Good".

**Comment by gleboleinik** [comment]
> I've found the root the problem: if there is link to not .md file that is in your vault (tested with .pdf or .png), it will show invalid date (but only with "Review: Easy" and "Review: Good".

Yes, same here.

**Comment by gleboleinik** [comment]
> I've found the root the problem: if there is link to not .md file that is in your vault (tested with .pdf or .png), it will show invalid date (but only with "Review: Easy" and "Review: Good".

Yes, same here.

**Comment by ronzulu** [comment]
Hi all

This appears to be the same problem as #764.

There is a patch for that at:
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/764#issuecomment-1788890836

If you are able to try that patch, and report back.

Otherwise, you will need to wait until https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/782 has been incorporated into the next release.

Cheers
Ronny

**Comment by GulTion** [comment]
> When I choose the ''Review: Good" option, and the note is scheduled to revise on a specific date, instead of this date i only see a heading saying ''Invalid date'', so I can't actually understand when I'll have to revise that note.
> 
> OS: Windows 10
> 
> Obsidian version: v. 1.4.16
> 
> Plugin version: 1.10.3.
> 
> ![изображение_2023-11-10_173621264](https://user-images.githubusercontent.com/150454326/282088443-bdad372e-c099-4654-bfbf-39c749e8327d.png)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/44129143/4fdf4f10-384b-4f64-b6ec-8b11b5ffc68a)
same here +1, pls fix asap

**Comment by MrStafeev** [comment]
> There is a patch for that at: [#764 (comment)](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/764#issuecomment-1788890836)
> 
> If you are able to try that patch, and report back.

Seems to work perfectly! Thank you very much!

**Comment by ronzulu** [comment]
Hi  @gleboleinik 

The fix for this has been included in the latest release 1.10.5.

Please upgrade, confirm the fix and close this issue.

Ronny

**Comment by gleboleinik** [comment]
> Hi @gleboleinik
> 
> The fix for this has been included in the latest release 1.10.5.
> 
> Please upgrade, confirm the fix and close this issue.
> 
> Ronny

It works just fine. Thank you!
