### ISSUE TITLE
Bug or not, missing feature

### ISSUE THREAD

**Issue by aswds2011** [st3v3nmw/obsidian-spaced-repetition#792]
I think there is a missing feature called "Show file name instead of 'Edit Later" in flashcard review?"
I am not sure if its a bug or it was removed for a reason.

As of latest version of Space repetition v1.10.5

**Comment by ronzulu** [comment]
Hi @aswds2011 is this the same as #786 or different?

**Comment by ronzulu** [comment]
Hi @aswds2011 without further info from you, I'll assume this is the same as #786, and close this now.

If you were after something else, please feel free to reopen the issue.

Cheers
Ronny
