### ISSUE TITLE
[BUG] cloze deletions in tables have no color making it troublesome to find when table is large

### ISSUE THREAD

**Issue by VerAn1015** [st3v3nmw/obsidian-spaced-repetition#795]
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/148541981/669ecc2b-b09d-43ff-ac5f-cdfc8bbbebb9)

**Comment by ronzulu** [comment]
Hi @VerAn1015 

I think you'll need to give more explanation about the issue, it's not immediately obvious what you would like to see.

Please include the raw Markdown (e.g. attach a file to your post)

Explain what you are wanting to see for each item in your screenshot:

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/2ffabfe2-936a-4343-8aeb-4196956eb35a)

Cheers
Ronny

**Comment by VerAn1015** [comment]
It seems to be that the issue of clozes in tables being color black and not blue only exists with Sheets Extended plugin enabled.
