### ISSUE TITLE
Language Mixup [BUG]

### ISSUE THREAD

**Issue by jharst** [st3v3nmw/obsidian-spaced-repetition#803]
**Describe the bug**
Ever since the last update, the plugin uses both German and English in its user interface (settings, commands). The System Language on my Computer and in Obsidian is English.

**To Reproduce**
I don't know if this is reproducible. When I open the plugin's settings, the language used is partly German, partly English. The commands used in the command palette are in German.

**Expected behavior**
I would expect the plugin to use the system language and it has done so in earlier versions.

**Screenshots**
<img width="1439" alt="Screenshot 2023-12-03 13-27-28" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/122213379/bbcba2d2-8162-456f-ab0d-330bce2ae06e">

**Versions (please complete the following information):**
-   OS: macOS Ventura
-   Obsidian version: 1.5.1
-   Plugin version: 1.10.5
-   If on desktop, Installer version: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.13 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36

**Comment by ronzulu** [comment]
Hi @jharst  just wondering if this issue still persists.

If so, I'll send through a version of the plug-in with some debug output.

Cheers
Ronny

**Comment by jharst** [comment]
Hi Ronny,

Thanks for getting back to me! No, the problem isn't there anymore, but I remember it coming back when I had to reinstall the plugin once. Everything works fine now though.

Thanks again,
jharst

**Comment by ronzulu** [comment]
Hello again

In that case I'll close this now, but feel free to reopen is the problem happens again.

Curious, do you sometimes run Obsidian with the language specified as German? Or the language selected for the system sometimes is German?

Cheers
Ronny

----

Thoughts about possible cause. 

The language used by the plug-in is based on a call to the Obsidian function `moment.locale()`.

This is retrieved by the code in `helper.ts ` within:
``` typescript
const locale = localeMap[moment.locale()];
```

Presumably this would execute early on in the plug-in load process. Is it possible that `moment.locale()` shouldn't be called at this time?

Could be worth calling this later in the plug-in load process, i.e. the first time the locale is actually need.

**Comment by jharst** [comment]
Hi Ronny,

Thanks again for reaching out to me! No, I never run Obsidian or the system with German as primary language. But your notes got me thinking: I have a note with a dataview script in which I call `moment.locale(de)`– do you think this might be the reason or the mixup? 

Cheers,
Joachim

**Comment by ronzulu** [comment]
Hi Joachim

I think that is a very strong possibility.

That call to `moment.locale` with a parameter sets the global locale of the "moment" library. This would then be returned when the OSR plug-in calls `moment.locale()` without any parameters.

I think we have gotten to the underlying reason :smile:
