### ISSUE TITLE
[BUG] HTML review comment deactivates block identifier

### ISSUE THREAD

**Issue by sebthoms** [st3v3nmw/obsidian-spaced-repetition#815]
Thanks a lot for creating this plugin, @st3v3nmw! It has been extremely useful for me.
There is just a small issue when creating flashcards from linked blocks.

**Describe the bug**
Whenever a HTML review comment is added to a flashcard containting a block identifier, the block identifier gets deactivated. This results in the other file being unable to locate that block.

<img width="164" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/154070933/928eec97-cd50-4e38-a7e6-3fc47f39af37">

becomes this:

<img width="386" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/154070933/2808a64c-5d00-4194-a413-512f34a7b3cb">

(I should probably add that I configured ">>" to be my flashcard identifier)

Adding the HTML comment on a new line solves this, but this unfortunately breaks list formatting in other flashcards.

Any help is appreciated!

**Comment by ronzulu** [comment]
For anyone looking to fix this...

From experimenting, it seems that the block identifier must be right at the end of the line.

If there is anything after the block identifier before the EOL, obsidian won't recognize it as the block identifier.

I think this can be fixed without adding a new user setting. I can't think of a reason why someone would want the current formatting. The following shows where the OSR info should be placed:

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/3bb29296-2c24-41f6-8a92-3af5a4955c73)

Cheers
Ronny

**Comment by ronzulu** [comment]
I'll try and fix this over the next week. Unless someone else is busting to do it :-)

**Comment by ronzulu** [comment]
Hi @sebthoms and anyone else reading...

Beta release is now available.

There is a file called `main.js` in this zip file
[main_815A.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13971784/main_815A.zip)


You will need to copy that to the obsidian plug-in folder, e.g.
`D:\Obsidian\Obsidian\.obsidian\plugins\obsidian-spaced-repetition`

Then reload the plug-in, or restart obsidian. 

Any feedback appreciated.

Ronny

**Comment by sebthoms** [comment]
It works perfectly now.

Thanks a lot!
