### ISSUE TITLE
YouTube Embeds with specified timestamps no longer being obeyed after updating [BUG]

### ISSUE THREAD

**Issue by nayyala** [st3v3nmw/obsidian-spaced-repetition#817]
**Describe the bug**
YouTube timestamps in iframe embeds from flashcards are completely ignored. It jumps to the timestamp and then completely switches elsewhere

**To Reproduce**

Try making a flashcard with the following embed:

<iframe width="560" height="315" src="https://www.youtube.com/embed/Lg5P2w_Ro1c?start=1135&end=1147&autoplay=0&random=1234" frameborder="0" autoplay="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>

It will not start at the desired timestamp. It almost gets there, but immediately jumps elsewhere. If you have never seen the video before, maybe it will but after a handful of times, try jumping to another part and then watch it disobey.

**Expected behavior**
As in the previous versions, I was able to have a youtube video within an iframe load at a the specified timestamp and finish at the specified end stamp. However, the video simply begins from the last point it was accessed completely ignoring it.

**Screenshots**
If applicable, add screenshots to help explain the bug. This could be the logs in the developer console (`CTRL` + `SHIFT` + `i`).

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/8975517/6f424b7a-c129-4c38-9162-271e8726cae8)

**Versions (please complete the following information):**

Spaced Repetition v 1.10.5
Obsidian 1.4.16

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by ronzulu** [comment]
Hi @nayyala, it would be helpful if you attach a  `.md` file that exhibits the problem.

Cheers
Ronny

**Comment by nayyala** [comment]
Hi @ronzulu 
Here you are

[Work Vault.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13719396/Work.Vault.md)

**Comment by nayyala** [comment]
Here it is:

[Work Vault.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13719405/Work.Vault.md)

**Comment by ronzulu** [comment]
I tried perhaps 10 times in total, but couldn't reproduce. I've tried:

Work.Vault->flashcard-> play clip-> cancel from modal
Work.Vault->flashcard-> play clip-> rate-> cancel from modal
Work.Vault->flashcard-> play clip-> cancel from modal-> view different note-> return to Work.Vault
Restart obsidian-> Work.Vault->flashcard-> play clip

What platform are you using?

During the https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/751 restructure, I didn't change any of the possibly related code, so unlikely I can assist with this one. e.g. I didn't change `renderMarkdownWrapper`, `embedMediaFile`

**Comment by ronzulu** [comment]
Was there any non-OSR plug-in system changes recently? If you temporarily revert to 1.10.1 does this work reliably?

**Comment by nayyala** [comment]
Well, it would appear that the issue is not related to the plugin at all. I have removed the plugin entirely and the issue persists. Something is going wrong with YouTube timestamps in the iframe embed. Apologies.

**Comment by ronzulu** [comment]
I did learn something from this... I never would have thought of embedding video within a question!
