### ISSUE TITLE
[BUG] Cramming does not review every card; it buries siblings, which does not match the intended functionality of cramming

### ISSUE THREAD

**Issue by nayyala** [st3v3nmw/obsidian-spaced-repetition#822]
Tried to cram a deck with multiple clozes on cards, and it buries all similar cards. This setting should be applied in normal reviews, but cramming should make it clear that the intent is to see every single card

**Comment by ronzulu** [comment]
Hi @nayyala 

I couldn't reproduce this. For example (with "bury sibling cards" enabled)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/0145594f-cb5a-4319-a60c-35263cadd1e4)

When I cram this deck, I see the following:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/7a6460fe-c1d3-4e6f-8820-7c1d2de03929)
After clicking easy...

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/b0307c6e-b531-43c4-851e-d754cc0758b1)
After clicking easy...

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/715f1948-16c4-4f1d-a3de-5a52624e7820)

Please detail the issue with screenshots and the precise sequence of GUI interactions.

Cheers
Ronny

**Comment by nayyala** [comment]
@ronzulu My apologies you are correct! I think it applies to cards that haven't been started yet and don't have the special dates added.

**Comment by ronzulu** [comment]
Actually, looking at the code, I think the problem you raise can occur.

But only when skipping cards during the review. Is that possibly what you encountered?
