### ISSUE TITLE
using command palette shortcut to review flashcards doesn't show any flashcards

### ISSUE THREAD

**Issue by bnjbvr** [st3v3nmw/obsidian-spaced-repetition#83]
Thanks for this plugin, I like it a lot :star_struck: 

I've noticed tonight that when I try to use the command palette and then select `Spaced Repetition: Review Flashcards`, then it opens the flashcards modal, but it fails to find any decks (nothing shows up). If I'm using the button the left menu bar, then the decks I'm using do show up.

Please let me know if you need additional information/logs!

**Comment by st3v3nmw** [comment]
Hello, I'm glad that you like the plugin!

The fix for this issue should be available in the next release.

**Comment by bnjbvr** [comment]
Thanks!
