### ISSUE TITLE
[BUG] Issues with trailing whitespace?

### ISSUE THREAD

**Issue by biocarl** [st3v3nmw/obsidian-spaced-repetition#833]
**Describe the bug**
When it is attempted to write a new review comment in the note it does not work if the question part has a trailing whitespace.
The console prints out a
```plaintext
[error] updateQuestionText: Text not found: SOMETEXT
```
- Code origin of the problem: When the new question/note text is generated in [updateQuestionText](https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/276041ab3d89627136ddb2dba432ce3412c30bff/src/Question.ts#L194) `noteText` and `originalText` are not the same  because the trailing whitespace of the question in originalText is stripped away, but this is not the case in `noteText`.

**To Reproduce**
When reviewing the following note, no review comment will be set and a `[error] updateQuestionText` will be generated.
- Note that after `#test` is a trailing whitespace
```plaintext
Some Filename
#review #test 
?
This is the answer
```

**Expected behavior**
The expected behavior is that the question part can contain a trailing whitespace since it is very easy to forget a whitespace. You've also mentioned whitespace handling in the comments [here](https://github.com/st3v3nmw/obsidian-spaced-repetition/blob/276041ab3d89627136ddb2dba432ce3412c30bff/src/Question.ts#L33), so I do not know if your format allows to be more flexible in that regard.

**Versions (please complete the following information):**
- On all platforms

**Comment by ronzulu** [comment]
Hi @biocarl thanks for letting us know.

what version of the plug-in are you using?

The code was made tolerant of trailing spaces recently, but perhaps there is still an issue.

I couldn't reproduce. I copied your example above with the trailing space:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/f7fbe608-0890-403c-8ce4-a207395923c5)

But after reviewing, the note is updated correctly:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/c4cadf5e-c129-4ebe-aa4d-e6f803c67b3d)

Cheers
Ronny

**Comment by biocarl** [comment]
Hey Ronny, thank you for your quick reply!

**More details**
- the `#review` tag is the flashcard tag
- This is comparing `noteText` with `originalText` (when processed by the `MultiLineTextFinder::findAndReplace` function)

```plaintext
[log] Character 1: 'S' and 'S' are equal 
[log] Character 2: 'o' and 'o' are equal 
[log] Character 3: 'm' and 'm' are equal 
[log] Character 4: 'e' and 'e' are equal 
[log] Character 5: ' ' and ' ' are equal 
[log] Character 6: 'F' and 'F' are equal 
[log] Character 7: 'i' and 'i' are equal 
[log] Character 8: 'l' and 'l' are equal 
[log] Character 9: 'e' and 'e' are equal 
[log] Character 10: 'n' and 'n' are equal 
[log] Character 11: 'a' and 'a' are equal 
[log] Character 12: 'm' and 'm' are equal 
[log] Character 13: 'e' and 'e' are equal 
[log] Character 14: '\n' and '\n' are equal 
[log] Character 15: '#' and '#' are equal 
[log] Character 16: 'r' and 'r' are equal 
[log] Character 17: 'e' and 'e' are equal 
[log] Character 18: 'v' and 'v' are equal 
[log] Character 19: 'i' and 'i' are equal 
[log] Character 20: 'e' and 'e' are equal 
[log] Character 21: 'w' and 'w' are equal 
[log] Character 22: ' ' and ' ' are equal 
[log] Character 23: '#' and '#' are equal 
[log] Character 24: 't' and 't' are equal 
[log] Character 25: 'e' and 'e' are equal 
[log] Character 26: 's' and 's' are equal 
[log] Character 27: 't' and 't' are equal 
[log] Character 28: ' ' and '\n' are NOT equal 
[log] Character 29: '\n' and '?' are NOT equal 
[log] Character 30: '?' and '\n' are NOT equal 
[log] Character 31: '\n' and 'T' are NOT equal 
```

**Version**
- It worked before I updated so one of the last updates broke existing behavior :(
- Currently I have the most up to date version

<img width="262" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/12430709/74c7a867-0722-492b-b62e-fff03126afd9">


- It does not work on both Android / an Mac Desktop App

Do you want me provide you with additional details?

Awesome plugin btw!! 🎊👍

**Comment by ronzulu** [comment]
Hi @biocarl , thanks for the info.

There is some info at https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/828#issuecomment-1876941800 that helped @michail-sygk to fix https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/828.

Are you able to debug into `MultiLineTextFinder.find` which should be tolerant of leading and trailing whitespace?

If not, I'll send through a debug version that logs all relevant info to the console.

Cheers
Ronny

**Comment by biocarl** [comment]
@ronzulu, also debugged `MultilineTextFinder.find` and it is the same problem as in https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/830
With all this trimming logic the whitespace is also trimmed from the original note. In my case, after appending the review comment the whitespace after the `#review` is trimmed. But for me at least that is fine ✌️
Hope we get https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/830 into the release soon!

Thanks for your support 👍
Cheers, Carl
