### ISSUE TITLE
[FEAT] For improved UX, split the long list of plug-in options across categories within a tab control

### ISSUE THREAD

**Issue by ronzulu** [st3v3nmw/obsidian-spaced-repetition#839]
**Is your feature request related to a problem? Please describe.**

The list of options supported by the plug-in is quite extensive. This list likely will grow when various feature enhancements are implemented, and will become somewhat daunting especially for new users.

**Describe the solution you'd like**
Split the current list by category by using a tab control, such as used by the "shell commands" plug-in

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/0e0b414a-59c6-4160-90ae-0506f630d0ab)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/2d28b8ac-e7f9-406e-a468-923a0bfd9ec5)

**Comment by Steindvart** [comment]
A good idea. It looks amazing! I didn't even know that there is such an opportunity in the organization of the settings interface. I will try to implement it in the near future.

**Comment by ronzulu** [comment]
Sorry @Steindvart I've started without you!

**Comment by Steindvart** [comment]
> Sorry @Steindvart I've started without you!

Thanks! Then we will wait for such a wonderful update :)

In connection with this situation, such an idea arose – it is necessary to mark in the Issue (comment or in description) that you started working on it. This will be a good practice to avoid isolated cross-work on a particular problem.

**Comment by Steindvart** [comment]
Hi @ronzulu! Looks awesome! Thank you for your work!

The compromise with the `Advanced` tab, I think, is justified and looks the best at the moment.

**Comment by st3v3nmw** [comment]
Hi @ronzulu,

I agree with @Steindvart, the UI improvement is amazing! I'm also not too keen on the name "Advanced", I can't think of a better alternative at the moment

How does it look like on mobile?

**Comment by ronzulu** [comment]
Thanks @Steindvart  and @st3v3nmw 

I've had an idea instead of the "Advanced" tab.

Simply include the setting in both the Flashcard and Notes tabs.

This means that we don't have to struggle to come up with some alternative word to "Advanced", and has the benefit that it's directly visible to users where it is most relevant.

I've added some words "Note that this setting is common to both Flashcards and Notes.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/17709bf6-bbb0-4ef6-9f0f-3a7291ed7898)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/e21f9c25-353f-466d-98e8-b9f02fe1e075)

I know it's quite unconventional to duplicate a setting, but I think it's probably the best solution.

Let me know what you think.

And Stephen, good question regarding mobile. So far I haven't used obsidian on my mobile, so this is a good reason to install!

Cheers
Ronny

**Comment by ronzulu** [comment]
Hi @annappropriate, I'm wondering if you think this is a good idea? Perhaps even more important on a mobile device?

I did try the code on mobile as suggested by @st3v3nmw but it didn't work. I only have basic css skills, if you like this idea would you have a chance to fix on mobile?

Cheers
Ronny

**Comment by annappropriate** [comment]
Hi @ronzulu! Looks neat, would love to have this on desktop!

Regarding mobile, I think that the device size might be a challenge. On desktop, you can be pretty liberal with your tab names. Unfortunately, they won't fit on mobile.
An interesting example of mobile-friendly settings screen is the Linter plugin. It offers tabs with icon titles that reveal their full name when selected, and also search for filtering the options quickly:

![Screenshot_20240616_210116_Obsidian](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/1017417/aa3908d5-c215-4e58-b721-58166d976f03)
![Screenshot_20240616_210129_Obsidian](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/1017417/ab12f215-594d-45c1-a029-c650f0d8513a)

This is quite a bit of work, but it's the nicest way to navigate lots of settings on mobile that I've seen so far.

**Comment by ronzulu** [comment]
@annappropriate 

Thanks for that, I hadn't seen it before. It does seem very well designed. I love how it starts off with just the icons to minimise space, but the active tab has the textual name shown for confirmation. And the search facility is also great – probably a good idea for our plug-in as well given that there are a fair few configuration items already, and I'm sure that will only grow.

I have tried the updated code on my mobile, and the tab names are split over 2 lines which I think is probably okay. The main issue is that content of the tab doesn't change – the tab highlight does change, but not the content.

![2024-06-17 09 18 44](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/97c4daa7-5a87-48b1-8b35-4ac9d215baa3)

Would it be okay if I posted a link to my repository? The issue might be something simple that you can spot and fix quite quickly.

Cheers
Ronny

**Comment by annappropriate** [comment]
I can give it a try

**Comment by ronzulu** [comment]
Actually, I was just trying it again on the desktop before sending you my repository details, and it isn't working now.

So I must have broken it at some point. Hopefully I'll be able to sort this out myself

Cheers

**Comment by ronzulu** [comment]
@st3v3nmw @annappropriate works on mobile now as well.
