### ISSUE TITLE
[FEAT] Command to open the "Review Queue" on the right view panel.

### ISSUE THREAD

**Issue by Steindvart** [st3v3nmw/obsidian-spaced-repetition#840]
### Problem
The right view panel "Notes Review Queue" opens only when the plugin is loaded. And if you close it, then, therefore, it will be possible to open it only when the plugin is restarted. There is no command or button to open it in an intuitive way.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/53004350/01ef1df0-4b21-4706-b9ae-1dd53cfca7ef)

### Solution
Need to add a command to open this panel.

### Context

Actually, I want to realize this by making a contribution. This Issue is more for discussion, if any, and better documentation.

**Comment by st3v3nmw** [comment]
This was released in v1.12.0, closing...
