### ISSUE TITLE
Looking for a co-maintainer

### ISSUE THREAD

**Issue by st3v3nmw** [st3v3nmw/obsidian-spaced-repetition#847]
Hi everyone 👋🏾,

Lately, I haven't had as much time as I would like to dedicate to maintaining and working on this plugin (see number of open issues and pull requests 😢).  The plugin has grown a lot (to over 150K downloads! 🥳) since I started work on it 3 years ago while in university to help me with my studies. As a Kenyan, I'm very happy that people all over the world find this plugin useful.

As a co-maintainer, you'll have collaborator access to this repository and mostly be involved in making improvements, fixing bugs, and reviewing incoming pull requests. Excited? 👀 ...  I'll still be involved in all this and more. I'm currently working on end-to-end testing to make releases faster since currently someone has to manually test each release.

For starters, we'll start with people who have already made sizeable contributions to the plugin (tagging @ronzulu and @AB1908 if interested).

With that being said, anyone interested can start looking into:

-  Addressing issues (there's an outdated list of starter issues labeled as papercuts [here](https://github.com/st3v3nmw/obsidian-spaced-repetition/labels/papercut) - I'll work on updating it)
- Writing [documentation](https://stephenmwangi.com/obsidian-spaced-repetition)
- Helping out with questions in the [discussions](https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions)
- [Translating the plugin into your language](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/282)
- And tracking development [here](https://github.com/st3v3nmw/obsidian-spaced-repetition/projects/3)

If you're interested, you can reach out to me in this issue thread and/or on this email mail@stephenmwangi.com.

Thanks!

**Comment by ronzulu** [comment]
Hi Stephen, firstly all credit to you for creating this plug-in and managing it as an open source project on GitHub. And congratulations, 150k downloads is quite a milestone!

About being a co-maintainer, I can't promise anything long term, but for the immediate future I expect to have some time for this.

Cheers
Ronny

**Comment by ronzulu** [comment]
Hi Stephen, as a suggestion perhaps lets focus on the open PRs first. There is some good stuff there.

Although it would be good if we first coordinate as with some of the PRs I don't think it's obvious how best to use the contribution. Might require some back and forth.

I think this would be easiest over Zoom, if that suited you.

Cheers
Ronny

**Comment by st3v3nmw** [comment]
> About being a co-maintainer, I can't promise anything long term, but for the immediate future I expect to have some time for this.

@ronzulu, the contributions in the immediate future would still be useful for the project. And thank you for the contributions so far, especially the rewrite to separate UI code from the logic 🎉. I'll be inviting you as a collaborator to the project in a few


> as a suggestion perhaps lets focus on the open PRs first. There is some good stuff there.

I agree, we should start with looking at the open PRs before starting other work


> I think this would be easiest over Zoom, if that suited you.

Over Zoom is okay for me. What timezone are you on? I'm in UTC+3. And what days work best for you? I prefer the weekend

Thanks,
Stephen

**Comment by st3v3nmw** [comment]
Hi @Steindvart,

> The idea of expanding the core team is good. Judging by the number of issues and the increasing number of PRs, which affect more and more global changes. This is necessary.

Yes, I agree

> I would like to join, but I'm worried that I don't have enough experience yet and may have problems with time due to the political situation in my country. For now, I will try to contribute as a simple participant :)

Any and all contributions to the project are very much welcome! Given your concerns, I think for now you can continue contributing as you have been (thanks for your contributions so far! 🥳). If we need some extra help, I will reach out... I'm sure we'll need some extra hands 😄

Thanks,
Stephen,

**Comment by ronzulu** [comment]
> Over Zoom is okay for me. What timezone are you on? I'm in UTC+3. And what days work best for you? I prefer the weekend

Great. Weekend is fine for me as well. I'm in Sydney UTC+11, and anytime before 9 PM is good for me. At the moment I'm pretty free this weekend, so pick a time that suits you 😄 

Cheers
Ronny

**Comment by AB1908** [comment]
I'm happy to chip in here and there with PR reviews but I expect not to have time for the next couple of months at least. I'll probably drop by again then. On a similar note, I've actually made substantial progress on my own rewrite of this plugin since what I was looking for turned out to be quite different.

**Comment by ronzulu** [comment]
Hi @st3v3nmw 

How are you? When would suit you to have a Zoom session to discuss.

I could do:
- anytime today before 1:30 PM your time
- tomorrow (Sunday) starting anytime between 10:30 a.m. and 1:30 PM your time

Or next weekend...

Cheers
Ronny

**Comment by st3v3nmw** [comment]
Hi @ronzulu,

1st off, sorry for disappearing 😢 (I started a new job which took some time to adjust and learn the ropes).

We can do this coming weekend on Google Meet / Zoom. I can send you an invite on email (please ping me on mail@stephenmwangi.com). With regards to timing, I'm very flexible on weekends so we can work with what time suits you.

Stephen

**Comment by ronzulu** [comment]
Hey @st3v3nmw, I was wondering what happened to you!  Glad to hear things have settled down.

I'll email on Friday to arrange a time.

Cheers
Ronny

**Comment by st3v3nmw** [comment]
> I'll email on Friday to arrange a time.

Okay! Looking forward to talking to you.

**Comment by st3v3nmw** [comment]
I think I can now close this issue.
