### ISSUE TITLE
[BUG] Edited Card don't get updated after save

### ISSUE THREAD

**Issue by 4Source** [st3v3nmw/obsidian-spaced-repetition#849]
**Describe the bug**
When you in review mode you can edit the current card. This is a great feature but when you click save the card don't get updated in the current review. This would be nice so it is possible to see the changes had the expected effect.

**To Reproduce**

1. Go to review the cards
2. Click on Edit Card
3. Change the Content of the Card
4. Click on Save
5. See the Card didn't get updated

**Expected behavior**
The changes made to the content should appear.

**Screenshots**
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/38220764/5334b56e-aacb-42d8-abb1-e372380e9322)

**Versions:**

-   OS: Win10
-   Obsidian version: 1.5.3
-   Plugin version: 1.11.0
-   Installer version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36

**Comment by ronzulu** [comment]
Note that this is a duplicate of https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/718

**Comment by 4Source** [comment]
Have searched for that but didn't found anything.
