### ISSUE TITLE
[FEAT] Images in flashcards using normal Obsidian syntax

### ISSUE THREAD

**Issue by Robert-M-Lucas** [st3v3nmw/obsidian-spaced-repetition#855]

**Comment by ronzulu** [comment]
Hi @Robert-M-Lucas  thanks for the suggestion.

Could you please elaborate and include an example of card text that you would like to see supported. What would the following look like?

```
Q1::A1

Q2
?
A2
```

**Comment by Robert-M-Lucas** [comment]
Essentially for this sort of flashcard to be correctly rendered:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/100799838/ccbfc19a-9632-4529-aa3c-d1bab3eb6a04)

Currently, only the raw image link text will be shown instead of the image being inserted.

**Comment by ronzulu** [comment]
We haven't heard back from you and so I'm closing this now. Feel free to reopen if you are able to detail more clearly the issue and provide a screenshot of "only the raw image link text"
