### ISSUE TITLE
[FEAT] Bi-directional cards

### ISSUE THREAD

**Issue by Suyashtnt** [st3v3nmw/obsidian-spaced-repetition#865]
**Is your feature request related to a problem? Please describe.**
I have a bunch of definition cards for chemistry polyatomic ions, which are fomatted like `$O H^-$::Hydroxide`. While this allows me to study from chemical formula -> name, I would also like to go the other way without duplicating all my notes 

**Describe the solution you'd like**
Special syntax such as `$O H^-$:=:Hydroxide` which tells the plugin to create 2 cards: one for the formula -> name and name -> formula. 

**Additional context**
N/A

**Comment by ronzulu** [comment]
Hi @Suyashtnt 

Fortunately the feature already exists and is called "single line reversed" and "multi-line reversed"
https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#single-line-reversed

The default separator is  `:::` (3 colons), but this can be changed within the plug-in's setup options.

Cheers
Ronny

**Comment by Suyashtnt** [comment]
> Hi @Suyashtnt
> 
> Fortunately the feature already exists and is called "single line reversed" and "multi-line reversed" https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#single-line-reversed
> 
> The default separator is `:::` (3 colons), but this can be changed within the plug-in's setup options.
> 
> Cheers Ronny

Ah. Based off the name it sounded like those likes started with the answer and gave you the question only, but not bi-directional. Maybe renaming them is a good idea, but that might just be me only. Anyways since it already exists closing as wontfix. Thanks!

**Comment by ronzulu** [comment]
> Ah. Based off the name it sounded like those likes started with the answer and gave you the question only, but not bi-directional. 

Good point
