### ISSUE TITLE
[BUG] Flashcard review UI scaling(?) issue

### ISSUE THREAD

**Issue by dmantisk** [st3v3nmw/obsidian-spaced-repetition#868]
**Describe the bug**
![Screenshot_20240205-110611](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/113114365/023412b2-6b95-4c7d-9a94-e5718b6a55b3)
As seen here the review pane is stuck in the corner.

**To Reproduce**
Simply start the review

**Expected behavior**
The review pane properly scaling to the screen

**Versions (please complete the following information):**

-   OS: Android 7.0
-   Obsidian version: 1.5.3
-   Plugin version: 1.11.1

**Additional context**
The same thing work well on PC

**Comment by ronzulu** [comment]
Hi @dmantisk there is some info at https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/653

Does that help?

**Comment by dmantisk** [comment]
That does, thank you.
Sorry that I missed it.

**Comment by ronzulu** [comment]
No worries. I don't know why the default width is set for mobile devices to be 40%, but I assume there must have been a reason.

We definitely could benefit from having an FAQ for this type of issue.
