### ISSUE TITLE
[BUG] Decks not visible when reviewing flashcards

### ISSUE THREAD

**Issue by semits20** [st3v3nmw/obsidian-spaced-repetition#87]

**Comment by semits20** [comment]
Obsidian Version: 0.12.3
OS: Windows 10

at the time of reviewing flashcards using the sidebar icon, flashcards are being shown but not the decks.

**Comment by st3v3nmw** [comment]
What about the plugin version?
Are there any error logs on the developer console? i.e. `ctrl` + `shift` + `i`

**Comment by semits20** [comment]
Plug In Version: 1.4.6

I am not a technical person but as you have suggested the hotkey i have checked it, i couldn't see any error in developer console.

**Comment by jakeoung** [comment]
A related issue: when I open the reviewing by shortcut, it will not show any cards I have.

**Comment by st3v3nmw** [comment]
@semits20, I can't reproduce this issue. I'm not sure what the problem might be.

@jakeoung, I fixed that issue. I'll make the release available soon.

**Comment by st3v3nmw** [comment]
Since you managed to list decks, I'll close this issue.
