### ISSUE TITLE
[FEAT] small ui overhaul suggestions w/ concept drawings

### ISSUE THREAD

**Issue by KyleKlus** [st3v3nmw/obsidian-spaced-repetition#872]
Hi there,

I have some ideas for a small ui overhaul on "obsidian spaced repetition" and I have made some concept drawings. So, I wanted to share these here and see if anybody has some remarks (especially @st3v3nmw, @ronzulu). I would be happy to implement those ideas myself in a PR draft.

### Proposal for code changes

- [x] Refactoring FlashcardModal into several views.
- [x] Refactoring keyboard listener
- [x] Implementing ui changes

### Concept drawings
_left -> mockup, right -> comments_

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97227530/90c9f4e2-3f64-4514-8d6a-b6ca1f27c6b0)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97227530/5da7c10b-af98-4387-9263-543073d6e983)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97227530/6db78c69-1ec8-4fa8-859c-33b7dec4850c)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97227530/cf2ad959-95e0-4dd9-830f-8eed549c0723)

**Comment by ronzulu** [comment]
Hi again

I like nearly all of your ideas, but unsure of a couple.

(2) Are you planning to include the full word or just the first letter? I'm just concerned about non-English translations where potentially the first letter isn't unique for new/due/total

(3) nice suggestion, but the disadvantage is that it would cause (some, although temporary) confusion for existing users. Also would be confusing if a user was to lookup up existing documentation or posts, and the order was opposite to the software.

I'm sure you are much more visually aware than most :smile: It never crossed my mind that the colours on this page are in a different order to the ones on the buttons on the card review view!

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/d2929191-a6c3-44f0-ae55-37e934f493ce)

**Comment by KyleKlus** [comment]
(2) I came across this issue too, so I included the whole word, instead of just the first letter. I think it looks worse than just having one letter or nothing in front of it, but I was always confused, which color means what, so I kept it, as it improves the onboarding experience for new user a lot.
This is how it now looks:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97227530/2968012f-b4f8-4b95-a19a-ae37fd97ea04)

(3) I thought of that too, so I didn't switch the colors, but I switched the positions of the numbers around, so that the people can still rely on the color they learned, but the order is different

**Comment by KyleKlus** [comment]
### New card view
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97227530/f7bcd36f-06d7-4b56-b7f5-69097afa09aa)

### New edit view
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97227530/57bb5b8d-6f96-4eec-8fe9-7bebf1013ef1)

**Comment by st3v3nmw** [comment]
I think we can close this now
