### ISSUE TITLE
[FEAT] Refactor code to support diff methods of storing the scheduling info, and diff SR algorithms

### ISSUE THREAD

**Issue by ronzulu** [st3v3nmw/obsidian-spaced-repetition#878]
The current code has a structure tied to the method of storing scheduling info within the note markdown file itself.

Refactoring the code is a prerequisite to implementing other methods, e.g. as requested in:
[[FEAT] Stop using YAML; Move plugin info and data to separate file](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/162)

**Comment by pikatwinky** [comment]
It's only my opinion but,
Talking about the note review mode... i think having the note schedulling info in the frontmatter is useful when using combined with Dataview, so you can create through the use of queries custom review sessions to filter down only certain set of notes based on properties (in particular using the 'due date' field), functionality none existent currently in the plugin (you have to review your notes in a global way) 
But on the other hand, talking about the flashcards, i think having their scheduling info in a separate db could help to unclutter the notes, but of course, maybe this last is unfeasible

**Comment by YIRU69** [comment]
I hope you can bring FSRS functionality into this project!

**Comment by ronzulu** [comment]
I hope so! I've completed implementing the re-factoring addressed by this issue, but not yet completed testing.

After this then there are a couple of other nontrivial tasks to complete...

**Comment by YIRU69** [comment]
Hi! Can you tell me approximately how long until I can use FRSR?

**Comment by ronzulu** [comment]
Hi @YIRU69 if I'm the one implementing, I'd think realistically say 6 months, so around October this year.

**Comment by st3v3nmw** [comment]
@ronzulu this is done now right?

**Comment by ronzulu** [comment]
Hi @st3v3nmw 

More will need to be done when new data stores are actually implemented, for example converting from one Datastore type to another.

But I'm happy enough with what's been completed so far, so I'll close this now.

**Comment by YIRU69** [comment]
@ronzulu Hi, glad to hear you complete this huge work. But it just part work for FSRS? I check the newest update and can't find FSRS.

**Comment by ronzulu** [comment]
Unfortunately @YIRU69 that is correct. It's only one part.

Also, I've taken @danhje suggestion and am first working on [ [FEAT] user defined "Easy, Good, Hard" values instead of or in addition to the algorithm defined one. #741 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/741).

The rationale being that #741 is a practical and easier way of verifying the work done here in #878 compared with FSRS. (Apart from all the unit test cases I added here...)
