### ISSUE TITLE
Translate plugin to other languages

### ISSUE THREAD

**Issue by st3v3nmw** [st3v3nmw/obsidian-spaced-repetition#88]
Crowdsourced - volunteers from the community.

**Comment by weeshinwang** [comment]
How can I contribute to the translation? I can translate into Simplified Chinese.

**Comment by st3v3nmw** [comment]
Hey, thanks!
I don't have this setup yet, but I'll do so soon & reach out to you.

**Comment by st3v3nmw** [comment]
Hey @weeshinwang, we now have support for multiple languages. To help translate the plugin, copy the entries from `src/lang/locale/en.ts` to the proper file in `locales` (i.e. `fr.ts` for French, or `sw.ts` for Swahili), translate, and then open a pull request. Thanks!
