### ISSUE TITLE
[FEAT] Add git hooks with husky

### ISSUE THREAD

**Issue by EspiraMarvin** [st3v3nmw/obsidian-spaced-repetition#880]
**Is your feature request related to a problem? Please describe.**

- The feature is unrelated to a problem but will help automate the development cycle. We can use Husky to lint commit messages, run tests, and lint code when you commit or push code. We can specify commit message formats, add pre-commit and post-merge hooks

**Describe the solution you'd like**

- There are specific tasks to handle with git hooks for this project: 
  1. Automate code linting after staging file changes
  2.  Running automated tests

**Additional context**

**Comment by st3v3nmw** [comment]
Hi Marvin!

Yes, this would be good to add to the project.
