### ISSUE TITLE
[FEAT] Advanced support for multi-line

### ISSUE THREAD

**Issue by jvdevlab** [st3v3nmw/obsidian-spaced-repetition#881]
**Is your feature request related to a problem? Please describe.**
The multi-line support doesn't allow for reach formatting of the answer.

Here is the example of the card I would like to have:

```
Question?
??
Answer 1

Empty line above

Code Block

More empty lines.

Links to other cards 

```

The work around I can have right now is to use blockquote

```
Question?
??
>Answer 1
>
>Empty line above
>
>Code Block
>
>More empty lines.
>
>Links to other cards 
```

This doesn't make it look nice. I can play with formatting more and don't wrap code block but it would be nice to have better support for multi-line

**Describe the solution you'd like**

Introduce configurable delimiters for the answer boundaries. By default it could be comments. 

```
Question?
<!--SR:START-->
Answer 1

Empty line above

Code Block

More empty lines.

Links to other cards 

<!--SR:END-->
```

Thank you.

**Comment by ronzulu** [comment]
Hi @jvdevlab 

Thanks for the suggestion.

There are some related features already requested, please see:
- [[FEAT] Support blank lines in multi-line flashcards ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/254)
- [More flexible formatting (especially blank lines) for flashcards](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/601)

The current functionality supports changing the string that separates the question from the answer. I haven't tried it, but I would think that you would be able to change it to `<!--SR:START-->`.

Note that #601 has support for blank lines in the question as well as the answer:
```
^^^
This is the first line of my question.

This is the second line my question.
+++
This is the first line of my answer.

This is the second line of my answer.
vvv
```

Is there anything that you are after that would not be supported if #601 is implemented?

Cheers
Ronny

**Comment by jvdevlab** [comment]
Hi @ronzulu,

Thank you for the reply. Any solution that would support blank lines will do. 

I feel like comments approach will make it be less prone to conflict with other delimiters used in other notes and easier to parse.

I did try the comment as a start delimiter.

`## Test questions?

Test answer
`
It cuts off the beginning of the question

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/83979897/0ffab44d-a28b-4374-bd01-b4f9fdd994b7)

But as mentioned above any solution will do.
Thanks

**Comment by ronzulu** [comment]
Hi @jvdevlab glad we have managed to consolidate functionality at #601.

I'll close this off now, but if there is anything else related you think of, feel free to update that issue.

Cheers
Ronny
