### ISSUE TITLE
Button issue

### ISSUE THREAD

**Issue by HilariousJon** [st3v3nmw/obsidian-spaced-repetition#884]
**Is your feature request related to a problem? Please describe.**

I don't know why it only show two buttons in the newest version, I check the setting but found not ways to deal with it.

**Describe the solution you'd like**

add the button good, and respectively add the setting for reoccur days

**Comment by HilariousJon** [comment]
and also maybe can make the button bigger and be in the middle

**Comment by ronzulu** [comment]
Hi @HilariousJon please let us know what platform you are using:

```
-   OS: [e.g. iOS]
-   Obsidian version: [e.g. v0.12.4]
-   Plugin version: [e.g. v1.4.9]
```

Also send screenshots.

**Comment by HilariousJon** [comment]
- OS：windows11
- Obsidian version: v1.5.8
- plugin veision: v1.11.1
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/143948932/93ace50b-f4a5-49cd-9da7-ba3ed47953a1)
some times it will come out three button and sometimes not, if it came as three button it will turns out that the button not go at the middle,,,,,and now I couldn't figure out how to get three buttons out.
also I wanna ask that how to delete the time mark left by the plugin after every time it came out  a 3 button, because that somehow make my note ugly.or could it be just make some improvement to not showing it under the reading mode.
Think that maybe you should update your manual, since the version has changed a lot.
I think that you can put more flexibility in the setting, so the user can define some function as they wish.
I think the plugin has a more comfortable user interface than anki, but still some function cannot achieve as good as anki, can it be improved

**Comment by ronzulu** [comment]
Hi @HilariousJon 

There are two separate ways that cards can be viewed:

1. Review mode
2. Cram mode

In review mode, three buttons are shown, and based on which button is selected, the scheduling info kept within the HTML comment is updated differently.

In cram mode, two buttons are shown and the scheduling info is not updated.

From the Obsidian command pallet, entering "flashcard" shows the following:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/de7c1a4e-f30e-4f7b-b2e2-82c38b053dcd)

Note that clicking on the plug-in's flashcard icon, specifies review mode.

Cheers
Ronny

**Comment by HilariousJon** [comment]
I see....
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/143948932/0d70baa8-38c6-4d15-a984-c4ff406e627d)
final issue is can these three button be go to the middle and get bigger?

**Comment by ronzulu** [comment]
@KyleKlus has been looking at this, see #872

**Comment by HilariousJon** [comment]
ok, Thanks for the answers!!!
