### ISSUE TITLE
Can there be an option to toggle on and off whether a flash card will be shown when a particular note is open 

### ISSUE THREAD

**Issue by KALKI-the-avataar** [st3v3nmw/obsidian-spaced-repetition#90]
The Idea is having flashcards in obsidian must resonate with our writings our literature. suppose I am viewing a note and at the same time I review a flashcard but if a flashcard Is something completely of the contest then there is no meaning of it. What I want is can there be a toggle to on and off so that the flashcard will show cards that have been formed from the notes which have been linked to the current note 2 levels deeper. What I am trying to make is a mnemonic medium.

**Comment by st3v3nmw** [comment]
I get this bit, it's the same as #56.
> suppose I am viewing a note and at the same time I review a flashcard but if a flashcard Is something completely of the contest then there is no meaning of it.

But I'm not really sure about this one:
> What I want is can there be a toggle to on and off so that the flashcard will show cards that have been formed from the notes which have been linked to the current note 2 levels deeper. What I am trying to make is a mnemonic medium.
Could you please provide some more information/context?

**Comment by st3v3nmw** [comment]
Stale issue, closing...
