### ISSUE TITLE
Unrelated Tags in Card Selection Modal since version 1.12.0

### ISSUE THREAD

**Issue by ikelos555** [st3v3nmw/obsidian-spaced-repetition#908]
**Describe the bug**
With version 1.12.0, unrelated tags are shown as well, which makes the whole appearance a bit messy. E.g. my tag for marking flashcards is "#flashcard", but sometimes there are a couple other unrelated meta-tags added to the note, like date tags and so on. Now the UI is clustered with all unrelated tags as well, not only the #flashcard tag and its sub-tags (#flashcard/sub1).

**To Reproduce**
Open card selection modal.

**Expected behavior**
Only the configured tag (in my case #flashcards), and its sub-tags should be listed.

**Screenshots**
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/10416355/52a9f0f6-0d4c-4575-8f68-5497d724b11f)

**Versions (please complete the following information):**

-   OS: macOs Sonoma 14.3.1
-   Obsidian version: 1.5.11
-   Plugin version: 1.12.0

**Additional context**
[data.json](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14662527/data.json)
[What is a heap.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14662604/What.is.a.heap.md)

**Comment by ronzulu** [comment]
Hi @ikelos555 

Sorry about that, I've fixed the problem and added a unit test case.

Could you please use this beta version.

There is a file called `main.js` in this zip file
[main_908A.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14663250/main_908A.zip)

You will need to copy that to the obsidian plug-in folder, e.g.
`D:\Obsidian\Obsidian\.obsidian\plugins\obsidian-spaced-repetition`

Then reload the plug-in, or restart obsidian. 

Any feedback appreciated.

Ronny

**Comment by ikelos555** [comment]
Thanks for the quick fix - tested it and works perfect!

Best
Marco
