### ISSUE TITLE
 Nested decks feature

### ISSUE THREAD

**Issue by Couriuss** [st3v3nmw/obsidian-spaced-repetition#91]
It would be awesome to organize flashcards into decks and sub-decks like what you can do in Anki, this way you can study specifically what's needed in that particular moment. 

As a stundent I find this feature really helpful.

**Comment by Couriuss** [comment]
Another feature related to this is to use frontmatter instead of tags to insert cards into decks.

An example:
---
Deck::Deck Name::Sub-deck::Sub-subdeck (eventually)
---

**Comment by OliverBalfour** [comment]
I think the nested tags feature might be a nice way to do this.

Personally, I'd like to set `#flashcards` as the "Flashcard tags" setting and then have nested tags like `#flashcards/python` be recognised as their own decks. This approach could also be used for sub-decks like `#deck/subdeck/subsubdeck`, where `#deck` contains all of the subdecks by default (so you can study entire decks or just subdecks as you please)

Currently, if you use nested tags, you need to manually add each child tag to the "Flashcard tags" setting.

**Comment by st3v3nmw** [comment]
I agree with what @OliverBalfour said, hierarchical tags allow us to have a more consistent syntax for specifying sub-decks.

**Comment by st3v3nmw** [comment]
Converting folder path to decks & subdecks could be a useful option too.

**Comment by st3v3nmw** [comment]
Nested decks should be available in the next release!
