### ISSUE TITLE
[BUG]Card review update failed

### ISSUE THREAD

**Issue by Benn314** [st3v3nmw/obsidian-spaced-repetition#918]
When I open the review of a certain label group in the card group review, it shows that there are no cards that have not been reviewed, but when I close the window and reopen it, it shows that the card group has not been reviewed, I don't know what the reason is, does anyone help me to see what the reason is.

**Comment by Benn314** [comment]
If you open the card group for review through the above options, it can be updated normally.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/70643377/68399361-ad3b-4925-a177-f49168c43d96)

**Comment by ronzulu** [comment]
Thanks for the screenshot.

I've attached the files that contain all the language elements used by the plugin.
[locale.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14754985/locale.zip)

Could you please identify:
- the relevant file for your language and 
- the string that relates to the item you marked as "Success"
- the string that relates to the item you marked as "Fail"

E.g. highlight:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/765669c5-5c11-4bb7-90c1-006e2be99368)
