### ISSUE TITLE
[BUG] Unable to recognize multi-line card that begins immediately after the frontmatter's closing line

### ISSUE THREAD

**Issue by Redfisha** [st3v3nmw/obsidian-spaced-repetition#922]
Describe the bug：
when there is no a blank line after frontmatter，it cannot  recognize card.
![屏幕截图(1577)](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/49059743/6f99c97f-0a6d-4928-ae47-ae0ed589bde1)

Obsidian version: 1.5.11
Plugin version: 1.12.2

**Comment by ronzulu** [comment]
Hi @Redfisha 

Please check with the updated file, see https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/915#issuecomment-2033277592

Thanks
Ronny

**Comment by Redfisha** [comment]
thanks  ronny
problem sovled.

**Comment by ronzulu** [comment]
Great, thanks for letting me know

**Comment by ronzulu** [comment]
Fixed in release 1.12.4, closing this now.
