### ISSUE TITLE
[BUG] Most of my flashcards are now missing

### ISSUE THREAD

**Issue by nstebbins** [st3v3nmw/obsidian-spaced-repetition#923]
**Describe the bug**
I updated the community plug-in to the latest version of Spaced Repetition and was dismayed find that most of my tagged flashcards are missing. I went from having about 1500 flashcards to about 155. 

**Screenshots**
Here's a video with the exact issues that I'm seeing. 

https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/5514378/b940358a-92a0-4f84-8aa0-2731f665a93f

**Versions (please complete the following information):**

-   OS: macOS Sonoma 14.1.2
-   Obsidian version: 1.4.16
-   Plugin version: 1.12.2

**Additional context**
I'm happy to provide any additional details.

**Comment by huetruong** [comment]
Same here. I came looking why my cards are gone.

**Comment by vrmneto** [comment]
same here

**Comment by huetruong** [comment]
I reloaded 1.11.2 and it works again. The changes from 1.12.0 has breaking changes to the way I have been styling my flashcards.

**Comment by vrmneto** [comment]
@huetruong how did you installed it?

**Comment by huetruong** [comment]
> @huetruong how did you installed it?
Go to link below, and download, extract to the .obsidian folder where the plugin is installed. Overwrite the new version with the older version.

https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.11.2

**Comment by ronzulu** [comment]
Hi @nstebbins thanks for letting us know and identifying the issue, the video was helpful.

The code went through non-trivial changing when implementing the recent enhancements for:
[Multiple Tags Within a Single File](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#multiple-tags-within-a-single-file)
[A Single Card Within Multiple Decks](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#a-single-card-within-multiple-decks)

I never considered a note format where the multi-line character is present on the line immediately after the end of the frontmatter, i.e.:
```
---
{{frontmatter}}
---
?
{{multi-line answer}}
```

It isn't something that I personally use, and it didn't occur to me. 

@huetruong @vrmneto please let me know if this is the format of notes that you are using. 

Thanks
Ronny

**Comment by ronzulu** [comment]
Hi @nstebbins 

Could you please post (attach, not copy/paste) the markdown file in your video.

Please also include a description of the expected behavior.

I've tried to recreate, using:
```
---
tags:
  - flashcards
src: https://www.khanacademy.org/
---
?
Yes, this is the answer
```

In version 1.11.2 the card is displayed with a blank front:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/2fe0268d-1de0-47c0-a401-19113933031c)

Is that what you are expecting?

Thanks
Ronny

**Comment by nstebbins** [comment]
[Merchant Credit.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14815599/Merchant.Credit.md)

**Comment by vrmneto** [comment]
> Hi @nstebbins thanks for letting us know and identifying the issue, the video was helpful.
> 
> The code went through non-trivial changing when implementing the recent enhancements for: [Multiple Tags Within a Single File](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#multiple-tags-within-a-single-file) [A Single Card Within Multiple Decks](https://www.stephenmwangi.com/obsidian-spaced-repetition/flashcards/#a-single-card-within-multiple-decks)
> 
> I never considered a note format where the multi-line character is present on the line immediately after the end of the frontmatter, i.e.:
> 
> ```
> ---
> {{frontmatter}}
> ---
> ?
> {{multi-line answer}}
> ```
> 
> It isn't something that I personally use, and it didn't occur to me.
> 
> @huetruong @vrmneto please let me know if this is the format of notes that you are using.
> 
> Thanks Ronny

Mine is diferent
![Captura de tela 2024-03-31 122624](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/68965241/f18784c3-0222-4e94-9ff2-8aff2160b524)

I am using the highlight to mark the omitted part of the note, 
![Captura de tela 2024-03-31 122902](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/68965241/dbf74129-8dab-497b-885d-461131e63929)

**Comment by vrmneto** [comment]
> > @huetruong how did you installed it?
> > Go to link below, and download, extract to the .obsidian folder where the plugin is installed. Overwrite the new version with the older version.
> 
> https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.11.2

thx man, it worked. You saved me here heheheh

**Comment by ronzulu** [comment]
@vrmneto you will need to give further explanation regarding "Mine is diferent".

What of yours is different? And different to which other user?

Also attach your markdown file (attach the file, don't copy/paste).

**Comment by vrmneto** [comment]
> @vrmneto you will need to give further explanation regarding "Mine is diferent".
> 
> What of yours is different? And different to which other user?
> 
> Also attach your markdown file (attach the file, don't copy/paste).

the difference is that I am using the highlight to mark the omitted part of the note, and not using ---
{{frontmatter}}
---
?
{{multi-line answer}}

[CF 37 §3° I - Participação de usuário na administração pública.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14823057/CF.37.3.I.-.Participacao.de.usuario.na.administracao.publica.md)

**Comment by ronzulu** [comment]
Hi all

Please check with the updated code, see https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/915#issuecomment-2033277592

Thanks
Ronny

**Comment by nstebbins** [comment]
Updated `main.js` and this is what I got 🤔 

![Screenshot 2024-04-04 at 11 34 15 AM](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/5514378/663914c8-c498-4f26-bf92-92b9f3c9e0b7)

**Comment by ronzulu** [comment]
Sorry about that, the style.css was recently changed. I've updated the zip file on #915 to include the latest version.

**Comment by ronzulu** [comment]
Hi @nstebbins sorry to hassle you, would be great if you could check again. Thx

**Comment by nstebbins** [comment]
Updated the stylesheet & JS file per your instructions and everything looks good now. Thanks for the support @ronzulu 👍🏻 

Have a great rest of your week

**Comment by ronzulu** [comment]
Thanks @nstebbins have a great weekend!
