### ISSUE TITLE
[BUG] Decreasing numbered List

### ISSUE THREAD

**Issue by 0xOktAvIan** [st3v3nmw/obsidian-spaced-repetition#925]
**Describe the bug**
When creating a decreasing numbered list (4. 3. 2. 1. - over multiple lines of course), when reviewing that flashcard, the list has the wrong numbers (4. 5. 6. 7.).

**To Reproduce**
1. Open Test Vault
2. Install Spaced Repetition
3. Create file, type decreasing numbered list
4. review the flashcard

**Expected behavior**
The numbered list should be decreasing (4. 3. 2. 1.)

**Screenshots**

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/95540768/4e6ca88f-66af-44c4-b20e-8e0c8b38d2e5)

**Versions (please complete the following information):**

-   OS: Windows 11 Home
-   Obsidian version: v1.5.11
-   Plugin version: v1.12.2
-   If on desktop, Installer version: '5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.5.8 Chrome/120.0.6099.283 Electron/28.2.3 Safari/537.36'

**Additional context**

File to reproduce: [Test.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14881555/Test.md)

**Comment by ronzulu** [comment]
It seems to be a quirk of Obsidian's reading mode. It exhibits the same issue in the following case:

[925.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14883630/925.md)

```
4. This
3. is
2. a
1. test
```

In reading mode (independent of the spaced repetition plugin) renders as:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/148065f6-8190-498d-8262-7152a450737b)

Note that if there is text in the line preceding the list, it renders correctly:
```
#flashcards/925

Test question
?
Here is the decreasing list
4. This
3. is
2. a
1. test
```

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/13036772-b886-4814-b9a4-ca8adca6dbf1)

(well, nearly correctly... I don't know why it put the last line out there like that)

Cheers
Ronny

**Comment by ronzulu** [comment]
Closing this now as this seems to be an Obsidian matter not specific to this plugin.
