### ISSUE TITLE
[BUG] #review does not work

### ISSUE THREAD

**Issue by toppanam** [st3v3nmw/obsidian-spaced-repetition#928]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain the bug. This could be the logs in the developer console (`CTRL` + `SHIFT` + `i`).

**Versions (please complete the following information):**

-   OS: [e.g. iOS]
-   Obsidian version: [e.g. v0.12.4]
-   Plugin version: [e.g. v1.4.9]
-   If on desktop, Installer version: [run `this.navigator.appVersion` on the developer console, e.g. `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"`]

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by toppanam** [comment]
I tried putting #review as tag on property. But it did not showing up on the Note Review Queue

**Comment by ronzulu** [comment]
You will need to click on the OSR flashcard icon for the plug-in to recognize that there are new note (or notes) with the #review tag.

Does that work?

**Comment by toppanam** [comment]
where is the OSR flashcard icon? I only have the Review flaschards icon on the Ribbon bar

**Comment by ronzulu** [comment]
Yes, that is the one

**Comment by toppanam** [comment]
I've tried that, all the cards have been viewed.  on the decks, but they don't shows on the Notes Review Queue

**Comment by ronzulu** [comment]
Glad you got it sorted out :-)

**Comment by toppanam** [comment]
Is there something can be done on the plug in to fix that?
