### ISSUE TITLE
[FEAT] A few feature requests

### ISSUE THREAD

**Issue by TolgaKerem07** [st3v3nmw/obsidian-spaced-repetition#941]
**Is your feature request related to a problem? Please describe.**

1- I always use my notes in live preview mode and the texts added by the plugin look unpleasant.
2- SM2 algorithm is very old
3- Multiple clozes are very useful when doing various memorizations in my field, but they are not supported at the moment.

**Describe the solution you'd like**

1- Option to save flashcard information in a different file maybe inside the plugins folder
2- I think the newer FSRS algorithm might work better
3- Multiple clozes support please
4- Is image occlusion possible?

**Additional context**

Thank you for the great plugin. But especially the first two problems prevent me from using it for now

**Comment by ronzulu** [comment]
Hi @TolgaKerem07, thanks for that. Here are some references to existing issues.

> 1- Option to save flashcard information in a different file maybe inside the plugins folder

[ [FEAT] Stop using YAML; Move plugin info and data to separate file #162 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/162)

> 2- I think the newer FSRS algorithm might work better

[ [FEAT] sm-2 is outdated, can you please replace it with the fsrs algorithm? #748 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/748)

> 4- Is image occlusion possible?

[ [Feat] Image occlusion #34 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/34)

Best to always search before opening a new feature or bug report. With the above I suggest going to the referenced issues and add a comment such as "I would also find this useful".

I've separated:

> 3- Multiple clozes support please

The references here are for "pull requests" i.e. code that has been contributed, but not yet released.
[ Support for atomic clozures #797 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/797)
[ Support for many clozures within a single flashcard #796 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/796)
[ Support for Anki Cloze Syntax #769 ](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/769)

If your request is covered by those, then add a comment such as "I would also find this useful" on those PRs

If not, open a new issue specifically for it. You would need to detail what you are after, giving examples.

**Comment by TolgaKerem07** [comment]
Sorry, you are right. I've seen a few of posts you mentioned, but I'm not very familiar with how GitHub works. I did what you said

**Comment by TolgaKerem07** [comment]
Sorry, you are right. I've seen a few of posts you mentioned, but I'm not very familiar with how GitHub works. I did what you said

**Comment by ronzulu** [comment]
> Sorry, you are right. I've seen a few of posts you mentioned, but I'm not very familiar with how GitHub works. I did what you said

No worries, I think we are all learning here  :-)
