### ISSUE TITLE
Option to rename "Easy", "Good", "Hard" when scheduling *Notes*

### ISSUE THREAD

**Issue by Rothrod** [st3v3nmw/obsidian-spaced-repetition#944]
**Is your feature request related to a problem? Please describe.**
I find confusing the use of "Easy", "Good", "Hard" when scheduling Notes. I try to use the notes scheduler as a Incremental Reading/Writing tool and the "Skip", "Fruitful", "Unfruitful" languange makes more sense in that context, since I'm not trying to memorise the note but rather reviewing it to understand it and potentially extract uself cards out of it.

**Describe the solution you'd like**
An option to rename the "buttons" the way it already exists for the flashcards buttons

**Comment by 4Source** [comment]
Just use 
![image](https://github.com/user-attachments/assets/365cd864-cadd-4471-a602-6a37faae5007)

And please mark as closed
