### ISSUE TITLE
[BUG] Links in section titles

### ISSUE THREAD

**Issue by dengrish** [st3v3nmw/obsidian-spaced-repetition#951]
I have section titles that contain links to other notes or PDF documents. When reviewing cards, the plugin does not correctly display such sections titles. The correct behaviors should be to show only the text after the vertical bar |. See screenshot below.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/17466045/80b515a1-504c-431b-a5cd-6ab12d8f438b)

**Comment by ronzulu** [comment]
Hi @dengrish seems like a good suggestion to me.

So you would want to see the question rendered as:
`3. Classification > Performance Measure > Precision and Recall`

Is that correct?

Personally I can't see anyone wanting the current formatting and I think the code should simply be modified.

If anyone thinks differently, please comment and perhaps the formatting style would be made a new option.

Cheers
Ronny

**Comment by dengrish** [comment]
Yes! It should be rendered as `3. Classification > Performance Measure > Precision and Recall`. Thanks!

**Comment by dengrish** [comment]
[1. The ML Landscape.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/15407696/1.The.ML.Landscape.md)

A sample note is attached. Thanks!

**Comment by 4Source** [comment]
Created a Fix for this now its up to the reviewer to include it.
