### ISSUE TITLE
[FEAT]Added option to review md file

### ISSUE THREAD

**Issue by qq269684709** [st3v3nmw/obsidian-spaced-repetition#965]
Bilingual

本插件基于supermemo，而supermemo18之后的学习流程，是先复习文章。从文章中摘录挖空或根据理解写问答卡片等复习卡片，而本插件仅仅只有复习卡片的功能。希望添加复习md文件的功能，也类似于obsidian的功能：开始漫步笔记，在这个基础上可以拥有间隔重复的复习逻辑。
This plugin is based on supermemo, and the learning process after supermemo18 is to review articles first. Review cards such as hollowing out or writing quiz cards according to the understanding of the article, and this plug-in only has the function of reviewing cards. Want to add the function of reviewing md files, also similar to the function of obsidian: start walking notes, on this basis you can have interval repeat review logic.

期待作者你的更新
Looking forward to your update from the author

**Comment by qq269684709** [comment]
双语
Bilingual
对不起，今天尝试更新版本到1.12.4，发现以及可以复习卡片了。但相对的复习步骤还可以根据上面的建议进行优化。感谢作者开发这么棒的插件，也期待早日加入FSRS算法
Sorry, tried to update the version to 1.12.4 today, found and can review the card. However, the relative review steps can also be optimized according to the above suggestions. Thanks to the author for developing such a great plugin, and look forward to adding FSRS algorithm soon

**Comment by qq269684709** [comment]
双语
Bilingual
shen'zi可以取消添加标签的方式来默认应用在obsidian的所有的MD文件中，参考supermemo对所有html的方式，然后可以忽略某个文件夹即可。
shen'zi can default to all obsidian MD files by untag-adding method, just follow supermemo's method for all html, and then ignore a folder.

**Comment by 4Source** [comment]
You solved you Problem by yourself? If so please close the Issue. 

> However, the relative review steps can also be optimized according to the above suggestions.

What improvements do you have in mind?
