### ISSUE TITLE
[FEAT] Do not auto scroll to the top of the flashcard after clicking to reveal the answer

### ISSUE THREAD

**Issue by nayyala** [st3v3nmw/obsidian-spaced-repetition#966]
For longer cloze deletion cards, it is rather annoying to have to scroll back down again after having done so in the first place when selecting to read the answer. Preserving the current scroll position would be very convenient.

**Comment by 4Source** [comment]
Could you share such a long card. Best would be to share the whole file. 
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/38220764/8e39412a-c6fc-4b52-ba8d-6901a67616f9)

This could potentially a bit difficult but I will take a look at it.

**Comment by nayyala** [comment]
Here:

Radar Questions #1
>
> What is IQ demodulation, and why is it important in radar systems?
> ==IQ demodulation involves reconstructing the complex envelope of a signal from in-phase (I) and quadrature-phase (Q) components, which is crucial for accurately processing radar signals after downconversion.==
>
> How are the I and Q components used to reconstruct a radar signal?
> ==The I and Q components are combined to form the complex signal envelope, where the in-phase (I) component represents the real part and the quadrature-phase (Q) component represents the imaginary part. This allows for accurate signal reconstruction.==
>
> What does the following diagram illustrate about IQ demodulation?
> ![[Pasted image 20240520223430.png|400]]
> ==The top diagram shows the downconversion process at the ADC, and how the I and Q components are derived using cosine and sine functions from the input signal.==
>
> What does the the following diagram depict about the time signal and coherent I and Q sampling?
> ![[Pasted image 20240520223456.png|500]]
> ==The bottom left diagram shows the time signal at the top and the corresponding coherent I and Q sampling of a Doppler shifted pulse train, illustrating how these components vary over time.==
>
> What is shown in the following diagram regarding Doppler processing?
> ![[Pasted image 20240520223525.png|500]]
> ==The bottom right diagram illustrates a generic Doppler processor of a coherent train of M identical coded pulses, highlighting the integration and FFT processing steps for Doppler frequency analysis.==
>
> Big Picture: Why is understanding IQ demodulation and Doppler processing critical for radar technology?
> ==Understanding IQ demodulation and Doppler processing is essential for accurately interpreting radar signals and extracting meaningful information about target movement and velocity. These techniques are fundamental for effective radar signal processing, enabling advanced applications such as target tracking, velocity measurement, and improving overall radar performance.==

Copy this into Obsidian, should be long enoughy, though I had images in there, maybe some example files might be sufficient

**Comment by 4Source** [comment]
https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/38220764/6f6842a0-afdf-4c23-9b17-d39d13217482

Did you mean the scroll back up after your selected hard/good/easy?

**Comment by 4Source** [comment]
If you wanna try my FIX this would be great here you can download the [main.js](https://github.com/4Source/obsidian-spaced-repetition/releases/tag/BUG_966_Beta.1) file and put it in ``YOUR_VAULT/.obsidian/plugins/obsidian-spaced-repetion`` not sure this is possible on mobile if your are on mobile

**Comment by nayyala** [comment]
Hi sorry for the late reply:
- i have it on max flashcard size
- that new fix looks great! I am using it on computer only

**Comment by 4Source** [comment]
> * that new fix looks great! I am using it on computer only

The video isn't a fixed version if you thought this. If I understand you correctly it jumps back up to the top after clicking ``show answer`` and not like it is in my case after clicking ``good/easy/hard``

**Comment by 4Source** [comment]
Could you please give additional Information: 
- Your System OS
-  Plugin Version
- Obsidian Version
- A Video of how it looks by you would be great

**Comment by nayyala** [comment]
Windows 11
1.12.4
1.5.12

I will try to upload the video soon, it seems like you understand the issue though

**Comment by ronzulu** [comment]
Hi @nayyala did you manage to try @4Source's fix? Does it do what you were after?
