### ISSUE TITLE
[BUG] cards missing when horizontal rule present in document

### ISSUE THREAD

**Issue by AdrianSkar** [st3v3nmw/obsidian-spaced-repetition#967]
All cards within a document disappear when there's a horizontal line (---) present in the document

**To Reproduce**

1. Go to the end of the document
2. Add a horizontal line (---) before the `#flashcards` hastag for example
3. Reload

**Expected behavior**
Cards are kept regardless

**Screenshots**
Cards present:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/12052430/5fae811c-a737-41d1-a154-6aff6d0e54ff)
Cards missing:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/12052430/93c949bf-8ccb-4e3f-a537-a67abe819089)

**Versions (please complete the following information):**

-   OS: Windows 10 64b
-   Obsidian version: 1.5.12
-   Plugin version: 1.12.4
-   If on desktop, Installer version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.13 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36

[test-cards.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/15420166/test-cards.md)

**Comment by ronzulu** [comment]
Hi @AdrianSkar thanks for letting us know.

To help us reproduce, could you please post the actual markdown file (attach to your post, not copy & paste)

Cheers
Ronny

**Comment by 4Source** [comment]
Discovered similar issue but with --- inside a code block

**Comment by AdrianSkar** [comment]
> Hi @AdrianSkar thanks for letting us know.
> 
> To help us reproduce, could you please post the actual markdown file (attach to your post, not copy & paste)
> 
> Cheers Ronny

Sure! Thank you.
