### ISSUE TITLE
[Bug]: ``` ``` causes inline flashcards to not be recognized.

### ISSUE THREAD

**Issue by AnonOnFire** [st3v3nmw/obsidian-spaced-repetition#973]
### Describe the bug

if the note contains "``` any text here ```" it causes inline flashcards to not be recognized.
I did not try it for other flashcard types and it only does not work if the "``` ```" is on the same line.

### To Reproduce

above-It;; works 
``` text ```
below-it;; nope, it is not recognized 
#flashcards
( I am using ;; instead of ::)

### Expected behavior

flashcard is not recognized.

### OS of your device

Win10

### Obsidian version

V1.5.12

### Plugin version

V1.12.4

**Comment by 4Source** [comment]
Could you please share your file where it is happening 
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/38220764/44809def-2a63-4c85-be75-be5d80f874fc)

**Comment by 4Source** [comment]
@AnonOnFire if you don't share a file we can't fix your bug it is not reproducible with:

> ### To Reproduce
> above-It;; works `text` below-it;; nope, it is not recognized #flashcards ( I am using ;; instead of ::)

My test: 
[bug 973.md](https://github.com/user-attachments/files/15791647/bug.973.md)
But recognizes all 4 Flashcards 

May you also include a ``---``(Horizontal line) in your file?

**Comment by ronzulu** [comment]
Issue #967 has been fixed and has been released in the latest mainstream version 1.12.5.

I'm closing this now, but feel free to reopen if that hasn't resolved your problem.
