### ISSUE TITLE
[Bug]: Appearance change after synchronizing with mobile

### ISSUE THREAD

**Issue by talacchi** [st3v3nmw/obsidian-spaced-repetition#978]
### Describe the bug

Hello ! Since I've synchronized my vault in obisidian, the appearance of the spaced repetition plugin has shrunk, to what seems to be the mobile version. It makes it very hard to use it on Windows 11. I am not exactly familiar with coding, would someone help get it back to its original version?
Thank you very much. 

### To Reproduce

1. Open Obsidian
2. Select spaced repetition plugin
3. Open spaced repetition plugin

### Expected behavior

Desktop version of the plugin appears

### Screenshots

![Capture d'écran 2024-05-31 151129](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/51914654/1f307e3a-6ad5-4e1a-b1ab-f297d751921f)

The buttons aren't next to each others nor colored anymore.
![Capture d'écran 2024-05-31 134717](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/51914654/4e80a7d8-dd4a-46e3-adfd-8dca519c922a)

Editing a card became impossible.
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/51914654/0f6ff61b-8786-4042-84e3-8b5be8759af1)

### OS of your device

Windows 11

### Obsidian version

v1.5.12

### Plugin version

v1.12.4

### Installer version

v1.4.13

### Config file

[data.json](https://github.com/user-attachments/files/15514242/data.json)

**Comment by 4Source** [comment]
1. Can you find a styles.css under .obsidian/plugins/obsidian-spaced-repetition?
2. Any errors in developer console (CTRL+SHIFT+I)?
3. Have you tried reinstalling the plugin?

**Comment by talacchi** [comment]
Hello, thank you very much for your answer. I ended up reinstalling it and it worked fine. I didn't spot any errors in developer console, but again I'm not I'd know how to spot them at my level.

**Comment by ronzulu** [comment]
To what device did you synchronise? Did you synchronise to a mobile device, and did the issue occur when you synchronised back from it?

After you reinstalled, have you gone through the synchronisation process again? And is it all okay after completing the synchronisation?

**Comment by talacchi** [comment]
I work on windows 11 and synchronized it to my huawei P30. Now the plugin work from both devices and hasn't changed. I didn't have to go through a new synchronisation at all, it worked just fine after I reinstalled it.
