### ISSUE TITLE
[Bug]: Need to restart obsidian for Notes to be loaded as New

### ISSUE THREAD

**Issue by kaiwizz** [st3v3nmw/obsidian-spaced-repetition#980]
### Describe the bug

When I create a new note with the tag `#review` I expect it to show up as a new note under review when I save it or close the note. But I need to close and reopen obsidian for new notes to be added to the review.

### To Reproduce

1. Create a new note and add the tag `#review`
2. Close the note and open the Spaced repetition sidebar

### Expected behavior

I expected the note to be added as new note for review

### OS of your device

Win 10

### Obsidian version

1.5.12

### Plugin version

1.12.4

**Comment by ronzulu** [comment]
Hi @kaiwizz yes this is a bug, but a quicker way than restarting Obsidian or the plugin is described at:
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/862#issuecomment-1918697082

Cheers
Ronny

**Comment by kaiwizz** [comment]
Thanks for pointing it out. I somehow did not notice that this issue has already been mentioned previously.
