### ISSUE TITLE
如果笔记中有---，则该笔记不会被创建为卡片

### ISSUE THREAD

**Issue by yuhao0613** [st3v3nmw/obsidian-spaced-repetition#985]
在撰写obsidian笔记过程中，常用---语法做分割线。
近期发现，只要笔记中有---，则整个笔记不会被识别为卡片，比较影响使用体验。

**Comment by 4Source** [comment]
This issue already exist #967

**Comment by 4Source** [comment]
Duplicate of #967

**Comment by ronzulu** [comment]
Hi @yuhao0613 if you agree that this is a duplicate of #967, then please close this issue. Thanks.
