### ISSUE TITLE
[FEAT]: support file level tag

### ISSUE THREAD

**Issue by zhuoqiang** [st3v3nmw/obsidian-spaced-repetition#991]
### Describe the solution you'd like

I want tags in markdown file header (in yaml format) are also considereed as flashcoards tags

### Additional context

currently only tags in the markdown text are considered by spaced-repetition

**Comment by ronzulu** [comment]
Hi @zhuoqiang 

This works for me:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/d5bf2a0c-c46d-40c6-9828-8e027a458801)

As raw text:
```
---
tags:
  - "#flashcards/test"
---

Hello
?
Yes, this is the answer
```

If this doesn't work for you, please post your actual markdown file

**Comment by zhuoqiang** [comment]
> Hi @zhuoqiang
> 
> This works for me: ![image](https://private-user-images.githubusercontent.com/75528127/338791921-d5bf2a0c-c46d-40c6-9828-8e027a458801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTY5NjksIm5iZiI6MTcxODE1NjY2OSwicGF0aCI6Ii83NTUyODEyNy8zMzg3OTE5MjEtZDViZjJhMGMtYzQ2ZC00MGM2LTk4MjgtOGUwMjdhNDU4ODAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAxNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNDhjNjk5YTE5M2RjNWM3ZWNkMGY2YzBjODFmYzA0MDg3ZmNhYzc1MWRjZWYyZjJkYjBhM2Q2YzdlODliNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwLLxRpXPk_xjsAxnBy1_QpRbuQGOCYoNtMbc_OZo1o)
> 
> As raw text:
> 
> ```
> ---
> tags:
>   - "#flashcards/test"
> ---
> 
> Hello
> ?
> Yes, this is the answer
> ```
> 
> If this doesn't work for you, please post your actual markdown file

thanks, it works! turns out I forgot the `#` prefix in the yaml tags

**Comment by ronzulu** [comment]
Glad it worked  :-)
