### ISSUE TITLE
[Bug]: Plugin Using Old Data

### ISSUE THREAD

**Issue by adrik0622** [st3v3nmw/obsidian-spaced-repetition#992]
### Describe the bug

Hey, so I'm noticing a weird error where the plugin is using old 'placeholder' data that I had put in for the cards on the attached markdown note
[Major Method.md](https://github.com/user-attachments/files/15823513/Major.Method.md)

Basically, it seems to be using old data for some of the flash cards and it's also unpredictable each run through which ones will be using old data.

### To Reproduce

1. Import the markdown file into your obisidianMD
2. Add `#mindpalace` tag to your recognized tags
3. Run the flashcard review for mindpalace/major method
[Screencast from 2024-06-13 09-53-59.webm](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/16964984/9ca92e6d-61b8-4b13-85df-706b12c5e0c3)

### Expected behavior

The expected behavior is that the plugin looks at the available file and lists data based on the most previous write. I speculate that the file is too big so some things are loaded and others aren't but I'm not sure why that would matter, and that's pure speculation.

### OS of your device

Manjaro 6.9.3

### Obsidian version

1.6.3

### Plugin version

1.10.3

### Additional context

[Major Method.md](https://github.com/user-attachments/files/15829567/Major.Method.md)
[Screencast from 2024-06-13 09-53-59.webm](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/16964984/5d8dd951-0e11-40ad-bfd6-604b31555543)

**Comment by adrik0622** [comment]
I can confirm the actual markdown document that is being stored locally has the correct data. This is a very unfortunate bug :(

**Comment by adrik0622** [comment]
Figured it out. Problem was due to me having two of the exact same documents with the same tags, so I was getting duplicates that were old from the old document. They were named exactly the same thing so I was scratching my head trying to figure out what the problem was, but we should be good now.

**Comment by ronzulu** [comment]
Hi @adrik0622 thanks for the update
